### ISSUE TITLE
Unimplemented cast int64 to string is not supported - tensorflow_model_server

### ISSUE THREAD

**Issue by aroraakshit** [tensorflow/serving#1017]
### System information
- **OS Platform and Distribution**: Linux Ubuntu 16.04.4
- **TensorFlow Serving installed from**: binary
- **TensorFlow Serving version**: 1.8
- **Using virtual environment**

### Describe the problem
After following the steps in [Using SavedModel with Estimators](https://www.tensorflow.org/guide/saved_model#using_savedmodel_with_estimators): When sending a classification request from client, the server is not able to cast it into serialized tf example that model is expecting. 
So far, the only example of tensorflow serving's client side code that exists describes how to send images to server and it uses predict_pb2. However, in classification_pb2 you cannot create a proto object, you need to create a tensorflow.serving.input object, that in turn uses example list. This information is described as just a note in the documentation and no examples were given, hence my bug report.

### Source code / logs
The code used to export saved model and feature specifications:
```
feature_spec = {
      "ink": tf.VarLenFeature(dtype=tf.float32),
      "shape": tf.FixedLenFeature([2], dtype=tf.int64),
      "class_index": tf.FixedLenFeature([1], dtype=tf.int64)
}

# defining serving input receiver function
def serving_input_receiver_fn():
  """An input receiver that expects a serialized tf.Example."""
  serialized_tf_example = tf.placeholder(dtype=tf.string, shape=[FLAGS.batch_size], name='input_example_tensor')
  receiver_tensors = {'examples': serialized_tf_example}
  parsed_features = tf.parse_example(serialized_tf_example, feature_spec)
  parsed_features["ink"] = tf.sparse_tensor_to_dense(parsed_features["ink"])
  return tf.estimator.export.ServingInputReceiver(parsed_features, receiver_tensors)

# export saved model
estimator.export_savedmodel("path/to/serve/", serving_input_receiver_fn, strip_default_attrs=True)
print("done exporting")
```

After exporting the model, start the model server using command line tool **tensorflow_model_server**

Then using the following code on client side to generate requests:
```
from tensorflow_serving.apis import classification_pb2
from tensorflow_serving.apis import prediction_service_pb2
from tensorflow_serving.apis import input_pb2 as final_inp

features = {}
features["class_index"] = tf.train.Feature(int64_list=tf.train.Int64List(value=[classnames.index("doodle")]))
features["ink"] = tf.train.Feature(float_list=tf.train.FloatList(value=ink.flatten()))
features["shape"] = tf.train.Feature(int64_list=tf.train.Int64List(value=ink.shape))
f = tf.train.Features(feature=features)
example = tf.train.Example(features=f)
final_req = example
start = time.time()

final_att = final_inp.ExampleList()
final_att.examples.extend([final_req])
final_att1 = final_inp.Input()
final_att1.example_list.CopyFrom(final_att)
request = classification_pb2.ClassificationRequest()
request.model_spec.name = model
request.model_spec.signature_name = signature_name
request.input.CopyFrom(final_att1)
result = stub.Classify(request, 10.0)

end = time.time()
time_diff = end - start
```

Here is the error on client side:
```
Traceback (most recent call last):
  File "/home/mldev/venv/lib/python3.5/site-packages/grpc/beta/_client_adaptations.py", line 193, in _blocking_unary_unary
    credentials=_credentials(protocol_options))
  File "/home/mldev/venv/lib/python3.5/site-packages/grpc/_channel.py", line 500, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/mldev/venv/lib/python3.5/site-packages/grpc/_channel.py", line 434, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNIMPLEMENTED, Cast int64 to string is notsupported
         [[Node: Cast = Cast[DstT=DT_STRING, SrcT=DT_INT64, _output_shapes=[[2]], _device="/job:localhost/replica:0/task:0/device:CPU:0"](ArgMax)]])>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mldev/intelligent_sp/train_scripts/client.py", line 72, in <module>
    run(args.host, args.port, args.input, args.model, args.signature_name)
  File "/home/mldev/intelligent_sp/train_scripts/client.py", line 51, in run
    result = stub.Classify(request, 10.0)
  File "/home/mldev/venv/lib/python3.5/site-packages/grpc/beta/_client_adaptations.py", line 309, in __call__
    self._request_serializer, self._response_deserializer)
  File "/home/mldev/venv/lib/python3.5/site-packages/grpc/beta/_client_adaptations.py", line 195, in _blocking_unary_unary
    raise _abortion_error(rpc_error_call)
grpc.framework.interfaces.face.face.LocalError: LocalError(code=StatusCode.UNIMPLEMENTED, details="Cast int64 to string isnot supported
         [[Node: Cast = Cast[DstT=DT_STRING, SrcT=DT_INT64, _output_shapes=[[2]], _device="/job:localhost/replica:0/task:0/device:CPU:0"](ArgMax)]]")
```

Here are the server logs:
```
2018-07-26 11:49:51.497657: I tensorflow_serving/model_servers/main.cc:153] Building single TensorFlow model file config:  model_name: 1532547336 model_base_path: /home/mldev/intelligent_sp/models/model6/serve/
2018-07-26 11:49:51.497959: I tensorflow_serving/model_servers/server_core.cc:459] Adding/updating models.
2018-07-26 11:49:51.497993: I tensorflow_serving/model_servers/server_core.cc:514]  (Re-)adding model: 1532547336
2018-07-26 11:49:51.598635: I tensorflow_serving/core/basic_manager.cc:716] Successfully reserved resources to load servable {name: 1532547336 version: 1532547336}
2018-07-26 11:49:51.598718: I tensorflow_serving/core/loader_harness.cc:66] Approving load for servable version {name: 1532547336 version: 1532547336}
2018-07-26 11:49:51.598750: I tensorflow_serving/core/loader_harness.cc:74] Loading servable version {name: 1532547336 version: 1532547336}
2018-07-26 11:49:51.598807: I external/org_tensorflow/tensorflow/contrib/session_bundle/bundle_shim.cc:360] Attempting to load native SavedModelBundle in bundle-shim from: /home/mldev/intelligent_sp/models/model6/serve/1532547336
2018-07-26 11:49:51.598854: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:242] Loading SavedModel with tags: { serve }; from: /home/mldev/intelligent_sp/models/model6/serve/1532547336
2018-07-26 11:49:51.658431: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:161] Restoring SavedModel bundle.
2018-07-26 11:49:51.682085: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:196] Running LegacyInitOp on SavedModel bundle.
2018-07-26 11:49:51.699838: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:291] SavedModel load for tags { serve }; Status: success. Took 100668 microseconds.
2018-07-26 11:49:51.699922: I tensorflow_serving/servables/tensorflow/saved_model_warmup.cc:83] No warmup data file found at /home/mldev/intelligent_sp/models/model6/serve/1532547336/assets.extra/tf_serving_warmup_requests
2018-07-26 11:49:51.701289: I tensorflow_serving/core/loader_harness.cc:86] Successfully loaded servable version {name: 1532547336 version: 1532547336}
2018-07-26 11:49:51.715439: I tensorflow_serving/model_servers/main.cc:323] Running ModelServer at 0.0.0.0:9000 ...
2018-07-26 11:52:09.049097: W external/org_tensorflow/tensorflow/core/framework/op_kernel.cc:1295] OP_REQUIRES failed at cast_op.cc:77 : Unimplemented: Cast int64 to string is not supported
2018-07-26 11:52:09.049173: E external/org_tensorflow/tensorflow/core/common_runtime/executor.cc:696] Executor failed to create kernel. Unimplemented: Cast int64 tostring is not supported
         [[Node: Cast = Cast[DstT=DT_STRING, SrcT=DT_INT64, _output_shapes=[[2]], _device="/job:localhost/replica:0/task:0/device:CPU:0"](ArgMax)]]
```

**Comment by aroraakshit** [comment]
Yes, it is a placeholder when I export my model, just like described [in the documentation of serving_input_receiver_function](https://www.tensorflow.org/guide/saved_model#using_savedmodel_with_estimators). 

I tried serializing the tf example proto in client code like this:
```
final_req = example.SerializeToString()
start = time.time()

final_att = final_inp.ExampleList()
final_att.examples.extend([final_req])
final_att1 = final_inp.Input()
final_att1.example_list.CopyFrom(final_att)
request = classification_pb2.ClassificationRequest()
request.model_spec.name = model
request.model_spec.signature_name = signature_name
request.input.CopyFrom(final_att1)
result = stub.Classify(request, 10.0)
```

But it gave the following error when I ran  it:
```
Traceback (most recent call last):
  File "/home/mldev/intelligent_sp/train_scripts/client.py", line 65, in <module>
    run(args.host, args.port, args.input, args.model, args.signature_name)
  File "/home/mldev/intelligent_sp/train_scripts/client.py", line 37, in run
    final_att.examples.extend([final_req])
TypeError: Not a cmessage
```

It looks like the request in classificaiton_pb2 has to always be a cmessage and cannot accept bytes.
