### ISSUE TITLE
tensorflow_model_server core dumped 

### ISSUE THREAD

**Issue by lovejoy** [tensorflow/serving#1179]
## Bug Report
If this is a bug report, please fill out the following form in full:

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
 uname -a
Linux cdptest-84f72ac7 3.10.0-327.28.3.el7.jd_1311.x86_64 #1 SMP Mon Oct 16 17:19:08 CST 2017 x86_64 x86_64 x86_64 GNU/Linux
 lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.5 LTS
Release:        16.04
Codename:       xenial
- **TensorFlow Serving installed from (source or binary)**:
docker image 

- **TensorFlow Serving version**:
tensorflow_model_server --version
TensorFlow ModelServer: 1.10.0-dev
TensorFlow Library: 1.11.0
### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in
TensorFlow Serving.
core dump 
```
Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `tensorflow_model_server --port=8500 --rest_api_port=8501 --model_config_file=/e'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000d79d15 in std::_Function_handler<void (long, long), Eigen::internal::TensorExecutor<Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<float, 3, 1, long>, 16, Eigen::MakePointer>, Eigen::TensorGeneratorOp<tensorflow::generator::ReverseGenerator<float, int, 3ul>, Eigen::TensorMap<Eigen::Tensor<float const, 3, 1, long>, 16, Eigen::MakePointer> const> const> const, Eigen::ThreadPoolDevice, true>::run(Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<float, 3, 1, long>, 16, Eigen::MakePointer>, Eigen::TensorGeneratorOp<tensorflow::generator::ReverseGenerator<float, int, 3ul>, Eigen::TensorMap<Eigen::Tensor<float const, 3, 1, long>, 16, Eigen::MakePointer> const> const> const&, Eigen::ThreadPoolDevice const&)::{lambda(long, long)#1}>::_M_invoke(std::_Any_data const&, long&&, std::_Any_data const&) ()
[Current thread is 1 (Thread 0x7fcb807f0700 (LWP 2448))]
(gdb) where
#0  0x0000000000d79d15 in std::_Function_handler<void (long, long), Eigen::internal::TensorExecutor<Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<float, 3, 1, long>, 16, Eigen::MakePointer>, Eigen::TensorGeneratorOp<tensorflow::generator::ReverseGenerator<float, int, 3ul>, Eigen::TensorMap<Eigen::Tensor<float const, 3, 1, long>, 16, Eigen::MakePointer> const> const> const, Eigen::ThreadPoolDevice, true>::run(Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<float, 3, 1, long>, 16, Eigen::MakePointer>, Eigen::TensorGeneratorOp<tensorflow::generator::ReverseGenerator<float, int, 3ul>, Eigen::TensorMap<Eigen::Tensor<float const, 3, 1, long>, 16, Eigen::MakePointer> const> const> const&, Eigen::ThreadPoolDevice const&)::{lambda(long, long)#1}>::_M_invoke(std::_Any_data const&, long&&, std::_Any_data const&) ()
#1  0x00000000007d62df in std::_Function_handler<void (long, long), Eigen::ThreadPoolDevice::parallelFor(long, Eigen::TensorOpCost const&, std::function<long (long)>, std::function<void (long, long)>) const::{lambda(long, long)#1}>::_M_invoke(std::_Any_data const&, long&&, std::_Any_data const&) ()
#2  0x00000000007d63d7 in std::_Function_handler<void (long, long), Eigen::ThreadPoolDevice::parallelFor(long, Eigen::TensorOpCost const&, std::function<long (long)>, std::function<void (long, long)>) const::{lambda(long, long)#1}>::_M_invoke(std::_Any_data const&, long&&, std::_Any_data const&) ()
#3  0x00000000007d63d7 in std::_Function_handler<void (long, long), Eigen::ThreadPoolDevice::parallelFor(long, Eigen::TensorOpCost const&, std::function<long (long)>, std::function<void (long, long)>) const::{lambda(long, long)#1}>::_M_invoke(std::_Any_data const&, long&&, std::_Any_data const&) ()
#4  0x00000000007d63d7 in std::_Function_handler<void (long, long), Eigen::ThreadPoolDevice::parallelFor(long, Eigen::TensorOpCost const&, std::function<long (long)>, std::function<void (long, long)>) const::{lambda(long, long)#1}>::_M_invoke(std::_Any_data const&, long&&, std::_Any_data const&) ()
#5  0x00000000007d63d7 in std::_Function_handler<void (long, long), Eigen::ThreadPoolDevice::parallelFor(long, Eigen::TensorOpCost const&, std::function<long (long)>, std::function<void (long, long)>) const::{lambda(long, long)#1}>::_M_invoke(std::_Any_data const&, long&&, std::_Any_data const&) ()
#6  0x00000000007d63d7 in std::_Function_handler<void (long, long), Eigen::ThreadPoolDevice::parallelFor(long, Eigen::TensorOpCost const&, std::function<long (long)>, std::function<void (long, long)>) const::{lambda(long, long)#1}>::_M_invoke(std::_Any_data const&, long&&, std::_Any_data const&) ()
#7  0x00000000007d4c03 in std::_Function_handler<void (), Eigen::ThreadPoolDevice::parallelFor(long, Eigen::TensorOpCost const&, std::function<long (long)>, std::function<void (long, long)>) const::{lambda(long, long)#1}::operator()(long, long) const::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
#8  0x00000000030c3951 in Eigen::NonBlockingThreadPoolTempl<tensorflow::thread::EigenEnvironment>::WorkerLoop(int) ()
#9  0x00000000030c1add in std::_Function_handler<void (), tensorflow::thread::EigenEnvironment::CreateThread(std::function<void ()>)::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
#10 0x00007fcbe57eec80 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#11 0x00007fcbe61d46ba in start_thread (arg=0x7fcb807f0700) at pthread_create.c:333
#12 0x00007fcbe525d41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

### Exact Steps to Reproduce
Please include all steps necessary for someone to reproduce this issue on their
own machine. If not, skip this section.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached. Try to provide a reproducible test case that is the bare
minimum necessary to generate the problem.

**Comment by gautamvasudevan** [comment]
Please fill out the form completely, including repro steps.
