### ISSUE TITLE
ImportError: No module named _pywrap_tensorflow

### ISSUE THREAD

**Issue by killuabone** [tensorflow/serving#118]
Hi, I'm following the Serving Inception Model with TensorFlow Serving and Kubernetes tutorial. I'm using docker on my mac. I get this error when I Export Inception model in container.
```
root@9b82edf4d8e7:/serving# bazel-bin/tensorflow_serving/example/inception_export --checkpoint_dir=inception-v3 --export_dir=inception-export
Traceback (most recent call last):
  File "/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/tensorflow_serving/example/inception_export.py", line 25, in <module>
    import tensorflow as tf
  File "/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/external/org_tensorflow/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/external/org_tensorflow/tensorflow/python/__init__.py", line 48, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/external/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/external/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 20, in swig_import_helper
    import _pywrap_tensorflow
ImportError: No module named _pywrap_tensorflow
```

**Comment by cag51** [comment]
Old, but I found this so will post for future Googlers.

The problem (for me) was that my numpy was v1.08, whereas tensorflow wants v1.11.  Upgrading numpy on El Capitan may not be easy; I had to (a) reboot in recovery mode, (b) open terminal and type "csrutil disable", (c) boot normally and upgrade numpy (pip2 install --user --upgrade numpy), (d) reboot in recovery mode again, and (e) open terminal and type "csrutil enable".
