### ISSUE TITLE
Cannot find numpy

### ISSUE THREAD

**Issue by Ian09** [tensorflow/serving#12]
Hi, 

I tried to install serving of tensorflow. My numpy is compiled with openblas and is installed at /usr/lib/python2.7/site-packages/numpy (I used Linux Mint 17.3). While I am installing tensorflow_serving, the error happens, saying cannot find numpy. 

It seems that bazel only seeks numpy at /usr/lib/python2.7/dist-packages, NOT /usr/lib/python2.7/site-packages/numpy. 

I linked the /usr/lib/python2.7/site-packages/numpy to /usr/lib/python2.7/dist-packages, and bazel can find numpy, but it cannot find libopenblas.so.0, which is installed at /usr/local. But bazel throw an error saying that it cannot find the .so file. 

Is it a bug to fix or should I do something else?

Thanks

**===ERROR1: Cannot find numpy==========**
dnn01@DL02 ~/serving $ bazel test tensorflow_serving/...
INFO: Found 90 targets and 37 test targets...
ERROR: /home/dnn01/serving/tensorflow_serving/session_bundle/example/BUILD:34:1: Executing genrule //tensorflow_serving/session_bundle/example:half_plus_two failed: bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped).
/home/dnn01/.cache/bazel/_bazel_dnn01/681ee4690332907d7b23cc5c101faf32/serving/bazel-out/host/bin/tensorflow_serving/session_bundle/example/export_half_plus_two.runfiles:/home/dnn01/.cache/bazel/_bazel_dnn01/681ee4690332907d7b23cc5c101faf32/serving/bazel-out/host/bin/tensorflow_serving/session_bundle/example/export_half_plus_two.runfiles/:/home/dnn01/.cache/bazel/_bazel_dnn01/681ee4690332907d7b23cc5c101faf32/serving/bazel-out/host/bin/tensorflow_serving/session_bundle/example/export_half_plus_two.runfiles/external/tf:/home/dnn01/.cache/bazel/_bazel_dnn01/681ee4690332907d7b23cc5c101faf32/serving/bazel-out/host/bin/tensorflow_serving/session_bundle/example/export_half_plus_two.runfiles/external/six_archive
['/home/dnn01/.cache/bazel/_bazel_dnn01/681ee4690332907d7b23cc5c101faf32/serving/bazel-out/host/bin/tensorflow_serving/session_bundle/example/export_half_plus_two.runfiles/tensorflow_serving/session_bundle/example', '/home/dnn01/.cache/bazel/_bazel_dnn01/681ee4690332907d7b23cc5c101faf32/serving/bazel-out/host/bin/tensorflow_serving/session_bundle/example/export_half_plus_two.runfiles', '/home/dnn01/.cache/bazel/_bazel_dnn01/681ee4690332907d7b23cc5c101faf32/serving/bazel-out/host/bin/tensorflow_serving/session_bundle/example/export_half_plus_two.runfiles/external/tf', '/home/dnn01/.cache/bazel/_bazel_dnn01/681ee4690332907d7b23cc5c101faf32/serving/bazel-out/host/bin/tensorflow_serving/session_bundle/example/export_half_plus_two.runfiles/external/six_archive', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/python2.7/dist-packages/ubuntu-sso-client']
Traceback (most recent call last):
  File "/home/dnn01/.cache/bazel/_bazel_dnn01/681ee4690332907d7b23cc5c101faf32/serving/bazel-out/host/bin/tensorflow_serving/session_bundle/example/export_half_plus_two.runfiles/tensorflow_serving/session_bundle/example/export_half_plus_two.py", line 31, in <module>
    import tensorflow as tf
  File "/home/dnn01/.cache/bazel/_bazel_dnn01/681ee4690332907d7b23cc5c101faf32/serving/bazel-out/host/bin/tensorflow_serving/session_bundle/example/export_half_plus_two.runfiles/external/tf/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/home/dnn01/.cache/bazel/_bazel_dnn01/681ee4690332907d7b23cc5c101faf32/serving/bazel-out/host/bin/tensorflow_serving/session_bundle/example/export_half_plus_two.runfiles/external/tf/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow import contrib
  File "/home/dnn01/.cache/bazel/_bazel_dnn01/681ee4690332907d7b23cc5c101faf32/serving/bazel-out/host/bin/tensorflow_serving/session_bundle/example/export_half_plus_two.runfiles/external/tf/tensorflow/contrib/__init__.py", line 23, in <module>
    from tensorflow.contrib import layers
  File "/home/dnn01/.cache/bazel/_bazel_dnn01/681ee4690332907d7b23cc5c101faf32/serving/bazel-out/host/bin/tensorflow_serving/session_bundle/example/export_half_plus_two.runfiles/external/tf/tensorflow/contrib/layers/__init__.py", line 67, in <module>
    from tensorflow.contrib.layers.python.framework.tensor_util import *
  File "/home/dnn01/.cache/bazel/_bazel_dnn01/681ee4690332907d7b23cc5c101faf32/serving/bazel-out/host/bin/tensorflow_serving/session_bundle/example/export_half_plus_two.runfiles/external/tf/tensorflow/contrib/layers/python/framework/tensor_util.py", line 20, in <module>
    from tensorflow.python.framework import dtypes
  File "/home/dnn01/.cache/bazel/_bazel_dnn01/681ee4690332907d7b23cc5c101faf32/serving/bazel-out/host/bin/tensorflow_serving/session_bundle/example/export_half_plus_two.runfiles/external/tf/tensorflow/python/framework/dtypes.py", line 24, in <module>
    import numpy as np
ImportError: No module named numpy

**===ERROR2: Cannot find libopenblas==========**
ERROR: /home/dnn01/serving/tensorflow_serving/session_bundle/example/BUILD:34:1: Executing genrule //tensorflow_serving/session_bundle/example:half_plus_two failed: bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped).
/home/dnn01/.cache/bazel/_bazel_dnn01/681ee4690332907d7b23cc5c101faf32/serving/bazel-out/host/bin/tensorflow_serving/session_bundle/example/export_half_plus_two.runfiles:/home/dnn01/.cache/bazel/_bazel_dnn01/681ee4690332907d7b23cc5c101faf32/serving/bazel-out/host/bin/tensorflow_serving/session_bundle/example/export_half_plus_two.runfiles/:/home/dnn01/.cache/bazel/_bazel_dnn01/681ee4690332907d7b23cc5c101faf32/serving/bazel-out/host/bin/tensorflow_serving/session_bundle/example/export_half_plus_two.runfiles/external/tf:/home/dnn01/.cache/bazel/_bazel_dnn01/681ee4690332907d7b23cc5c101faf32/serving/bazel-out/host/bin/tensorflow_serving/session_bundle/example/export_half_plus_two.runfiles/external/six_archive
['/home/dnn01/.cache/bazel/_bazel_dnn01/681ee4690332907d7b23cc5c101faf32/serving/bazel-out/host/bin/tensorflow_serving/session_bundle/example/export_half_plus_two.runfiles/tensorflow_serving/session_bundle/example', '/home/dnn01/.cache/bazel/_bazel_dnn01/681ee4690332907d7b23cc5c101faf32/serving/bazel-out/host/bin/tensorflow_serving/session_bundle/example/export_half_plus_two.runfiles', '/home/dnn01/.cache/bazel/_bazel_dnn01/681ee4690332907d7b23cc5c101faf32/serving/bazel-out/host/bin/tensorflow_serving/session_bundle/example/export_half_plus_two.runfiles/external/tf', '/home/dnn01/.cache/bazel/_bazel_dnn01/681ee4690332907d7b23cc5c101faf32/serving/bazel-out/host/bin/tensorflow_serving/session_bundle/example/export_half_plus_two.runfiles/external/six_archive', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gtk-2.0', '/usr/lib/python2.7/dist-packages/ubuntu-sso-client']
Traceback (most recent call last):
  File "/home/dnn01/.cache/bazel/_bazel_dnn01/681ee4690332907d7b23cc5c101faf32/serving/bazel-out/host/bin/tensorflow_serving/session_bundle/example/export_half_plus_two.runfiles/tensorflow_serving/session_bundle/example/export_half_plus_two.py", line 31, in <module>
    import tensorflow as tf
  File "/home/dnn01/.cache/bazel/_bazel_dnn01/681ee4690332907d7b23cc5c101faf32/serving/bazel-out/host/bin/tensorflow_serving/session_bundle/example/export_half_plus_two.runfiles/external/tf/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/home/dnn01/.cache/bazel/_bazel_dnn01/681ee4690332907d7b23cc5c101faf32/serving/bazel-out/host/bin/tensorflow_serving/session_bundle/example/export_half_plus_two.runfiles/external/tf/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow import contrib
  File "/home/dnn01/.cache/bazel/_bazel_dnn01/681ee4690332907d7b23cc5c101faf32/serving/bazel-out/host/bin/tensorflow_serving/session_bundle/example/export_half_plus_two.runfiles/external/tf/tensorflow/contrib/__init__.py", line 23, in <module>
    from tensorflow.contrib import layers
  File "/home/dnn01/.cache/bazel/_bazel_dnn01/681ee4690332907d7b23cc5c101faf32/serving/bazel-out/host/bin/tensorflow_serving/session_bundle/example/export_half_plus_two.runfiles/external/tf/tensorflow/contrib/layers/__init__.py", line 67, in <module>
    from tensorflow.contrib.layers.python.framework.tensor_util import *
  File "/home/dnn01/.cache/bazel/_bazel_dnn01/681ee4690332907d7b23cc5c101faf32/serving/bazel-out/host/bin/tensorflow_serving/session_bundle/example/export_half_plus_two.runfiles/external/tf/tensorflow/contrib/layers/python/framework/tensor_util.py", line 20, in <module>
    from tensorflow.python.framework import dtypes
  File "/home/dnn01/.cache/bazel/_bazel_dnn01/681ee4690332907d7b23cc5c101faf32/serving/bazel-out/host/bin/tensorflow_serving/session_bundle/example/export_half_plus_two.runfiles/external/tf/tensorflow/python/framework/dtypes.py", line 24, in <module>
    import numpy as np
  File "/usr/lib/python2.7/dist-packages/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs
  File "/usr/lib/python2.7/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/lib/python2.7/dist-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/lib/python2.7/dist-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/lib/python2.7/dist-packages/numpy/core/__init__.py", line 14, in <module>
    from . import multiarray
ImportError: libopenblas.so.0: cannot open shared object file: No such file or directory

**Comment by kirilg** [comment]
I'm not sure exactly how it was compiled/installed, but it seems like /usr/lib/python2.7/site-packages is not in the python path so it doesn't get searched.

Instead of compiling with openblas, try installing numpy with apt-get as in https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/setup.md

sudo apt-get install python-numpy python-dev

You can also use a Docker container (http://tensorflow.github.io/serving/docker) to set up the full environment and then compile Tensorflow serving there. This container will have everything needed to compile. dockerfile is in https://github.com/tensorflow/serving/blob/master/tensorflow_serving/tools/docker/Dockerfile.devel

**Comment by Ian09** [comment]
Hi Kiril,

Thanks for the reply!
I compiled tensorflow_serving with the options "--genrule_strategy=standalone --spawn_strategy=standalone", 
bazel build --genrule_strategy=standalone --spawn_strategy=standalone tensorflow_serving/...

And it can be compiled and pass the test. 

Is it a good way to solve this problem?

**Comment by kirilg** [comment]
Sorry for the late reply. Yes, that's a good way to solve this problem. I'm actually adding it to our bazel.rc file that will be pushed soon.
