### ISSUE TITLE
Bazel build error on TFS in window

### ISSUE THREAD

**Issue by zeqinLi** [tensorflow/serving#1238]
Bazel build error on TFS in window：
OS:win 10
tensorflow:1.9.0
python:3.5.8
Bazel:0.20.0
JDK:1.8

bazel build -c opt tensorflow_serving/...
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
c:\users\zeqin\serving/.bazelrc
INFO: Invocation ID: c8e6dfee-1b62-48eb-bc6b-0d218a9a6cbe
WARNING: C:/users/zeqin/serving/tensorflow_serving/servables/tensorflow/BUILD:578:1: in cc_library rule //tensorflow_serving/servables/tensorflow:classifier: target '//tensorflow_serving/servables/tensorflow:classifier' depends on deprecated target '@org_tensorflow//tensorflow/contrib/session_bundle:session_bundle_lite': No longer supported. Switch to SavedModel immediately.
WARNING: C:/users/zeqin/serving/tensorflow_serving/servables/tensorflow/BUILD:578:1: in cc_library rule //tensorflow_serving/servables/tensorflow:classifier: target '//tensorflow_serving/servables/tensorflow:classifier' depends on deprecated target '@org_tensorflow//tensorflow/contrib/session_bundle:signature_lite': No longer supported. Switch to SavedModel immediately.
WARNING: C:/users/zeqin/serving/tensorflow_serving/servables/tensorflow/BUILD:710:1: in cc_library rule //tensorflow_serving/servables/tensorflow:regressor: target '//tensorflow_serving/servables/tensorflow:regressor' depends on deprecated target '@org_tensorflow//tensorflow/contrib/session_bundle:session_bundle_lite': No longer supported. Switch to SavedModel immediately.
WARNING: C:/users/zeqin/serving/tensorflow_serving/servables/tensorflow/BUILD:710:1: in cc_library rule //tensorflow_serving/servables/tensorflow:regressor: target '//tensorflow_serving/servables/tensorflow:regressor' depends on deprecated target '@org_tensorflow//tensorflow/contrib/session_bundle:signature_lite': No longer supported. Switch to SavedModel immediately.
WARNING: C:/users/zeqin/serving/tensorflow_serving/servables/tensorflow/BUILD:437:1: in cc_library rule //tensorflow_serving/servables/tensorflow:predict_util: target '//tensorflow_serving/servables/tensorflow:predict_util' depends on deprecated target '@org_tensorflow//tensorflow/contrib/session_bundle:session_bundle': No longer supported. Switch to SavedModel immediately.
WARNING: C:/users/zeqin/serving/tensorflow_serving/servables/tensorflow/BUILD:437:1: in cc_library rule //tensorflow_serving/servables/tensorflow:predict_util: target '//tensorflow_serving/servables/tensorflow:predict_util' depends on deprecated target '@org_tensorflow//tensorflow/contrib/session_bundle:signature': No longer supported. Switch to SavedModel immediately.
WARNING: C:/users/zeqin/serving/tensorflow_serving/servables/tensorflow/BUILD:757:1: in cc_library rule //tensorflow_serving/servables/tensorflow:multi_inference: target '//tensorflow_serving/servables/tensorflow:multi_inference' depends on deprecated target '@org_tensorflow//tensorflow/contrib/session_bundle:session_bundle': No longer supported. Switch to SavedModel immediately.
WARNING: C:/users/zeqin/serving/tensorflow_serving/servables/tensorflow/BUILD:121:1: in cc_library rule //tensorflow_serving/servables/tensorflow:session_bundle_factory: target '//tensorflow_serving/servables/tensorflow:session_bundle_factory' depends on deprecated target '@org_tensorflow//tensorflow/contrib/session_bundle:session_bundle': No longer supported. Switch to SavedModel immediately.
WARNING: C:/users/zeqin/serving/tensorflow_serving/servables/tensorflow/BUILD:209:1: in cc_library rule //tensorflow_serving/servables/tensorflow:session_bundle_source_adapter: target '//tensorflow_serving/servables/tensorflow:session_bundle_source_adapter' depends on deprecated target '@org_tensorflow//tensorflow/contrib/session_bundle:session_bundle': No longer supported. Switch to SavedModel immediately.
WARNING: C:/users/zeqin/serving/tensorflow_serving/servables/tensorflow/BUILD:668:1: in cc_library rule //tensorflow_serving/servables/tensorflow:regression_service: target '//tensorflow_serving/servables/tensorflow:regression_service' depends on deprecated target '@org_tensorflow//tensorflow/contrib/session_bundle:session_bundle': No longer supported. Switch to SavedModel immediately.
WARNING: C:/users/zeqin/serving/tensorflow_serving/servables/tensorflow/BUILD:626:1: in cc_library rule //tensorflow_serving/servables/tensorflow:classification_service: target '//tensorflow_serving/servables/tensorflow:classification_service' depends on deprecated target '@org_tensorflow//tensorflow/contrib/session_bundle:session_bundle': No longer supported. Switch to SavedModel immediately.
WARNING: C:/users/zeqin/serving/tensorflow_serving/servables/tensorflow/BUILD:491:1: in cc_library rule //tensorflow_serving/servables/tensorflow:get_model_metadata_impl: target '//tensorflow_serving/servables/tensorflow:get_model_metadata_impl' depends on deprecated target '@org_tensorflow//tensorflow/contrib/session_bundle:session_bundle': No longer supported. Switch to SavedModel immediately.
WARNING: C:/users/zeqin/serving/tensorflow_serving/servables/tensorflow/BUILD:626:1: in cc_library rule //tensorflow_serving/servables/tensorflow:classification_service: target '//tensorflow_serving/servables/tensorflow:classification_service' depends on deprecated target '@org_tensorflow//tensorflow/contrib/session_bundle:signature': No longer supported. Switch to SavedModel immediately.
WARNING: C:/users/zeqin/serving/tensorflow_serving/servables/tensorflow/BUILD:668:1: in cc_library rule //tensorflow_serving/servables/tensorflow:regression_service: target '//tensorflow_serving/servables/tensorflow:regression_service' depends on deprecated target '@org_tensorflow//tensorflow/contrib/session_bundle:signature': No longer supported. Switch to SavedModel immediately.
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node '//tensorflow_serving/model_servers:tensorflow_model_server BuildConfigurationValue.Key[fbb5c182ce936aa213e4c6084c4e8320] false' (requested by nodes '//tensorflow_serving/model_servers:tensorflow_model_server_tar BuildConfigurationValue.Key[fbb5c182ce936aa213e4c6084c4e8320] false', '//tensorflow_serving/model_servers:tensorflow_model_server_beta_grpc_test BuildConfigurationValue.Key[fbb5c182ce936aa213e4c6084c4e8320] false', '//tensorflow_serving/model_servers:tensorflow_model_server_test BuildConfigurationValue.Key[fbb5c182ce936aa213e4c6084c4e8320] false')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:499)        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.localPopAndExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:127)
        at com.google.devtools.build.lib.rules.cpp.CppLinkstampCompileHelper.getVariables(CppLinkstampCompileHelper.java:141)
        at com.google.devtools.build.lib.rules.cpp.CppLinkstampCompileHelper.createLinkstampCompileAction(CppLinkstampCompileHelper.java:56)
        at com.google.devtools.build.lib.rules.cpp.CppLinkActionBuilder.build(CppLinkActionBuilder.java:1000)
        at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.createDynamicLibrary(CcLinkingHelper.java:709)
        at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.createCcLinkActions(CcLinkingHelper.java:439)
        at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.link(CcLinkingHelper.java:356)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.createTransitiveLinkingActions(CcBinary.java:684)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.init(CcBinary.java:399)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.create(CcBinary.java:240)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.create(CcBinary.java:76)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:323)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:207)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:728)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:783)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:326)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:422)        ... 6 more

INFO: Elapsed time: 20.028s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (339 packages loaded, 17101 targets configured)
    Fetching @remotejdk_win; fetching 14s
Internal error thrown during build. Printing stack trace: java.lang.RuntimeException: Unrecoverable error while evaluating node '//tensorflow_serving/model_servers:tensorflow_model_server BuildConfigurationValue.Key[fbb5c182ce936aa213e4c6084c4e8320] false' (requested by nodes '//tensorflow_serving/model_servers:tensorflow_model_server_tar BuildConfigurationValue.Key[fbb5c182ce936aa213e4c6084c4e8320] false', '//tensorflow_serving/model_servers:tensorflow_model_server_beta_grpc_test BuildConfigurationValue.Key[fbb5c182ce936aa213e4c6084c4e8320] false', '//tensorflow_serving/model_servers:tensorflow_model_server_test BuildConfigurationValue.Key[fbb5c182ce936aa213e4c6084c4e8320] false')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:499)        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.localPopAndExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:127)
        at com.google.devtools.build.lib.rules.cpp.CppLinkstampCompileHelper.getVariables(CppLinkstampCompileHelper.java:141)
        at com.google.devtools.build.lib.rules.cpp.CppLinkstampCompileHelper.createLinkstampCompileAction(CppLinkstampCompileHelper.java:56)
        at com.google.devtools.build.lib.rules.cpp.CppLinkActionBuilder.build(CppLinkActionBuilder.java:1000)
        at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.createDynamicLibrary(CcLinkingHelper.java:709)
        at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.createCcLinkActions(CcLinkingHelper.java:439)
        at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.link(CcLinkingHelper.java:356)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.createTransitiveLinkingActions(CcBinary.java:684)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.init(CcBinary.java:399)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.create(CcBinary.java:240)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.create(CcBinary.java:76)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:323)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:207)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:728)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:783)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:326)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:422)        ... 6 more
java.lang.RuntimeException: Unrecoverable error while evaluating node '//tensorflow_serving/model_servers:tensorflow_model_server BuildConfigurationValue.Key[fbb5c182ce936aa213e4c6084c4e8320] false' (requested by nodes '//tensorflow_serving/model_servers:tensorflow_model_server_tar BuildConfigurationValue.Key[fbb5c182ce936aa213e4c6084c4e8320] false', '//tensorflow_serving/model_servers:tensorflow_model_server_beta_grpc_test BuildConfigurationValue.Key[fbb5c182ce936aa213e4c6084c4e8320] false', '//tensorflow_serving/model_servers:tensorflow_model_server_test BuildConfigurationValue.Key[fbb5c182ce936aa213e4c6084c4e8320] false')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:499)        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.localPopAndExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:127)
        at com.google.devtools.build.lib.rules.cpp.CppLinkstampCompileHelper.getVariables(CppLinkstampCompileHelper.java:141)
        at com.google.devtools.build.lib.rules.cpp.CppLinkstampCompileHelper.createLinkstampCompileAction(CppLinkstampCompileHelper.java:56)
        at com.google.devtools.build.lib.rules.cpp.CppLinkActionBuilder.build(CppLinkActionBuilder.java:1000)
        at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.createDynamicLibrary(CcLinkingHelper.java:709)
        at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.createCcLinkActions(CcLinkingHelper.java:439)
        at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.link(CcLinkingHelper.java:356)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.createTransitiveLinkingActions(CcBinary.java:684)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.init(CcBinary.java:399)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.create(CcBinary.java:240)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.create(CcBinary.java:76)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:323)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:207)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:728)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:783)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:326)
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:422)        ... 6 more
java.lang.RuntimeException: Unrecoverable error while evaluating node '//tensorflow_serving/model_servers:tensorflow_model_server BuildConfigurationValue.Key[fbb5c182ce936aa213e4c6084c4e8320] false' (requested by nodes '//tensorflow_serving/model_servers:tensorflow_model_server_tar BuildConfigurationValue.Key[fbb5c182ce936aa213e4c6084c4e8320] false', '//tensorflow_serving/model_servers:tensorflow_model_server_beta_grpc_test BuildConfigurationValue.Key[fbb5c182ce936aa213e4c6084c4e8320] false', '//tensorflow_serving/model_servers:tensorflow_model_server_test BuildConfigurationValue.Key[fbb5c182ce936aa213e4c6084c4e8320] false')
        at com.google.devtools.build.skyframe.AbstractParallelEvaluator$Evaluate.run(AbstractParallelEvaluator.java:499)        at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:368)
        at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.localPopAndExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:127)
        at com.google.devtools.build.lib.rules.cpp.CppLinkstampCompileHelper.getVariables(CppLinkstampCompileHelper.java:141)
        at com.google.devtools.build.lib.rules.cpp.CppLinkstampCompileHelper.createLinkstampCompileAction(CppLinkstampCompileHelper.java:56)
        at com.google.devtools.build.lib.rules.cpp.CppLinkActionBuilder.build(CppLinkActionBuilder.java:1000)
        at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.createDynamicLibrary(CcLinkingHelper.java:709)
        at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.createCcLinkActions(CcLinkingHelper.java:439)
        at com.google.devtools.build.lib.rules.cpp.CcLinkingHelper.link(CcLinkingHelper.java:356)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.createTransitiveLinkingActions(CcBinary.java:684)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.init(CcBinary.java:399)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.create(CcBinary.java:240)
        at com.google.devtools.build.lib.rules.cpp.CcBinary.create(CcBinary.java:76)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:323)
        at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:207)
        at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:728)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:783)
        at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:326)
FAILED: Build did NOT complete successfully (339 packages loaded, 17101 targets configured)
    Fetching @remotejdk_win; fetching 14s

Server terminated abruptly (error code: 14, error message: '', log file: 'c:\users\zeqin\_bazel_zeqin\rwulk6q3/server/jvm.out')

**Comment by hgadig** [comment]
Please note that we do not officially support Tensorflow Serving beyond Ubuntu.
But I can advise you to use Docker(if it works for your use case). Also if you succeed to build in Windows, we will be happy to accept a PR with all the steps documented.

**Comment by zeqinLi** [comment]
If I use Docker,GPU cannot be invoked under Windows system.So  I have to build in windows.Is there any other solution?Thanks！

**Comment by hgadig** [comment]
> If I use Docker,GPU cannot be invoked under Windows system.So I have to build in windows.Is there any other solution?Thanks！

As I mentioned, we suggest Docker only if it fits the use case. However, based on your scenario we don't have any concrete solution for this(it's just trial and documenting then submitting a PR to help others) as we do not officially support TFS for Windows.

**Comment by qunsorber** [comment]
@Harshini-Gadige I finished building this project source code on Windows 10 without docker, modifed same souce code and build scripts, and it worked well. so I wonder whether you still need windows support, I'd like to share the my work with anyone who need it.
