### ISSUE TITLE
Error in tensorflow export while exporting the model multiple times.

### ISSUE THREAD

**Issue by pradyumnanpk** [tensorflow/serving#131]
I implemented an online machine learning algorithm using tensorflow serving. There is a model_update program that reads in streaming data and updates the tensorflow model every X seconds. This updated model is written to disk using tensorflow serving export. This dynamically updated tensorflow model is loaded by the tensorflow server. 

This program starts with a pretrained model stored at /tmp/auto_model/00000001 and updates the model based on the streamed data. /tmp/auto_model/00000002 is the first updated model generated by this program. It successfully generates version numbers 3, 4, 5, 6 before crashing at version number 7 with the following error.

Traceback (most recent call last):
  File "/home/prady/Documents/serving1/serving/bazel-bin/tensorflow_serving/example/model_retrainer.runfiles/tf_serving/tensorflow_serving/example/model_retrainer.py", line 151, in <module>
    r = Retrain()
  File "/home/prady/Documents/serving1/serving/bazel-bin/tensorflow_serving/example/model_retrainer.runfiles/tf_serving/tensorflow_serving/example/model_retrainer.py", line 48, in __init__
    self.main()
  File "/home/prady/Documents/serving1/serving/bazel-bin/tensorflow_serving/example/model_retrainer.runfiles/tf_serving/tensorflow_serving/example/model_retrainer.py", line 147, in main
    self.model_exporter.export(export_path, tf.constant(version_number), self.sess)
  File "/home/prady/Documents/serving1/serving/bazel-bin/tensorflow_serving/example/model_retrainer.runfiles/tf_serving/tensorflow_serving/session_bundle/exporter.py", line 256, in export
    meta_graph_suffix=constants.EXPORT_SUFFIX_NAME)
  File "/home/prady/Documents/serving1/serving/bazel-bin/tensorflow_serving/example/model_retrainer.runfiles/org_tensorflow/tensorflow/python/training/saver.py", line 1063, in save
    meta_graph_suffix=meta_graph_suffix)
  File "/home/prady/Documents/serving1/serving/bazel-bin/tensorflow_serving/example/model_retrainer.runfiles/org_tensorflow/tensorflow/python/training/saver.py", line 934, in _MaybeDeleteOldCheckpoints
    self._CheckpointFilename(p)):
  File "/home/prady/Documents/serving1/serving/bazel-bin/tensorflow_serving/example/model_retrainer.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 481, in get_matching_files
    return GetMatchingFiles(compat.as_bytes(filename), status)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/home/prady/Documents/serving1/serving/bazel-bin/tensorflow_serving/example/model_retrainer.runfiles/org_tensorflow/tensorflow/python/framework/errors.py", line 450, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors.NotFoundError: /tmp/auto_model/00000002-tmp

Let me know if you need any additional information.

**Comment by nfiedel** [comment]
Hi Sherry,
  Could you please take a look and give any guidance here?
  It looks like a possible race condition in MaybeDeleteOldCheckpoints in saver.py. 	
  
  @pradyumnanpk - do you know if any other process on your system may have deleted the older checkpoints?

  Thanks!

**Comment by pradyumnanpk** [comment]
@nfiedel I am pretty sure that no other processes deleted the older checkpoints. No matter, how many times you run it, the retrainer generates 5 new trained models successfully and crashes while exporting the 6th model.

**Comment by fangweili** [comment]
Before the fix, could you maybe workaround it with saver(max_to_keep=0).

**Comment by pradyumnanpk** [comment]
@fangweili - It worked with the workaround you suggested. Can you give me an insight on why it was crashing initially.

**Comment by fangweili** [comment]
The default value is 5. When you reach the 6th checkpoint, it will start to cleanup old ones. However, in model export case, old checkpoints may have been moved (to become part of export), and result in cleanup code not being able to find them.

Setting the value to 0 disables the cleanup.

This is an issue on our side, we will fix it.
