### ISSUE TITLE
Several tests are broken on ci.bazel.io

### ISSUE THREAD

**Issue by damienmg** [tensorflow/serving#139]
See http://ci.bazel.io/job/TensorFlow_Serving/BAZEL_VERSION=latest,PLATFORM_NAME=linux-x86_64/214/console

Happens with both Bazel @ HEAD and 0.3.0

Failing tests:
```
//tensorflow_serving/batching:batching_session_test                   NO STATUS
//tensorflow_serving/servables/tensorflow:session_bundle_factory_test NO STATUS
//tensorflow_serving/servables/tensorflow:session_bundle_source_adapter_test NO STATUS
//tensorflow_serving/session_bundle:session_bundle_py_test            NO STATUS
//tensorflow_serving/session_bundle:exporter_test                        FAILED in 3.6s
  /home/ci/.cache/bazel/_bazel_ci/3765d23dccdc53317a8257c675fcb26d/execroot/linux-x86_64/bazel-out/local-fastbuild/testlogs/tensorflow_serving/session_bundle/exporter_test/test.log
//tensorflow_serving/session_bundle:gc_test                              FAILED in 3.6s
  /home/ci/.cache/bazel/_bazel_ci/3765d23dccdc53317a8257c675fcb26d/execroot/linux-x86_64/bazel-out/local-fastbuild/testlogs/tensorflow_serving/session_bundle/gc_test/test.log
//tensorflow_serving/util:fast_read_dynamic_ptr_benchmark                FAILED in 16.5s
  /home/ci/.cache/bazel/_bazel_ci/3765d23dccdc53317a8257c675fcb26d/execroot/linux-x86_64/bazel-out/local-

```

And interesting part of the log:
```
ERROR: /home/ci/.cache/bazel/_bazel_ci/3765d23dccdc53317a8257c675fcb26d/external/org_tensorflow/tensorflow/contrib/session_bundle/example/BUILD:38:1: Executing genrule @org_tensorflow//tensorflow/contrib/session_bundle/example:half_plus_two failed: bash failed: error executing command 
  (cd /home/ci/.cache/bazel/_bazel_ci/3765d23dccdc53317a8257c675fcb26d/execroot/linux-x86_64 && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
  /bin/bash -c 'source external/bazel_tools/tools/genrule/genrule-setup.sh; rm -rf /tmp/half_plus_two; /usr/bin/python bazel-out/host/bin/external/org_tensorflow/tensorflow/contrib/session_bundle/example/export_half_plus_two; cp -r /tmp/half_plus_two/* bazel-out/local-fastbuild/genfiles/external/org_tensorflow/tensorflow/contrib/session_bundle/example/half_plus_two'): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Traceback (most recent call last):
  File "/home/ci/.cache/bazel/_bazel_ci/3765d23dccdc53317a8257c675fcb26d/execroot/linux-x86_64/bazel-out/host/bin/external/org_tensorflow/tensorflow/contrib/session_bundle/example/export_half_plus_two.runfiles/tf_serving/../org_tensorflow/tensorflow/contrib/session_bundle/example/export_half_plus_two.py", line 32, in <module>
    import tensorflow as tf
  File "/home/ci/.cache/bazel/_bazel_ci/3765d23dccdc53317a8257c675fcb26d/execroot/linux-x86_64/bazel-out/host/bin/external/org_tensorflow/tensorflow/contrib/session_bundle/example/export_half_plus_two.runfiles/org_tensorflow/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/home/ci/.cache/bazel/_bazel_ci/3765d23dccdc53317a8257c675fcb26d/execroot/linux-x86_64/bazel-out/host/bin/external/org_tensorflow/tensorflow/contrib/session_bundle/example/export_half_plus_two.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 97, in <module>
    from tensorflow.python.platform import test
  File "/home/ci/.cache/bazel/_bazel_ci/3765d23dccdc53317a8257c675fcb26d/execroot/linux-x86_64/bazel-out/host/bin/external/org_tensorflow/tensorflow/contrib/session_bundle/example/export_half_plus_two.runfiles/org_tensorflow/tensorflow/python/platform/test.py", line 77, in <module>
    import mock                # pylint: disable=g-import-not-at-top,unused-import
ImportError: No module named mock
FAIL: //tensorflow_serving/session_bundle:gc_test (see /home/ci/.cache/bazel/_bazel_ci/3765d23dccdc53317a8257c675fcb26d/execroot/linux-x86_64/bazel-out/local-fastbuild/testlogs/tensorflow_serving/session_bundle/gc_test/test.log)
FAIL: //tensorflow_serving/session_bundle:exporter_test (see /home/ci/.cache/bazel/_bazel_ci/3765d23dccdc53317a8257c675fcb26d/execroot/linux-x86_64/bazel-out/local-fastbuild/testlogs/tensorflow_serving/session_bundle/exporter_test/test.log)
FAIL: //tensorflow_serving/util:fast_read_dynamic_ptr_benchmark (see /home/ci/.cache/bazel/_bazel_ci/3765d23dccdc53317a8257c675fcb26d/execroot/linux-x86_64/bazel-out/local-fastbuild/testlogs/tensorflow_serving/util/fast_read_dynamic_ptr_benchmark/test.log)
```

/cc @kirilg

**Comment by damienmg** [comment]
FYI the list of possible culprits: http://ci.bazel.io/job/TensorFlow_Serving/214/changes

**Comment by kirilg** [comment]
I believe the culprit is syncing to the latest Tensorflow the last time we pushed to GitHub (necessary for us, but TF introduced a new dependency on mock on July 13).

Tensorflow now added the line `pip install mock` to their PIP install instructions. See latest change in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/install/install_pip_packages.sh. Could you add that to your Jenkins config as well and check if that works?

**Comment by damienmg** [comment]
Ok I am updating our install, that's kind of sad that bazel does have a way to track dependencies and we still needs to modify the install of our slaves once in a while.

**Comment by lberki** [comment]
Well, this is because Bazel doesn't have a way to say "I need this dependency on the host system, but not during the build". We should, but it's not trivial how it should look like.

**Comment by kirilg** [comment]
I see your continuous build is back to green, so I'll close this issue. Thanks again for testing TensorFlow Serving with the latest Bazel, we really appreciate it.

**Comment by damienmg** [comment]
Oh sorry I though that committing the change would have close the issue, yes it is fixed :)
