### ISSUE TITLE
"You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,?,?,3]

### ISSUE THREAD

**Issue by HoangTienDuc** [tensorflow/serving#1532]
input image has shape:
```
image.shape:  (512, 512, 3) 
```
i feed input image into tf-serving
```
inputs = np.expand_dims(image, axis=0) -->  inputs.shape:  (1, 512, 512, 3), dtype inputs:  float32
```
but i don't know why i got error below:
```
Traceback (most recent call last):
  File "client.py", line 86, in <module>
    run(args.host, args.port, args.image_path, args.model, args.signature_name)
  File "client.py", line 72, in run
    boxes = tf.make_ndarray(prediction_outputs.result().outputs['output'])
  File "/home/tienduchoang/miniconda3/lib/python3.7/site-packages/grpc/_channel.py", line 303, in result
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
        status = StatusCode.INVALID_ARGUMENT
        details = "You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,?,?,3]
         [[{{node input_1}}]]"
        debug_error_string = "{"created":"@1578992659.969599135","description":"Error received from peer ipv6:[::1]:8500","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,?,?,3]\n\t [[{{node input_1}}]]","grpc_status":3}"
>
```

**Comment by gowthamkpr** [comment]
@HoangTienDuc This is definitely not a serving issue. But can you please provide a simple reproducible code to reproducible code or a code snippet of your model and version of Tensorflow you are using. Thanks!

**Comment by HoangTienDuc** [comment]
- My tensorflow version:
```
tensorflow             1.14.0     
tensorflow-estimator   1.14.0     
tensorflow-serving-api 1.14.0
```
- My model configuration:
```
MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:

signature_def['prediction']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['input'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, -1, 3)
        name: strided_slice_2:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['output'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, -1)
        name: strided_slice_3:0
  Method name is: tensorflow/serving/predict
```
- My client reproducible code:
```
#  read image
image = cv2.imread(image_path)
#  preprocess image and resize image into shape(512,512, 3)
#  create input to feed into tf-serving:
inputs = np.expand_dims(image, axis=0)
#  and get result:
request = predict_pb2.PredictRequest()
 request.model_spec.name = model
 request.model_spec.signature_name = signature_name
 request.inputs['input'].CopyFrom(make_tensor_proto(inputs))

# result = stub.Predict(request, None)
prediction_outputs = stub.Predict.future(request, None)

 boxes = tf.make_ndarray(prediction_outputs.result().outputs['output'])
```

**Comment by gowthamkpr** [comment]
@HoangTienDuc 
Your input shape as shown here in the signature def is 
```
 inputs['input'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, -1, 3)
```
not matching the shape of the input that you are feeding into the model which is `(1, 512, 512, 3)`. So this is the cause of the error.

Try not to expand the dimension i.e., comment this line out `inputs = np.expand_dims(image, axis=0)`

**Comment by HoangTienDuc** [comment]
I already commented that line, but the error still the same.
```
Traceback (most recent call last):
  File "client.py", line 88, in <module>
    run(args.host, args.port, args.image_path, args.model, args.signature_name)
  File "client.py", line 74, in run
    boxes = tf.make_ndarray(prediction_outputs.result().outputs['output'])
  File "/home/tienduchoang/miniconda3/lib/python3.7/site-packages/grpc/_channel.py", line 303, in result
    raise self
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
        status = StatusCode.INVALID_ARGUMENT
        details = "You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,?,?,3]
         [[{{node input_1}}]]"
        debug_error_string = "{"created":"@1579249496.420776299","description":"Error received from peer ipv6:[::1]:8500","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"You must feed a value for placeholder tensor 'input_1' with dtype float and shape [?,?,?,3]\n\t [[{{node input_1}}]]","grpc_status":3}"
>
```

**Comment by gowthamkpr** [comment]
Can you post the entore samed_model_cli output, I mean the the signature of serving default?

**Comment by gowthamkpr** [comment]
@HoangTienDuc I am not exactly sure where you are running into an error. Please go through this [colab](https://colab.research.google.com/gist/gowthamkpr/b17e6e8fc89886acc2cb129f2b35791f/final_flowers_serving.ipynb) which will help you debug the error yourself.

**Comment by gowthamkpr** [comment]
Closing this issue as it has been inactive for more than 3 weeks. Please add additional comments and we can open the issue again. Thanks!

**Comment by DmitriyBaykov** [comment]
Hi, @gowthamkpr. Seems like I'm facing a similar issue on TF=2.1, tensorflow-transform=0.21, tensorflow serving - latest image from Docker. [Here's a reference to my SO question](https://stackoverflow.com/questions/59880686/serving-tf-model-with-variable-length-input). Could you give me a hand with this? I need to have variable inputs on my model's serving.
