### ISSUE TITLE
Connection timeout error 110

### ISSUE THREAD

**Issue by Adblu** [tensorflow/serving#1665]
Starting server:
```
docker run -p 8501:8501 --mount type=bind,source=/home/wnnuser/car/serving/a/model,target=/models/a -e MODEL_NAME=a --gpus device=1 -t tensorflow/serving:2.0.0-gpu
```

Example inference code:
```
URL = 'http://34.34.343.234:8501/v1/models/a:predict'

image = '/home/n/Documents/cars_mask_rcnn/dataset/val/a.jpg'

headers = {"content-type": "application/json"}

image_content = cv2.imread(image, 1 ).astype('uint8').tolist()

body = {"instances": [{"inputs": image_content}]}

r = requests.post(URL, data=json.dumps(body), headers = headers)
print(r.text)
```

And getting:

```
Traceback (most recent call last):
  File "/home/n/.conda/envs/cars/lib/python3.6/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/n/.conda/envs/cars/lib/python3.6/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/home/n/.conda/envs/cars/lib/python3.6/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/n/.conda/envs/cars/lib/python3.6/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/home/n/.conda/envs/cars/lib/python3.6/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/n/.conda/envs/cars/lib/python3.6/http/client.py", line 1262, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/n/.conda/envs/cars/lib/python3.6/http/client.py", line 1308, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/n/.conda/envs/cars/lib/python3.6/http/client.py", line 1257, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/n/.conda/envs/cars/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/home/n/.conda/envs/cars/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/home/n/.conda/envs/cars/lib/python3.6/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/home/n/.conda/envs/cars/lib/python3.6/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f7ce9b71978>: Failed to establish a new connection: [Errno 110] Connection timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/n/.conda/envs/cars/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/n/.conda/envs/cars/lib/python3.6/site-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/n/.conda/envs/cars/lib/python3.6/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='63.35.219.128', port=8501): Max retries exceeded with url: /v1/models/a:predict (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7ce9b71978>: Failed to establish a new connection: [Errno 110] Connection timed out',))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/n/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-3a3012119f84>", line 1, in <module>
    r = requests.post(URL, data=json.dumps(body), headers = headers)
  File "/home/n/.conda/envs/cars/lib/python3.6/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/n/.conda/envs/cars/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/n/.conda/envs/cars/lib/python3.6/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/n/.conda/envs/cars/lib/python3.6/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/home/n/.conda/envs/cars/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='23.23.234.128', port=8501): Max retries exceeded with url: /v1/models/a:predict (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7ce9b71978>: Failed to establish a new connection: [Errno 110] Connection timed out',))

```

Do you have any clue ?

**Comment by gowthamkpr** [comment]
@Adblu Were you able to solve this issue?

**Comment by Adblu** [comment]
@gowthamkpr  Its local network, because I am doing ssh tunneling of the port, but anyway, yes, solved.
