### ISSUE TITLE
Tensorflow Serving - How can I create my own signatures for my model?

### ISSUE THREAD

**Issue by gabriel-fsa** [tensorflow/serving#1793]
The code:
```
import tensorflow as tf
import os
import tempfile

if tf.executing_eagerly():
       tf.compat.v1.disable_eager_execution()


model = tf.keras.models.load_model('model_trained')


tensor_info_input = tf.compat.v1.saved_model.utils.build_tensor_info(model.get_layer(name="image").input)

tensor_info_output = tf.compat.v1.saved_model.utils.build_tensor_info(model.get_layer(name="dense2").output)


signature = tf.compat.v1.saved_model.signature_def_utils.build_signature_def(
                    inputs={'input': tensor_info_input},
                                outputs={'output': tensor_info_output},
                                            method_name=tf.compat.v1.saved_model.signature_constants.PREDICT_METHOD_NAME)


export_path = '/root/model/2'


print('export_path = {}\n'.format(export_path))

tf.keras.models.save_model(
            model,
                export_path,
                    overwrite=True,
                        include_optimizer=True,
                            save_format=None,
                                signatures=signature,
                                    options=None
                                    )

print('\nSaved model:')
```

The output and error:

`Traceback (most recent call last):
  File "transform_model.py", line 28, in <module>
    tf.keras.models.save_model(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/saving/save.py", line 133, in save_model
    saved_model_save.save(model, filepath, overwrite, include_optimizer,
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/keras/saving/saved_model/save.py", line 80, in save
    save_lib.save(model, filepath, signatures, options)
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/save.py", line 975, in save
    _, exported_graph, object_saver, asset_info = _build_meta_graph(
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/save.py", line 1050, in _build_meta_graph
    signature_serialization.canonicalize_signatures(signatures))
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/signature_serialization.py", line 109, in canonicalize_signatures
    raise ValueError(
ValueError: Expected a TensorFlow function to generate a signature for, but got inputs {
  key: "input"
  value {
    name: "image:0"
    dtype: DT_FLOAT
    tensor_shape {
      dim {
        size: -1
      }
      dim {
        size: 200
      }
      dim {
        size: 50
      }
      dim {
        size: 1
      }
    }
  }
}
outputs {
  key: "output"
  value {
    name: "dense2/truediv:0"
    dtype: DT_FLOAT
    tensor_shape {
      dim {
        size: -1
      }
      dim {
        size: 50
      }
      dim {
        size: 37
      }
    }
  }
}
method_name: "tensorflow/serving/predict"
. Only `tf.functions` with an input signature or concrete functions can be used as a signature.`

**Comment by rmothukuru** [comment]
@gabriel-fsa,
While trying to reproduce your error, I encountered another error, 

**`OSError: SavedModel file does not exist at: model_trained/{saved_model.pbtxt|saved_model.pb}`**

Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/c41e3c1db6efea5f95efcb9a03e48a12/gh_1793.ipynb). 

Can you please share the complete reproducible code so that we can look into it. Thanks!

**Comment by gabriel-fsa** [comment]
> @gabriel-fsa,
> While trying to reproduce your error, I encountered another error,
> 
> **`OSError: SavedModel file does not exist at: model_trained/{saved_model.pbtxt|saved_model.pb}`**
> 
> Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/c41e3c1db6efea5f95efcb9a03e48a12/gh_1793.ipynb).
> 
> Can you please share the complete reproducible code so that we can look into it. Thanks!

It's because u don't have the model. Downloaded [here](https://drive.google.com/drive/folders/1sK4S-eQvfla5H-luVyRyshDLuSKK77QQ?usp=sharing).

**Comment by arghyaganguly** [comment]
@gabriel-fsa, could you please retry once by wrapping the signature into a concrete function and check :- 
eg :- 

@tf.function(signature = tf.compat.v1.saved_model.signature_def_utils.build_signature_def(
                    inputs={'input': tensor_info_input},
                                outputs={'output': tensor_info_output},
                                            method_name=tf.compat.v1.saved_model.signature_constants.PREDICT_METHOD_NAME))

**Comment by pindinagesh** [comment]
Hi @gabriel-fsa 

Have you got a chance to work on above @arghyaganguly's comment?

**Comment by pindinagesh** [comment]
Hi @gabriel-fsa 

Could you please have a look at this similar [issue](https://stackoverflow.com/questions/60560719/tensorflow-serving-export-signature-without-arguments) which has been discussed and closing this issue due to inactivity. Please feel free to reopen if this still exist. Thanks!
