### ISSUE TITLE
Resnet example client does not work with JPEG images

### ISSUE THREAD

**Issue by joancafom** [tensorflow/serving#1947]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: official docker image (Linux Ubuntu 16.04)
- **TensorFlow Serving installed from (source or binary)**: official docker image
- **TensorFlow Serving version**: `2.7.0`

### Describe the problem
Hi! From version `2.7.0`, the [example client found in the repo](https://github.com/tensorflow/serving/blob/2.7.0/tensorflow_serving/example/resnet_client_grpc.py) does not seem to properly handle images as input:

```
$ python resnet_client_grpc.py
...
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "input tensor alias not found in signature: input_1. Inputs expected to be in the set {image_bytes}."
	debug_error_string = "{"created":"@1638878577.643963469","description":"Error received from peer ipv4:172.20.0.2:8500","file":"src/core/lib/surface/call.cc","file_line":1063,"grpc_message":"input tensor alias not found in signature: input_1. Inputs expected to be in the set {image_bytes}.","grpc_status":3}"
```

Notice that this does not happen in version `2.6.1` I'm using an official TensorFlow ResNet SavedModel.

### Exact Steps to Reproduce

1. Download the [ResNet SavedModel](https://www.tensorflow.org/tfx/serving/serving_kubernetes?hl=sl#download_the_resnet_savedmodel)

```
$ rm -rf /tmp/resnet
$ mkdir /tmp/resnet
$ curl -s http://download.tensorflow.org/models/official/20181001_resnet/savedmodels/resnet_v2_fp32_savedmodel_NHWC_jpg.tar.gz | tar --strip-components=2 -C /tmp/resnet -xvz
```

2. Create a docker-compose file that runs two containers, one for the official `tensorflow-serving` image and another with python (will be used to query the server):

```yaml
version: "2"
services:
  tensorflow-serving:
    image: docker.io/tensorflow/serving
    ports:
      - 8500:8500
      - 8501:8501
    environment:
      - MODEL_NAME=resnet
    volumes:
      - "/tmp/resnet:/models/resnet"
  tensorflow-resnet-client:
    image: docker.io/bitnami/python:3
    depends_on:
      - tensorflow-serving
    entrypoint: ['tail', '-f', '/dev/null']
volumes:
  tensorflow_serving_data:
    driver: local
```

3. Run the containers and connect to the client one to execute the python script:

```
$ docker-compose up
$ docker exec -it tensorflow-resnet-client_1 bash
root@9c067b6717f6:/app# python -m pip install --upgrade pip
root@9c067b6717f6:/app# curl -JLO https://raw.githubusercontent.com/tensorflow/serving/2.7.0/tensorflow_serving/example/resnet_client_grpc.py
root@9c067b6717f6:/app# sed -i 's/localhost:/tensorflow-serving_1:/g' resnet_client_grpc.py
root@9c067b6717f6:/app# pip install tensorflow-serving-api Pillow grpcio
root@9c067b6717f6:/app# python resnet_client_grpc.py
...
Traceback (most recent call last):
  File "resnet_client_grpc.py", line 80, in <module>
    tf.compat.v1.app.run()
  File "/opt/bitnami/python/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/opt/bitnami/python/lib/python3.7/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/opt/bitnami/python/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "resnet_client_grpc.py", line 74, in main
    result = stub.Predict(request, 10.0)  # 10 secs timeout
  File "/opt/bitnami/python/lib/python3.7/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/opt/bitnami/python/lib/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "input tensor alias not found in signature: input_1. Inputs expected to be in the set {image_bytes}."
	debug_error_string = "{"created":"@1638878577.643963469","description":"Error received from peer ipv4:172.20.0.2:8500","file":"src/core/lib/surface/call.cc","file_line":1063,"grpc_message":"input tensor alias not found in signature: input_1. Inputs expected to be in the set {image_bytes}.","grpc_status":3}"
```

It does not matter whether the property `MODEL_ACCEPT_JPG` is set to `True`, the error is the same:

```
root@9c067b6717f6:/app# sed -i 's/MODEL_ACCEPT_JPG = False/MODEL_ACCEPT_JPG = True/g' resnet_client_grpc.py
root@9c067b6717f6:/app# python resnet_client_grpc.py
...
Traceback (most recent call last):
  File "resnet_client_grpc.py", line 80, in <module>
    tf.compat.v1.app.run()
  File "/opt/bitnami/python/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/opt/bitnami/python/lib/python3.7/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/opt/bitnami/python/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "resnet_client_grpc.py", line 74, in main
    result = stub.Predict(request, 10.0)  # 10 secs timeout
  File "/opt/bitnami/python/lib/python3.7/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/opt/bitnami/python/lib/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "input tensor alias not found in signature: input_1. Inputs expected to be in the set {image_bytes}."
	debug_error_string = "{"created":"@1638878886.899172004","description":"Error received from peer ipv4:172.20.0.2:8500","file":"src/core/lib/surface/call.cc","file_line":1063,"grpc_message":"input tensor alias not found in signature: input_1. Inputs expected to be in the set {image_bytes}.","grpc_status":3}"
>
```

As shown, the error received is `INVALID_ARGUMENT`.

**Comment by sanatmpa1** [comment]
@joancafom,

Can you take a look at this[ SO thread](https://stackoverflow.com/questions/43849407/how-to-debug-invalid-argument-input-tensor-alias-not-found-in-signature) about a similar `INVALID_ARGUMENT` error and let us know if it helps? Thanks!

**Comment by joancafom** [comment]
Hi!

Performing equivalent changes in the python script does result in the same error:

```diff
  # See prediction_service.proto for gRPC request/response details.
  request = predict_pb2.PredictRequest()
  request.model_spec.name = 'resnet'
  request.model_spec.signature_name = 'serving_default'
- request.inputs['input_1'].CopyFrom(
+ request.inputs['inputs'].CopyFrom(
      tf.make_tensor_proto(data))
```

```
root@3da902550555:/app# python resnet_client_grpc.py
...
  File "/opt/bitnami/python/lib/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "input tensor alias not found in signature: inputs. Inputs expected to be in the set {image_bytes}."
	debug_error_string = "{"created":"@1639481334.993491744","description":"Error received from peer ipv4:172.29.0.2:8500","file":"src/core/lib/surface/call.cc","file_line":1063,"grpc_message":"input tensor alias not found in signature: inputs. Inputs expected to be in the set {image_bytes}.","grpc_status":3}"
```

**Comment by joancafom** [comment]
Any updates or suggestions on this?

**Comment by guanxinq** [comment]
Could you please try to replace request.inputs['inputs'].CopyFrom() with request.inputs['image_bytes'].CopyFrom().

**Comment by windmaple** [comment]
The Resnet model here is out of date. Please use the latest Resnet model from TFHub instead: https://tfhub.dev/tensorflow/resnet_50/classification/1

**Comment by joancafom** [comment]
> Could you please try to replace request.inputs['inputs'].CopyFrom() with request.inputs['image_bytes'].CopyFrom().

I have tried to perform the suggested changes, but still no luck:

```diff
  # See prediction_service.proto for gRPC request/response details.
  request = predict_pb2.PredictRequest()
  request.model_spec.name = 'resnet'
  request.model_spec.signature_name = 'serving_default'
- request.inputs['inputs'].CopyFrom(
+ request.inputs['image_bytes'].CopyFrom(
      tf.make_tensor_proto(data))
```

```
root@b2a7896eac99:/app# python resnet_client_grpc.py
...
  File "/opt/bitnami/python/lib/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "Expects arg[0] to be string but float is provided"
	debug_error_string = "{"created":"@1640603098.629696162","description":"Error received from peer ipv4:192.168.64.2:8500","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"Expects arg[0] to be string but float is provided","grpc_status":3}"
```

Additionally, setting `MODEL_ACCEPT_JPG` to `True` does result in a different error message:

```
root@b2a7896eac99:/app# python resnet_client_grpc.py
...
  File "/opt/bitnami/python/lib/python3.7/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "slice index 0 of dimension 0 out of bounds.
	 [[{{node map/TensorArrayUnstack/strided_slice}}]]"
	debug_error_string = "{"created":"@1640603128.980763151","description":"Error received from peer ipv4:192.168.64.2:8500","file":"src/core/lib/surface/call.cc","file_line":1074,"grpc_message":"slice index 0 of dimension 0 out of bounds.\n\t [[{{node map/TensorArrayUnstack/strided_slice}}]]","grpc_status":3}"
```

> The Resnet model here is out of date. Please use the latest Resnet model from TFHub instead:

Using this model instead seems to work and now I can get the expected prediction 🙂 . Nevertheless, this model has been working fine with the example client up to version `2.6.1`. Is it something expected for this new version to drop support for older models?

**Comment by guanxinq** [comment]
That does not mean TF Serving or TF drop the support for older models. It seems the newer model uses a different signature name and resnet_client_grpc.py was updated for the new signature name in https://github.com/tensorflow/serving/commit/bb1428d53abb53fe938ddf9bb8839d4dfe48d291. 

You could modify resnet_client_grpc.py to make it work with the older model(i.e. revert above commit)

**Comment by joancafom** [comment]
Okay, thanks for the help!
