### ISSUE TITLE
Model export fails: Serving Inception (inception-v3)

### ISSUE THREAD

**Issue by wakahiu** [tensorflow/serving#195]
I'm following the instruction on "[Serving Inception Model with TensorFlow Serving and Kubernetes](https://tensorflow.github.io/serving/serving_inception)" and experiencing the following error when trying to export the model.
```
$ bazel-bin/tensorflow_serving/example/inception_export --checkpoint_dir=~/trained_models/inception-v3-2016-03-01
Traceback (most recent call last):
  File "/root/behold-ai-serving/bazel-bin/tensorflow_serving/REST_server/inception_export.runfiles/tf_serving/tensorflow_serving/REST_server/inception_export.py", line 27, in <module>
    import tensorflow as tf
  File "/root/behold-ai-serving/bazel-bin/tensorflow_serving/REST_server/inception_export.runfiles/org_tensorflow/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/root/behold-ai-serving/bazel-bin/tensorflow_serving/REST_server/inception_export.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/root/behold-ai-serving/bazel-bin/tensorflow_serving/REST_server/inception_export.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/root/behold-ai-serving/bazel-bin/tensorflow_serving/REST_server/inception_export.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: /root/behold-ai-serving/bazel-bin/tensorflow_serving/REST_server/inception_export.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow.so: undefined symbol: PyModule_Create2
```

I'm running **python3** in a virtualenv.  Its it possible to have the example running in Python3 without an enormous amount of code refactoring?

**Comment by wakahiu** [comment]
I didn't have much running the server in virtual env. I solved the issue by installing pip packages globally, and using python 2.7.
