### ISSUE TITLE
An error occurred during the fetch of repository 'local_config_tensorrt'

### ISSUE THREAD

**Issue by 520jefferson** [tensorflow/serving#1965]
Hi , i meet   this error, when i compile the tf serving with cuda 11.1 and tensorrt 8.2.2.1 / 7.2.2
The log errors as follows:

/FT/.cache/_bazel_root/2146c6edcc05d261008f841f79bab606/external/org_tensorflow/third_party/tensorrt/tensorrt_configure.bzl:243:37: in <toplevel>
**### ERROR: An error occurred during the fetch of repository 'local_config_tensorrt':**
   Traceback (most recent call last):
	File "/FT/.cache/_bazel_root/2146c6edcc05d261008f841f79bab606/external/org_tensorflow/third_party/tensorrt/tensorrt_configure.bzl", line 225, column 38, in _tensorrt_configure_impl
		_create_local_tensorrt_repository(repository_ctx)
	File "/FT/.cache/_bazel_root/2146c6edcc05d261008f841f79bab606/external/org_tensorflow/third_party/tensorrt/tensorrt_configure.bzl", line 112, column 30, in _create_local_tensorrt_repository
		config = find_cuda_config(repository_ctx, find_cuda_config_path, ["tensorrt"])
	File "/FT/.cache/_bazel_root/2146c6edcc05d261008f841f79bab606/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 643, column 41, in find_cuda_config
		exec_result = _exec_find_cuda_config(repository_ctx, script_path, cuda_libraries)
	File "/FT/.cache/_bazel_root/2146c6edcc05d261008f841f79bab606/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 637, column 19, in _exec_find_cuda_config
		return execute(repository_ctx, [python_bin, "-c", decompress_and_execute_cmd])
	File "/FT/.cache/_bazel_root/2146c6edcc05d261008f841f79bab606/external/org_tensorflow/third_party/remote_config/common.bzl", line 219, column 13, in execute
		fail(
Error in fail: Repository command failed
Could not find any NvInferVersion.h matching version '' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
of:
        '/FT/tools/TensorRT-8.2.2.1/targets/x86_64-linux-gnu/lib'
ERROR: /FT/tensorflow-serving/WORKSPACE:40:10: fetching tensorrt_configure rule //external:local_config_tensorrt: Traceback (most recent call last):
	File "/FT/.cache/_bazel_root/2146c6edcc05d261008f841f79bab606/external/org_tensorflow/third_party/tensorrt/tensorrt_configure.bzl", line 225, column 38, in _tensorrt_configure_impl
		_create_local_tensorrt_repository(repository_ctx)
	File "/FT/.cache/_bazel_root/2146c6edcc05d261008f841f79bab606/external/org_tensorflow/third_party/tensorrt/tensorrt_configure.bzl", line 112, column 30, in _create_local_tensorrt_repository
		config = find_cuda_config(repository_ctx, find_cuda_config_path, ["tensorrt"])
	File "/FT/.cache/_bazel_root/2146c6edcc05d261008f841f79bab606/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 643, column 41, in find_cuda_config
		exec_result = _exec_find_cuda_config(repository_ctx, script_path, cuda_libraries)
	File "/FT/.cache/_bazel_root/2146c6edcc05d261008f841f79bab606/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 637, column 19, in _exec_find_cuda_config
		return execute(repository_ctx, [python_bin, "-c", decompress_and_execute_cmd])
	File "/FT/.cache/_bazel_root/2146c6edcc05d261008f841f79bab606/external/org_tensorflow/third_party/remote_config/common.bzl", line 219, column 13, in execute
		fail(
Error in fail: Repository command failed
****Could not find any NvInferVersion.h matching version '' in any subdirectory:****
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
of:
        '/FT/tools/TensorRT-8.2.2.1/targets/x86_64-linux-gnu/lib'
ERROR: no such package '@local_config_tensorrt//': Repository command failed
Could not find any NvInferVersion.h matching version '' in any subdirectory:
        ''
        'include'
        'include/cuda'
        'include/*-linux-gnu'
        'extras/CUPTI/include'
        'include/cuda/CUPTI'
of:
        '/FT/tools/TensorRT-8.2.2.1/targets/x86_64-linux-gnu/lib'
INFO: Elapsed time: 1.293s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
./compile_serving.sh: line 46:  : command not found
./compile_serving.sh: line 47: --verbose_failures: command not found
./compile_serving.sh: line 48: --output_filter=DONT_MATCH_ANYTHING: command not found
./compile_serving.sh: line 49: --config=nativeopt: command not found
./compile_serving.sh: line 50: tensorflow_serving/tools/pip_package:build_pip_package: No such file or directory
./compile_serving.sh: line 51: bazel-bin/tensorflow_serving/tools/pip_package/build_pip_package: No such file or directory
./compile_serving.sh: line 52: /tmp/pip: No such file or directory
ERROR: Invalid requirement: ''
./compile_serving.sh: line 54: /tmp/pip/tensorflow_serving_api_gpu-*.whl: No such file or directory
$TEST_TMPDIR defined: output root default is '/FT/tensorflow-serving/../.cache' and max_idle_secs default is '15'.
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
$TEST_TMPDIR defined: output root default is '/FT/tensorflow-serving/../.cache' and max_idle_secs default is '15'.
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.

**Comment by sanatmpa1** [comment]
@520jefferson,

Can you take a look at [this workaround](https://github.com/tensorflow/tensorflow/issues/33207#issuecomment-550586632) proposed in a [similar issue](https://github.com/tensorflow/tensorflow/issues/33207) and let us know if it helps? Thanks!

**Comment by 520jefferson** [comment]
@sanatmpa1 
it sames i set the wrong ENV TENSORRT_INSTALL_PATH
![image](https://user-images.githubusercontent.com/5691554/150308038-af65ae6a-7aef-4010-9039-1c56bbbf8265.png)
