### ISSUE TITLE
no such target '@org_tensorflow//third_party/gpus/crosstool:crosstool'

### ISSUE THREAD

**Issue by yejw5** [tensorflow/serving#225]
When I build an example code with command like `bazel build -c opt --config=cuda //tensorflow_serving/example:inception_export`, the following error appears:

```
ERROR: no such target '@org_tensorflow//third_party/gpus/crosstool:crosstool': target 'crosstool' not declared in package 'third_party/gpus/crosstool' defined by /root/.cache/bazel/_bazel_root/32464d5fc391eed53e38176f08f351a1/external/org_tensorflow/third_party/gpus/crosstool/BUILD.
```

With Cuda8.0 and Cudnn5.1.5.

**Comment by llhe** [comment]
Looks like the build is broken by this change:
https://github.com/tensorflow/tensorflow/commit/58b37cf745c6c30d44878ddf5987c4283ed12c3c

**Comment by llhe** [comment]
@davidzchen Could you have a look on this?

**Comment by davidzchen** [comment]
I am working on a fix for this.

**Comment by gangadhar-p** [comment]
I have the same issue. Is there a workaround to continue with the build?

**Comment by gangadhar-p** [comment]
I was able to work around this by following the suggestion on the thread https://github.com/tensorflow/serving/issues/186

> 1. the crosstool in tools/bazel.rc is invalid (AFAIK). change @org_tensorflow//third_party/gpus/crosstool to @local_config_cuda//crosstool:toolchain.
> 
> 2. the cuda_configure repository rule will fail (haven't looked in to why exactly), but essentially an bazel clean --expunge && export TF_NEED_CUDA=1 will fix this.

**Comment by tvkpz** [comment]
hi

I still cannot build successfully. In response to 

$ bazel build -c opt --config=cuda tensorflow_serving/...

I get the following error

/serving# bazel build -c opt --config=cuda tensorflow_serving/...
INFO: Reading 'startup' options from /root/.bazelrc: --batch
INFO: Found 186 targets...
ERROR: /root/.cache/bazel/_bazel_root/f8d1071c69ea316497c31e40fe01608c/external/org_tensorflow/tensorflow/contrib/session_bundle/example/BUILD:38:1: Executing genrule @org_tensorflow//tensorflow/contrib/session_bundle/example:half_plus_two failed: bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
I external/org_tensorflow/tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I external/org_tensorflow/tensorflow/stream_executor/dso_loader.cc:119] Couldn't open CUDA library libcudnn.so. LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64:
I external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc:3459] Unable to load cuDNN DSO
I external/org_tensorflow/tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I external/org_tensorflow/tensorflow/stream_executor/dso_loader.cc:119] Couldn't open CUDA library libcuda.so.1. LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64:
I external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: 9f639740fce0
I external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: Not found: was unable to find libcuda.so DSO loaded into this program
I external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_diagnostics.cc:363] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  367.55  Tue Sep 27 10:17:05 PDT 2016
GCC version:  gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) 
"""
I external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: 367.55.0
I external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1091] LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64:
I external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1092] failed to find libcuda.so on this system: Failed precondition: could not dlopen DSO: libcuda.so.1; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
I external/org_tensorflow/tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/f8d1071c69ea316497c31e40fe01608c/execroot/serving/bazel-out/host/bin/external/org_tensorflow/tensorflow/contrib/session_bundle/example/export_half_plus_two.runfiles/tf_serving/../org_tensorflow/tensorflow/contrib/session_bundle/example/export_half_plus_two.py", line 32, in <module>
    import tensorflow as tf
  File "/root/.cache/bazel/_bazel_root/f8d1071c69ea316497c31e40fe01608c/execroot/serving/bazel-out/host/bin/external/org_tensorflow/tensorflow/contrib/session_bundle/example/export_half_plus_two.runfiles/org_tensorflow/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/root/.cache/bazel/_bazel_root/f8d1071c69ea316497c31e40fe01608c/execroot/serving/bazel-out/host/bin/external/org_tensorflow/tensorflow/contrib/session_bundle/example/export_half_plus_two.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 106, in <module>
    from tensorflow.python.platform import test
  File "/root/.cache/bazel/_bazel_root/f8d1071c69ea316497c31e40fe01608c/execroot/serving/bazel-out/host/bin/external/org_tensorflow/tensorflow/contrib/session_bundle/example/export_half_plus_two.runfiles/org_tensorflow/tensorflow/python/platform/test.py", line 67, in <module>
    from tensorflow.python.framework import test_util as _test_util
  File "/root/.cache/bazel/_bazel_root/f8d1071c69ea316497c31e40fe01608c/execroot/serving/bazel-out/host/bin/external/org_tensorflow/tensorflow/contrib/session_bundle/example/export_half_plus_two.runfiles/org_tensorflow/tensorflow/python/framework/test_util.py", line 43, in <module>
    from tensorflow.python.platform import googletest
  File "/root/.cache/bazel/_bazel_root/f8d1071c69ea316497c31e40fe01608c/execroot/serving/bazel-out/host/bin/external/org_tensorflow/tensorflow/contrib/session_bundle/example/export_half_plus_two.runfiles/org_tensorflow/tensorflow/python/platform/googletest.py", line 32, in <module>
    from tensorflow.python.platform import benchmark  # pylint: disable=unused-import
  File "/root/.cache/bazel/_bazel_root/f8d1071c69ea316497c31e40fe01608c/execroot/serving/bazel-out/host/bin/external/org_tensorflow/tensorflow/contrib/session_bundle/example/export_half_plus_two.runfiles/org_tensorflow/tensorflow/python/platform/benchmark.py", line 119, in <module>
    class Benchmark(six.with_metaclass(_BenchmarkRegistrar, object)):
  File "/usr/lib/python2.7/dist-packages/six.py", line 617, in with_metaclass
    return meta("NewBase", bases, {})
  File "/root/.cache/bazel/_bazel_root/f8d1071c69ea316497c31e40fe01608c/execroot/serving/bazel-out/host/bin/external/org_tensorflow/tensorflow/contrib/session_bundle/example/export_half_plus_two.runfiles/org_tensorflow/tensorflow/python/platform/benchmark.py", line 114, in __new__
    if not newclass.is_abstract():
AttributeError: type object 'NewBase' has no attribute 'is_abstract'
INFO: Elapsed time: 79.494s, Critical Path: 33.68s

Anybody face the same problem.

**Comment by tobegit3hub** [comment]
It seems that updating the `bazel.rc` file could fix it. Could you like to accept this? @davidzchen

**Comment by gautamvasudevan** [comment]
Closing - please see the latest [Docker examples](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/docker.md) for bringing up a build environment.

**Comment by xinxilwl** [comment]
> Closing - please see the latest [Docker examples](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/docker.md) for bringing up a build environment.

hi, the link you put isn't what we want, we need to build a new image for AVX optimization. Because it can contribute to performance.
