### ISSUE TITLE
"ImportError: cannot import name manifest_pb2" when importing exporter

### ISSUE THREAD

**Issue by xtr33me** [tensorflow/serving#254]
I'm new to tensorflow_serving and in trying to learn tensorflow as a whole, I am also trying to figure out how to export the "textsum" model for serving. I put the below code in a file and was going to try to figure out how to build on it, however it is erroring at a pretty early point with the error in the title.  Anyone have any ideas as to why I may be seeing this?  I have the latest tensorflow_serving code and was successfully able to install, configure and run the test listed in the readme. 

When I set a breakpoint at the "from tensorflow.contrib.session_bundle import exporter" line and looked at tensorflow.contrib.session_bundle, there is no "exporter". The only child to session_bundle is "gc".

Error I receive is: 

> I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
> I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
> I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
> I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so locally
> I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
> Traceback (most recent call last):
>   File "textsum/export_textsum.py", line 10, in <module>
>     from tensorflow.contrib.session_bundle import exporter
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/session_bundle/exporter.py", line 32, in <module>
>     from tensorflow.contrib.session_bundle import manifest_pb2
> ImportError: cannot import name manifest_pb2

Small bit of code I currently have that is causing this is below and I have placed it in the textsum folder under tf_models.

```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import sys
import tensorflow as tf
from tensorflow.contrib.session_bundle import exporter

tf.app.flags.DEFINE_string("export_dir", "/exports/textsum",
                           "Directory where to export textsum model.")
tf.app.flags.DEFINE_integer('export_version', 1, 'version number of the model.')
tf.app.flags.DEFINE_bool("use_checkpoint_v2", False,
                     "If true, write v2 checkpoint files.")
FLAGS = tf.app.flags.FLAGS

def Export():
    with tf.Session() as sess:
        # Export model
        print('Exporting trained model to %s' % FLAGS.export_dir)
        init_op = tf.group(tf.initialize_all_tables(), name='init_op')
        saver = tf.train.Saver(sharded=True)
        model_exporter = exporter.Exporter(saver)
        model_exporter.init(
            sess.graph.as_graph_def(),
            init_op=init_op,
            default_graph_signature=exporter.classification_signature(
                input_tensor=serialized_tf_example,
                classes_tensor=prediction_classes,
                scores_tensor=values))
        model_exporter.export(FLAGS.export_dir, tf.constant(FLAGS.export_version), sess)
        print('Done exporting!')  

def main(_):
    Export()

if __name__ == "__main__":
    tf.app.run()
```

**Comment by xtr33me** [comment]
Going to close this issue as it seems that I had TF 0.9 installed and then installed this tensorflow_serving clone after. 0.9 does not seem to have exporter.py in session_bundle. I am assuming that uninstalling the older version and only having the tensorflow build in this clone is going to resolve the issue.
