### ISSUE TITLE
histogram_summary error while trying to serve InceptionV3 from Docker

### ISSUE THREAD

**Issue by souterjk** [tensorflow/serving#270]
I'm following the guide for serving the inception model with Docker, however I am getting an error when I try to export the downloaded model. When I run this command inside of my docker container:

`bazel-bin/tensorflow_serving/example/inception_export --checkpoint_dir=inception-v3 --export_dir=inception-export`

I get an error:
`Traceback (most recent call last):
  File "/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/tf_serving/tensorflow_serving/example/inception_export.py", line 169, in <module>
    tf.app.run()
  File "/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/tf_serving/tensorflow_serving/example/inception_export.py", line 165, in main
    export()
  File "/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/tf_serving/tensorflow_serving/example/inception_export.py", line 79, in export
    logits, _ = inception_model.inference(images, NUM_CLASSES + 1)
  File "/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/inception_model/inception/inception_model.py", line 90, in inference
    _activation_summaries(endpoints)
  File "/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/inception_model/inception/inception_model.py", line 157, in _activation_summaries
    _activation_summary(act)
  File "/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/inception_model/inception/inception_model.py", line 150, in _activation_summary
    tf.histogram_summary(tensor_name + '/activations', x)
AttributeError: 'module' object has no attribute 'histogram_summary'
`

Has anyone else seen this? Can someone help me move past it? The only modifications that I've made that were not from the walkthrough were to the 2 lines in ops.py described in this issue
https://github.com/tensorflow/serving/issues/250

**Comment by souterjk** [comment]
Never mind. Leaving this here in case someone else needs it:

The API has changed, the method call in that file (/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/inception_model/inception/inception_model.py) now needs to be tf.summary.histogram(... and the one below it (scalar) needs to be tf.summary.scalar(...

https://www.tensorflow.org/versions/r0.12/api_docs/python/summary.html#histogram
