### ISSUE TITLE
ERRORs while installation, package contains errors: tensorflow/core/platform/default/build_config., no such package '@local_config_sycl//sycl. missing fetch expression. 

### ISSUE THREAD

**Issue by vaklyuenkov** [tensorflow/serving#280]
Hello! Can't find anywhere info about same errors. 

Ubuntu 14.04.
Build label: 0.4.3
CUDA Version 8.0.44

Thank you!
```
/usr/local/serving/tensorflow /usr/local/serving/tensorflow
Please specify the location of python. [Default is /usr/bin/python]: 
Do you wish to build TensorFlow with Google Cloud Platform support? [y/N] y
Google Cloud Platform support will be enabled for TensorFlow
Do you wish to build TensorFlow with Hadoop File System support? [y/N] y
Hadoop File System support will be enabled for TensorFlow
Found possible Python library paths:
  /usr/local/lib/python2.7/dist-packages
  /usr/lib/python2.7/dist-packages
Please input the desired Python library path to use.  Default is [/usr/local/lib/python2.7/dist-packages]

Using python library path: /usr/local/lib/python2.7/dist-packages
Do you wish to build TensorFlow with OpenCL support? [y/N] y
OpenCL support will be enabled for TensorFlow
Do you wish to build TensorFlow with CUDA support? [y/N] y
CUDA support will be enabled for TensorFlow
Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]:  
Please specify the CUDA SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 
Please specify the location where CUDA  toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify the Cudnn version you want to use. [Leave empty to use system default]: 
Please specify the location where cuDNN  library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]: 
Please specify which C++ compiler should be used as the host C++ compiler. [Default is /usr/bin/g++]: 
Please specify which C compiler should be used as the host C compiler. [Default is /usr/bin/gcc]: 
Please specify the location where ComputeCpp for SYCL 1.2 is installed. [Default is /usr/local/computecpp]: 
INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
...........
____Loading package: tensorflow/core/util/tensor_bundle
____Loading package: tensorflow/contrib/crf
____Loading package: tensorflow/python/kernel_tests
ERROR: package contains errors: tensorflow/core/platform/default/build_config.
ERROR: error loading package 'tensorflow/core/platform/default/build_config': Encountered error while reading extension file 'sycl/platform.bzl': no such package '@local_config_sycl//sycl': Traceback (most recent call last):
        File "/usr/local/serving/tensorflow/third_party/sycl/sycl_configure.bzl", line 163
                _tpl(repository_ctx, "crosstool:BUILD")
        File "/usr/local/serving/tensorflow/third_party/sycl/sycl_configure.bzl", line 97, in _tpl
                repository_ctx.template(out, Label("//third_party/sycl/%s....), ...)
Unable to load package for //third_party/sycl/crosstool:BUILD.tpl: not found..
ERROR: missing fetch expression. Type 'bazel help fetch' for syntax and help.
```

**Comment by vaklyuenkov** [comment]
manually choose all versions and folders help.
