### ISSUE TITLE
Get "INTERNAL: HTTP/2 error code: INTERNAL_ERROR" when requesting tensorflow serving

### ISSUE THREAD

**Issue by tobegit3hub** [tensorflow/serving#284]
We have used TensorFlow Serving to load the model and provide gRPC services. We also implement the Java gRPC client to request TensorFlow Serving, which works like a charm.

But when we try to submit the Java code to Spark cluster, we got this error.

```
Job aborted due to stage failure: Task 47 in stage 7.0 failed 4 times, most recent failure: Lost task 47.3 in stage 7.0 (TID 5349, c3-hadoop-prc-st256.bj): io.grpc.StatusRuntimeException: INTERNAL: HTTP/2 error code: INTERNAL_ERROR
```

The trace is simple and we get nothing but "internal error".

```
Job aborted due to stage failure: Task 47 in stage 7.0 failed 4 times, most recent failure: Lost task 47.3 in stage 7.0 (TID 5349, xxx): io.grpc.StatusRuntimeException: INTERNAL: HTTP/2 error code: INTERNAL_ERROR
Received Rst Stream
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:230)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:211)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:144)
	at tensorflow.serving.PredictionServiceGrpc$PredictionServiceBlockingStub.predict(PredictionServiceGrpc.java:160)

	......

	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)
	at org.apache.spark.util.collection.ExternalSorter.insertAll(ExternalSorter.scala:189)
	at org.apache.spark.shuffle.sort.SortShuffleWriter.write(SortShuffleWriter.scala:64)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:73)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
	at org.apache.spark.scheduler.Task.run(Task.scala:91)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:219)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

Driver stacktrace:
```

We can run in locally but not in Spark cluster and we're not sure if it's related to OpenSSL or other libraries. How can we trace this error?

BTW, the TensorFlow Serving doesn't have log for this. Can we compile with the debug message for this?

**Comment by tobegit3hub** [comment]
We're sure that it's not related to Spark and can reproduce with large data.

Is there any restriction to transfer upon HTTP2 or gRPC? If we request with 1~2M data and it fails. If the data is smaller than 1M, it succeeds. Any feedback or solution about this?

**Comment by tobegit3hub** [comment]
The error message is not sufficient. If you compile the latest tensorflow_model_serving, I can get this message which is much more clear.

```
Caused by: io.grpc.StatusRuntimeException: INTERNAL: Frame size 7217879 exceeds maximum: 4194304. If this is normal, increase the maxMessageSize in the channel/server builder
	at io.grpc.Status.asRuntimeException(Status.java:536)
	at io.grpc.internal.MessageDeframer.processHeader(MessageDeframer.java:338)
	at io.grpc.internal.MessageDeframer.deliver(MessageDeframer.java:240)
	at io.grpc.internal.MessageDeframer.deframe(MessageDeframer.java:176)
	at io.grpc.internal.AbstractStream.deframe(AbstractStream.java:276)
	at io.grpc.internal.AbstractClientStream.inboundDataReceived(AbstractClientStream.java:150)
	at io.grpc.internal.Http2ClientStream.transportDataReceived(Http2ClientStream.java:137)
	at io.grpc.netty.NettyClientStream.transportDataReceived(NettyClientStream.java:180)
	at io.grpc.netty.NettyClientHandler.onDataRead(NettyClientHandler.java:251)
	at io.grpc.netty.NettyClientHandler.access$700(NettyClientHandler.java:92)
	at io.grpc.netty.NettyClientHandler$FrameListener.onDataRead(NettyClientHandler.java:588)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:256)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger$1.onDataRead(Http2InboundFrameLogger.java:48)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:410)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:244)
	at io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:155)
	at io.netty.handler.codec.http2.Http2InboundFrameLogger.readFrame(Http2InboundFrameLogger.java:41)
	at io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:113)
	at io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:333)
	at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:393)
```

Now the message size is limited to 4194304(4M) which is similar to our data size.

The code of the definition is in `serving/tensorflow_serving/model_servers/main.cc`.

```
builder.SetMaxMessageSize(tensorflow::kint32max);
```

And the final value is in `tensorflow/core/platform/types.h`.

```
static const int32 kint32max = ((int32)0x7FFFFFFF);
```

It should be resolved if I change the limitation of message size and re-compile the project. It would be better to add more instruction about this or make `maxMessageSize` configurable for users.

```
builder.SetMaxMessageSize(1024_1024_1024);
```
