### ISSUE TITLE
ImportError: No module named _py_wrap_tensorflow

### ISSUE THREAD

**Issue by E36lewis** [tensorflow/serving#343]
Trying to follow along with the basic tutorial, I'm able to complete all steps up until I run 
`$>bazel-bin/tensorflow_serving/example/mnist_saved_model /tmp/mnist_model`

Then I receive this
```
Traceback (most recent call last):
  File "/home/chris/serving/bazel-bin/tensorflow_serving/example/mnist_saved_model.runfiles/tf_serving/tensorflow_serving/example/mnist_saved_model.py", line 32, in <module>
    import tensorflow as tf
  File "/home/chris/serving/bazel-bin/tensorflow_serving/example/mnist_saved_model.runfiles/org_tensorflow/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/chris/serving/bazel-bin/tensorflow_serving/example/mnist_saved_model.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/chris/serving/bazel-bin/tensorflow_serving/example/mnist_saved_model.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 61, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/chris/serving/bazel-bin/tensorflow_serving/example/mnist_saved_model.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/home/chris/serving/bazel-bin/tensorflow_serving/example/mnist_saved_model.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 20, in swig_import_helper
    import _pywrap_tensorflow
ImportError: No module named _pywrap_tensorflow

```

Failed to load the native TensorFlow runtime.

See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#import_error

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
Im confused on what could be the error because I ran `bazel test tensorflow_serving/...--test_verbose_timeout_warnings
`

with an output of this
```
WARNING: /home/chris/.cache/bazel/_bazel_chris/eef30f2fca530b8705683f2a1edee38d/external/org_tensorflow/tensorflow/workspace.bzl:71:5: tf_repo_name was specified to tf_workspace but is no longer used and will be removed in the future.
WARNING: /home/chris/.cache/bazel/_bazel_chris/eef30f2fca530b8705683f2a1edee38d/external/inception_model/WORKSPACE:1: Workspace name in /home/chris/.cache/bazel/_bazel_chris/eef30f2fca530b8705683f2a1edee38d/external/inception_model/WORKSPACE (@inception) does not match the name given in the repository's definition (@inception_model); this will cause a build error in future versions.
INFO: Found 206 targets and 60 test targets...
INFO: Elapsed time: 0.651s, Critical Path: 0.07s
//tensorflow_serving/batching:basic_batch_scheduler_test        (cached) PASSED in 0.3s
  WARNING: //tensorflow_serving/batching:basic_batch_scheduler_test: Test execution time (0.3s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//tensorflow_serving/batching:batch_scheduler_retrier_test      (cached) PASSED in 0.3s
  WARNING: //tensorflow_serving/batching:batch_scheduler_retrier_test: Test execution time (0.3s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//tensorflow_serving/batching:batch_scheduler_test              (cached) PASSED in 0.3s
  WARNING: //tensorflow_serving/batching:batch_scheduler_test: Test execution time (0.3s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//tensorflow_serving/batching:batching_session_test             (cached) PASSED in 1.0s
  WARNING: //tensorflow_serving/batching:batching_session_test: Test execution time (1.0s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//tensorflow_serving/batching:shared_batch_scheduler_test       (cached) PASSED in 0.6s
  WARNING: //tensorflow_serving/batching:shared_batch_scheduler_test: Test execution time (0.6s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//tensorflow_serving/batching:streaming_batch_scheduler_test    (cached) PASSED in 4.1s
  WARNING: //tensorflow_serving/batching:streaming_batch_scheduler_test: Test execution time (4.1s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//tensorflow_serving/batching/test_util:puppet_batch_scheduler_test (cached) PASSED in 0.3s
  WARNING: //tensorflow_serving/batching/test_util:puppet_batch_scheduler_test: Test execution time (0.3s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//tensorflow_serving/core:aspired_version_policy_test           (cached) PASSED in 0.4s
  WARNING: //tensorflow_serving/core:aspired_version_policy_test: Test execution time (0.4s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//tensorflow_serving/core:aspired_versions_manager_benchmark    (cached) PASSED in 29.6s
//tensorflow_serving/core:aspired_versions_manager_builder_test (cached) PASSED in 0.6s
  WARNING: //tensorflow_serving/core:aspired_versions_manager_builder_test: Test execution time (0.6s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//tensorflow_serving/core:aspired_versions_manager_test         (cached) PASSED in 6.3s
//tensorflow_serving/core:availability_preserving_policy_test   (cached) PASSED in 0.3s
  WARNING: //tensorflow_serving/core:availability_preserving_policy_test: Test execution time (0.3s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//tensorflow_serving/core:basic_manager_test                    (cached) PASSED in 9.3s
//tensorflow_serving/core:caching_manager_test                  (cached) PASSED in 0.9s
  WARNING: //tensorflow_serving/core:caching_manager_test: Test execution time (0.9s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//tensorflow_serving/core:dynamic_source_router_test            (cached) PASSED in 0.3s
  WARNING: //tensorflow_serving/core:dynamic_source_router_test: Test execution time (0.3s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//tensorflow_serving/core:loader_harness_test                   (cached) PASSED in 0.4s
  WARNING: //tensorflow_serving/core:loader_harness_test: Test execution time (0.4s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//tensorflow_serving/core:log_collector_test                    (cached) PASSED in 0.1s
  WARNING: //tensorflow_serving/core:log_collector_test: Test execution time (0.1s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//tensorflow_serving/core:manager_test                          (cached) PASSED in 0.1s
  WARNING: //tensorflow_serving/core:manager_test: Test execution time (0.1s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//tensorflow_serving/core:request_logger_test                   (cached) PASSED in 0.2s
//tensorflow_serving/core:resource_preserving_policy_test       (cached) PASSED in 0.1s
  WARNING: //tensorflow_serving/core:resource_preserving_policy_test: Test execution time (0.1s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//tensorflow_serving/core:servable_data_test                    (cached) PASSED in 0.1s
  WARNING: //tensorflow_serving/core:servable_data_test: Test execution time (0.1s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//tensorflow_serving/core:servable_id_test                      (cached) PASSED in 0.1s
  WARNING: //tensorflow_serving/core:servable_id_test: Test execution time (0.1s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//tensorflow_serving/core:servable_state_monitor_test           (cached) PASSED in 0.3s
//tensorflow_serving/core:server_request_logger_test            (cached) PASSED in 0.4s
//tensorflow_serving/core:simple_loader_test                    (cached) PASSED in 0.2s
  WARNING: //tensorflow_serving/core:simple_loader_test: Test execution time (0.2s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//tensorflow_serving/core:source_adapter_test                   (cached) PASSED in 1.2s
  WARNING: //tensorflow_serving/core:source_adapter_test: Test execution time (1.2s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//tensorflow_serving/core:source_router_test                    (cached) PASSED in 2.2s
  WARNING: //tensorflow_serving/core:source_router_test: Test execution time (2.2s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//tensorflow_serving/core:static_manager_test                   (cached) PASSED in 0.6s
  WARNING: //tensorflow_serving/core:static_manager_test: Test execution time (0.6s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//tensorflow_serving/core:static_source_router_test             (cached) PASSED in 0.3s
  WARNING: //tensorflow_serving/core:static_source_router_test: Test execution time (0.3s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//tensorflow_serving/core:storage_path_test                     (cached) PASSED in 0.2s
  WARNING: //tensorflow_serving/core:storage_path_test: Test execution time (0.2s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//tensorflow_serving/model_servers:server_core_test             (cached) PASSED in 9.2s
//tensorflow_serving/resources:resource_tracker_test            (cached) PASSED in 0.4s
//tensorflow_serving/resources:resource_util_test               (cached) PASSED in 0.2s
//tensorflow_serving/servables/hashmap:hashmap_source_adapter_test (cached) PASSED in 0.8s
  WARNING: //tensorflow_serving/servables/hashmap:hashmap_source_adapter_test: Test execution time (0.8s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//tensorflow_serving/servables/tensorflow:bundle_factory_util_test (cached) PASSED in 4.7s
  WARNING: //tensorflow_serving/servables/tensorflow:bundle_factory_util_test: Test execution time (4.7s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//tensorflow_serving/servables/tensorflow:classifier_test       (cached) PASSED in 1.0s
  WARNING: //tensorflow_serving/servables/tensorflow:classifier_test: Test execution time (1.0s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//tensorflow_serving/servables/tensorflow:get_model_metadata_impl_test (cached) PASSED in 39.2s
//tensorflow_serving/servables/tensorflow:predict_impl_test     (cached) PASSED in 42.4s
//tensorflow_serving/servables/tensorflow:regressor_test        (cached) PASSED in 1.7s
  WARNING: //tensorflow_serving/servables/tensorflow:regressor_test: Test execution time (1.7s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//tensorflow_serving/servables/tensorflow:saved_model_bundle_factory_test (cached) PASSED in 1.3s
  WARNING: //tensorflow_serving/servables/tensorflow:saved_model_bundle_factory_test: Test execution time (1.3s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//tensorflow_serving/servables/tensorflow:saved_model_bundle_source_adapter_test (cached) PASSED in 0.3s
  WARNING: //tensorflow_serving/servables/tensorflow:saved_model_bundle_source_adapter_test: Test execution time (0.3s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//tensorflow_serving/servables/tensorflow:session_bundle_factory_test (cached) PASSED in 2.3s
  WARNING: //tensorflow_serving/servables/tensorflow:session_bundle_factory_test: Test execution time (2.3s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//tensorflow_serving/servables/tensorflow:session_bundle_source_adapter_test (cached) PASSED in 0.3s
  WARNING: //tensorflow_serving/servables/tensorflow:session_bundle_source_adapter_test: Test execution time (0.3s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//tensorflow_serving/servables/tensorflow:simple_servers_test   (cached) PASSED in 1.3s
  WARNING: //tensorflow_serving/servables/tensorflow:simple_servers_test: Test execution time (1.3s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//tensorflow_serving/servables/tensorflow:util_test             (cached) PASSED in 0.4s
//tensorflow_serving/sources/storage_path:file_system_storage_path_source_test (cached) PASSED in 0.4s
  WARNING: //tensorflow_serving/sources/storage_path:file_system_storage_path_source_test: Test execution time (0.4s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//tensorflow_serving/sources/storage_path:static_storage_path_source_test (cached) PASSED in 0.1s
//tensorflow_serving/util:any_ptr_test                          (cached) PASSED in 0.1s
  WARNING: //tensorflow_serving/util:any_ptr_test: Test execution time (0.1s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//tensorflow_serving/util:class_registration_test               (cached) PASSED in 0.2s
  WARNING: //tensorflow_serving/util:class_registration_test: Test execution time (0.2s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//tensorflow_serving/util:cleanup_test                          (cached) PASSED in 0.3s
//tensorflow_serving/util:event_bus_test                        (cached) PASSED in 0.6s
//tensorflow_serving/util:fast_read_dynamic_ptr_benchmark       (cached) PASSED in 30.1s
//tensorflow_serving/util:fast_read_dynamic_ptr_test            (cached) PASSED in 2.2s
  WARNING: //tensorflow_serving/util:fast_read_dynamic_ptr_test: Test execution time (2.2s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//tensorflow_serving/util:inline_executor_test                  (cached) PASSED in 0.1s
  WARNING: //tensorflow_serving/util:inline_executor_test: Test execution time (0.1s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//tensorflow_serving/util:observer_test                         (cached) PASSED in 0.3s
//tensorflow_serving/util:optional_test                         (cached) PASSED in 0.2s
//tensorflow_serving/util:periodic_function_test                (cached) PASSED in 1.8s
  WARNING: //tensorflow_serving/util:periodic_function_test: Test execution time (1.8s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//tensorflow_serving/util:retrier_test                          (cached) PASSED in 0.1s
  WARNING: //tensorflow_serving/util:retrier_test: Test execution time (0.1s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//tensorflow_serving/util:threadpool_executor_test              (cached) PASSED in 3.6s
  WARNING: //tensorflow_serving/util:threadpool_executor_test: Test execution time (3.6s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//tensorflow_serving/util:unique_ptr_with_deps_test             (cached) PASSED in 0.1s

Executed 0 out of 60 tests: 60 tests pass.
```

also ran this  `ldd /usr/local/lib/python3.5/dist-packages/tensorflow/python/_pywrap_tensorflow.so`

output
```

	linux-vdso.so.1 =>  (0x00007ffc46dd4000)
	libcublas.so.8.0 => /usr/local/cuda/lib64/libcublas.so.8.0 (0x00007f31252a7000)
	libcuda.so.1 => /usr/lib/x86_64-linux-gnu/libcuda.so.1 (0x00007f3124894000)
	libcudnn.so.5 => /usr/local/cuda/lib64/libcudnn.so.5 (0x00007f311f624000)
	libcufft.so.8.0 => /usr/local/cuda/lib64/libcufft.so.8.0 (0x00007f31167d6000)
	libcurand.so.8.0 => /usr/local/cuda/lib64/libcurand.so.8.0 (0x00007f311286d000)
	libcudart.so.8.0 => /usr/local/cuda/lib64/libcudart.so.8.0 (0x00007f3112606000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f3112402000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f31120f9000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3111edb000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f3111b59000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f3111943000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3111579000)
	/lib64/ld-linux-x86-64.so.2 (0x000055f36aea2000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f3111371000)
	libnvidia-fatbinaryloader.so.375.39 => /usr/lib/nvidia-375/libnvidia-fatbinaryloader.so.375.39 (0x00007f3111125000)

```
Also ran this l`s -l /usr/local/cuda/lib64/libcud*`

Output was 

```
-rw-r--r-- 1 root root   558720 Feb  7 11:56 /usr/local/cuda/lib64/libcudadevrt.a
lrwxrwxrwx 1 root root       16 Feb  7 11:56 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.8.0
lrwxrwxrwx 1 root root       19 Feb  7 11:56 /usr/local/cuda/lib64/libcudart.so.8.0 -> libcudart.so.8.0.44
-rwxr-xr-x 1 root root   415432 Feb  7 11:56 /usr/local/cuda/lib64/libcudart.so.8.0.44
-rw-r--r-- 1 root root   775162 Feb  7 11:56 /usr/local/cuda/lib64/libcudart_static.a
lrwxrwxrwx 1 root root       13 Feb  7 12:27 /usr/local/cuda/lib64/libcudnn.so -> libcudnn.so.5
lrwxrwxrwx 1 root root       18 Feb  7 12:27 /usr/local/cuda/lib64/libcudnn.so.5 -> libcudnn.so.5.1.10
-rwxr-xr-x 1 root root 84163560 Feb  7 12:27 /usr/local/cuda/lib64/libcudnn.so.5.1.10
-rw-r--r-- 1 root root 70364814 Feb  7 12:27 /usr/local/cuda/lib64/libcudnn_static.a
```

Running on Ubuntu 16.04 in anaconda3 env 
If you need any more info let me know I'm going to keep tinkering but I've been working on it for half a day and got nothing.

**Comment by E36lewis** [comment]
So I pulled the latest version of tensorflow from Github, then configured, ran bazel build. Now when I run `bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server`

which runs the server fine, but when I try to run 
`
bazel-bin/tensorflow_serving/example/inception_export --checkpoint_dir=inception-v3 --export_dir=inception-export`

I receive an error for 

`_pywrap_tensorflow.so: undefined symbol: PyBytes_AsStringAndSize`

I did some research on that piticular error through google and everything that has come up is related to the python version it is [compiled](https://github.com/tensorflow/tensorflow/issues/479) with, but the version I compiled with is the same as in my venv that I'm using.

Here is the full error

```
(tensorflow) chris@chris-desktop:~/serving$ bazel-bin/tensorflow_serving/example/inception_export --checkpoint_dir=inception-v3 --export_dir=inception-export
Traceback (most recent call last):
  File "/home/chris/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/tf_serving/tensorflow_serving/example/inception_export.py", line 29, in <module>
    import tensorflow as tf
  File "/home/chris/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/org_tensorflow/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/chris/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 72, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/chris/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 61, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/chris/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/home/chris/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: /home/chris/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow.so: undefined symbol: PyBytes_AsStringAndSize


Failed to load the native TensorFlow runtime.

```
As always will continue to go down the rabbits hole, if anyone has some info on the problem or can help please post.

**Comment by E36lewis** [comment]
So I've been digging and have basically come to this point:
The error is being raised because of TypeError not UnicodeEncodeError(I checked my system, it's 1114111)
It's all happing here(inside:~/servinng/tensorflow/tensorflow/python/lib/core/strings.i):
```

bool _BytesToStringPiece(PyObject* obj, tensorflow::StringPiece* result) {
  if (obj == Py_None) {
    result->clear();
  } else {
    char* ptr;
    Py_ssize_t len;
    if (PyBytes_AsStringAndSize(obj, &ptr, &len) == -1) {
      // Python has raised an error (likely TypeError or UnicodeEncodeError).
      return false;
    }
    result->set(ptr, len);
  }
  return true;
}

```

What I get with some research is  

> > exception [TypeError](https://docs.python.org/3/library/exceptions.html#TypeError)

I just don't know how that is possible, seeing that I'm following the tutorials step by step?

Clarification would be very appreciated.

**Comment by gautamvasudevan** [comment]
Please see the latest [Docker examples](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/docker.md) for bringing up a build environment that will also build the examples. Dependencies are very tricky specific here.
