### ISSUE TITLE
Inception in k8s Issue

### ISSUE THREAD

**Issue by drstarson** [tensorflow/serving#397]
I'm following the Serving Inception Model with TensorFlow Serving and Kubernetes workflow and everything work up to the point of the final serving of the inception model via k8s. 

I'm getting the pods running and the output of $kubectl describe service inception-service is consistent with what is suggested by the workflow in the https://tensorflow.github.io/serving/serving_inception.html workflow. 

However, when running inference things don't work. Here is the trace: 

bazel-bin/tensorflow_serving/example/inception_client --server=[External IP]:9000 --image=download.jpg
Traceback (most recent call last):
  File "/home/dimlyus/serving/bazel-bin/tensorflow_serving/example/inception_client.runfi
les/tf_serving/tensorflow_serving/example/inception_client.py", line 56, in <module>
    tf.app.run()
  File "/home/dimlyus/serving/bazel-bin/tensorflow_serving/example/inception_client.runfi
les/org_tensorflow/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/dimlyus/serving/bazel-bin/tensorflow_serving/example/inception_client.runfi
les/tf_serving/tensorflow_serving/example/inception_client.py", line 51, in main
    result = stub.Predict(request, 60.0)  # 10 secs timeout
  File "/usr/local/lib/python2.7/dist-packages/grpc/beta/_client_adaptations.py", line 32
4, in __call__
    self._request_serializer, self._response_deserializer)
  File "/usr/local/lib/python2.7/dist-packages/grpc/beta/_client_adaptations.py", line 21
0, in _blocking_unary_unary
    raise _abortion_error(rpc_error_call)
grpc.framework.interfaces.face.face.AbortionError: AbortionError(code=StatusCode.UNAVAILA
BLE, details="Connect Failed")

Any advice on how to troubleshoot this would be greatly appreciated!

**Comment by drstarson** [comment]
This issue is resolved. The solution is shared here: [http://stackoverflow.com/questions/43301262/how-to-troubleshoot-deployment-of-inception-serving-running-in-kubernetes](http://stackoverflow.com/questions/43301262/how-to-troubleshoot-deployment-of-inception-serving-running-in-kubernetes)
