### ISSUE TITLE
inception_client failed

### ISSUE THREAD

**Issue by zhihongzeng** [tensorflow/serving#412]
Host OS: ubuntu 16.04 LTS
working environment on docker container based on 
https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/docker.md

**Step 1: compile and test serving** 
git clone --recurse-submodules https://github.com/tensorflow/serving
cd serving/tensorflow
./configure
cd ..
bazel test tensorflow_serving/...
....
Executed 58 out of 58 tests: 58 tests pass.

version info:
root@b83acbc1db2e:/serving# git describe --tags
0.5.0-95-g05ebb72
root@b83acbc1db2e:/serving# cd tensorflow
root@b83acbc1db2e:/serving/tensorflow# git describe --tags
v1.1.0-rc1-15-gf8dce81

**Step 2:: start server**
root@b83acbc1db2e:/serving# curl -O http://download.tensorflow.org/models/image/imagenet/inception-v3-2016-03-01.tar.gz
root@b83acbc1db2e:/serving# tar xzf inception-v3-2016-03-01.tar.gz
root@b83acbc1db2e:/serving# bazel-bin/tensorflow_serving/example/inception_saved_model --checkpoint_dir=inception-v3 --output_dir=inception-export
WARNING:tensorflow:From /serving/bazel-bin/tensorflow_serving/example/inception_saved_model.runfiles/tf_serving/tensorflow_serving/example/inception_saved_model.py:98: index_to_string (from tensorflow.contrib.lookup.lookup_ops) is deprecated and will be removed after 2017-01-07.
Instructions for updating:
This op will be removed after the deprecation date. Please switch to index_to_string_table_from_tensor and call the lookup method of the returned table.
2017-04-19 16:01:27.861170: W external/org_tensorflow/tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-04-19 16:01:27.861202: W external/org_tensorflow/tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-04-19 16:01:27.861215: W external/org_tensorflow/tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-04-19 16:01:27.861242: W external/org_tensorflow/tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-04-19 16:01:27.861255: W external/org_tensorflow/tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Successfully loaded model from inception-v3/model.ckpt-157585 at step=157585.
Exporting trained model to inception-export/1
WARNING:tensorflow:From /serving/bazel-bin/tensorflow_serving/example/inception_saved_model.runfiles/tf_serving/tensorflow_serving/example/inception_saved_model.py:155: initialize_all_tables (from tensorflow.python.ops.data_flow_ops) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.tables_initializer` instead.
Successfully exported model to inception-export

root@b83acbc1db2e:/serving# bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server --port=9000 --model_name=inception --model_base_path=inception-export &> inception_log &
[1] 24293

**Step 3: Query image**: 
root@b83acbc1db2e:/serving# bazel-bin/tensorflow_serving/example/inception_client --server=localhost:9000 --image=originalLeopard.jpg
D0419 16:08:00.296979503   25102 ev_posix.c:101]             Using polling engine: poll
I0419 16:08:02.360389974   25105 socket_utils_common_posix.c:205] Disabling AF_INET6 sockets because ::1 is not available.
Traceback (most recent call last):
  File "/serving/bazel-bin/tensorflow_serving/example/inception_client.runfiles/tf_serving/tensorflow_serving/example/inception_client.py", line 56, in <module>
    tf.app.run()
  File "/serving/bazel-bin/tensorflow_serving/example/inception_client.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/serving/bazel-bin/tensorflow_serving/example/inception_client.runfiles/tf_serving/tensorflow_serving/example/inception_client.py", line 51, in main
    result = stub.Predict(request, 10.0)  # 10 secs timeout
  File "/usr/local/lib/python2.7/dist-packages/grpc/beta/_client_adaptations.py", line 300, in __call__
    self._request_serializer, self._response_deserializer)
  File "/usr/local/lib/python2.7/dist-packages/grpc/beta/_client_adaptations.py", line 198, in _blocking_unary_unary
    raise _abortion_error(rpc_error_call)
grpc.framework.interfaces.face.face.ExpirationError: ExpirationError(code=StatusCode.DEADLINE_EXCEEDED, details="Deadline Exceeded")
E0419 16:08:12.453529181   25102 chttp2_transport.c:1810]    close_transport: {"created":"@1492618092.453497866","description":"FD shutdown","file":"src/core/lib/iomgr/ev_poll_posix.c","file_line":427}

Here are inception log of the server:
root@b83acbc1db2e:/serving# cat inception_log  
2017-04-19 16:03:00.012677: I tensorflow_serving/model_servers/main.cc:155] Building single TensorFlow model file config:  model_name: inception model_base_path: inception-export model_version_policy: 0
2017-04-19 16:03:00.012999: I tensorflow_serving/model_servers/server_core.cc:338] Adding/updating models.
2017-04-19 16:03:00.013024: I tensorflow_serving/model_servers/server_core.cc:384]  (Re-)adding model: inception
2017-04-19 16:03:00.113606: I tensorflow_serving/core/basic_manager.cc:698] Successfully reserved resources to load servable {name: inception version: 1}
2017-04-19 16:03:00.113640: I tensorflow_serving/core/loader_harness.cc:66] Approving load for servable version {name: inception version: 1}
2017-04-19 16:03:00.113656: I tensorflow_serving/core/loader_harness.cc:74] Loading servable version {name: inception version: 1}
2017-04-19 16:03:00.113696: I external/org_tensorflow/tensorflow/contrib/session_bundle/bundle_shim.cc:360] Attempting to load native SavedModelBundle in bundle-shim from: inception-export/1
2017-04-19 16:03:00.113717: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:226] Loading SavedModel from: inception-export/1
2017-04-19 16:03:00.203846: W external/org_tensorflow/tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-04-19 16:03:00.203883: W external/org_tensorflow/tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-04-19 16:03:00.203890: W external/org_tensorflow/tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-04-19 16:03:00.203896: W external/org_tensorflow/tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-04-19 16:03:00.203901: W external/org_tensorflow/tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-04-19 16:03:00.515790: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:145] Restoring SavedModel bundle.
2017-04-19 16:03:01.169838: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:180] Running LegacyInitOp on SavedModel bundle.
2017-04-19 16:03:01.252482: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:274] Loading SavedModel: success. Took 1138245 microseconds.
2017-04-19 16:03:01.252636: I tensorflow_serving/core/loader_harness.cc:86] Successfully loaded servable version {name: inception version: 1}
2017-04-19 16:03:01.263060: I tensorflow_serving/model_servers/main.cc:298] Running ModelServer at 0.0.0.0:9000 ...

Any idea would be appreciated.
Zhihong

**Comment by zhihongzeng** [comment]
Here is my new successful results after the above the post:

To compile code, instead of using "bazel test tensorflow_serving/...", I ran:

bazel build -c opt tensorflow_serving/...

Then: 
root@b83acbc1db2e:/serving# bazel-bin/tensorflow_serving/example/inception_saved_model --checkpoint_dir=inception-v3 --output_dir=inception-export
root@b83acbc1db2e:/serving# bazel-bin/tensorflow_serving/model_servers/tensorflow_model_server --port=9000 --model_name=inception --model_base_path=inception-export &> inception_log &
root@b83acbc1db2e:/serving# bazel-bin/tensorflow_serving/example/inception_client --server=localhost:9000 --image=originalLeopard.jpg
D0420 18:32:18.496340847   23244 ev_posix.c:101]             Using polling engine: poll
I0420 18:32:20.460148827   23247 socket_utils_common_posix.c:205] Disabling AF_INET6 sockets because ::1 is not available.
outputs {
  key: "classes"
  value {
    dtype: DT_STRING
    tensor_shape {
      dim {
        size: 1
      }
      dim {
        size: 5
      }
    }
    string_val: "jaguar, panther, Panthera onca, Felis onca"
    string_val: "leopard, Panthera pardus"
    string_val: "cheetah, chetah, Acinonyx jubatus"
    string_val: "cougar, puma, catamount, mountain lion, painter, panther, Felis concolor"
    string_val: "snow leopard, ounce, Panthera uncia"
  }
}
outputs {
  key: "scores"
  value {
    dtype: DT_FLOAT
    tensor_shape {
      dim {
        size: 1
      }
      dim {
        size: 5
      }
    }
    float_val: 9.80259609222
    float_val: 6.51670694351
    float_val: 2.97874474525
    float_val: 2.27059745789
    float_val: 2.13479757309
  }
}

**Comment by sukritiramesh** [comment]
Hi @zhihongzeng, thanks for looping back on this. Can you please describe your fix? (Useful to document in case someone else encounters the same/similar problem).

**Comment by zhihongzeng** [comment]
@sukritiramesh , thanks for your encouragement.

What I found during serving inception model with docker is: 
Following https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/docker.md, and run "bazel test tensorflow_serving/... " will compile the code and test code (success),  it may fail to run inception_client in https://tensorflow.github.io/serving/serving_inception.

The solution is: 
following https://tensorflow.github.io/serving/serving_inception, and run the following command to compile the code:
bazel build -c opt tensorflow_serving/...

**Comment by sukritiramesh** [comment]
Good to hear! Closing this issue for now, please feel free to reopen if you have further problems.
