### ISSUE TITLE
Provide example for resnetv2 client

### ISSUE THREAD

**Issue by gitmalong** [tensorflow/serving#433]
I'd be happy to see an example client for resnet v2.

**Comment by gitmalong** [comment]
I'm piggy backing off inception saved model and inception client.

In [inception_saved_model.py](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/inception_saved_model.py) I replaced

```

    # Run inference.
    logits, _ = inception_model.inference(images, NUM_CLASSES + 1)

```
with

`        logits, _ = inception.inception_resnet_v2(images, num_classes=len(labels_to_names), is_training=False)

(I'm using TF slim)
.


`

`  with open(FLAGS.image, 'rb') as f:
    # See prediction_service.proto for gRPC request/response details.
    data = f.read()
    request = predict_pb2.PredictRequest()
    request.model_spec.name = 'inception'
    request.model_spec.signature_name = 'predict_images'
    request.inputs['images'].CopyFrom(
        tf.contrib.util.make_tensor_proto(data, dtype=tf.string))
    result = stub.Predict(request, 10.0)  # 10 secs timeout
    print(result)
`
In [inception_client.py](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/inception_client.py) I replaced

```
    request.inputs['images'].CopyFrom(
        tf.contrib.util.make_tensor_proto(data, shape=[1]))
```

with
```

    request.inputs['images'].CopyFrom(
        tf.contrib.util.make_tensor_proto(data, dtype.tf.string))
```

Running the client results in

```
Traceback (most recent call last):
  File "/home/ubuntu/serving/bazel-bin/tensorflow_serving/example/resnet_client.runfiles/tf_serving/tensorflow_serving/example/resnet_client.py", line 56, in <module>
    tf.app.run()
  File "/home/ubuntu/serving/bazel-bin/tensorflow_serving/example/resnet_client.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/ubuntu/serving/bazel-bin/tensorflow_serving/example/resnet_client.runfiles/tf_serving/tensorflow_serving/example/resnet_client.py", line 51, in main
    result = stub.Predict(request, 10.0)  # 10 secs timeout
  File "/usr/local/lib/python2.7/dist-packages/grpc/beta/_client_adaptations.py", line 323, in __call__
    self._request_serializer, self._response_deserializer)
  File "/usr/local/lib/python2.7/dist-packages/grpc/beta/_client_adaptations.py", line 209, in _blocking_unary_unary
    raise _abortion_error(rpc_error_call)
grpc.framework.interfaces.face.face.AbortionError: AbortionError(code=StatusCode.INVALID_ARGUMENT, details="slice index 0 of dimension 0 out of bounds.
	 [[Node: map/strided_slice = StridedSlice[Index=DT_INT32, T=DT_INT32, _output_shapes=[[]], begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=1, _device="/job:localhost/replica:0/task:0/cpu:0"](map/Shape, map/strided_slice/stack, map/strided_slice/stack_1, map/strided_slice/stack_2)]]")

```

**Comment by gitmalong** [comment]
I was able to let it work when defined my placeholder as seen [here](http://stackoverflow.com/questions/39902596/tensorflow-inception-resnet-v2-classify-image/41240131#41240131). But the prediction takes about 15sec. I'm recompiling with cpu optimizations now.
