### ISSUE TITLE
ImportError: No module named mock

### ISSUE THREAD

**Issue by DrewParallel** [tensorflow/serving#451]
I use VirtualBox and the guest OS is Ubuntu 14.04.5 LTS.

When trying to run bazel-bin/tensorflow_serving/example/mnist_export /tmp/mnist_model, I get this error:
```
Traceback (most recent call last):
  File "src/serving/bazel-bin/tensorflow_serving/example/mnist_export.runfiles/tf_serving/tensorflow_serving/example/mnist_export.py", line 34, in <module>
    import tensorflow as tf
  File "src/serving/bazel-bin/tensorflow_serving/example/mnist_export.runfiles/org_tensorflow/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "src/serving/bazel-bin/tensorflow_serving/example/mnist_export.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 104, in <module>
    from tensorflow.python.platform import test
  File "src/serving/bazel-bin/tensorflow_serving/example/mnist_export.runfiles/org_tensorflow/tensorflow/python/platform/test.py", line 53, in <module>
    import mock                # pylint: disable=g-import-not-at-top,unused-import
ImportError: No module named mock
```

**Comment by kirilg** [comment]
You can install mock with the command `sudo pip install mock`

**Comment by DrewParallel** [comment]
Yup, that worked. Thank you.

**Comment by wengchen1993** [comment]
Hi,

I am currently running python 3.5 on Vagrant Ubuntu Xenial 16.04 LTS and I think that gave me the same problem when I tried to run the same command. Tried pip install mock but no luck, any suggestions that I can possibly solve this?

Thanks!

**Comment by DIT4FUN** [comment]
my os is centos7 ,same error,but pip install mock,stil can't work
