### ISSUE TITLE
tf.learn DNNClassifier iris example empty feature column name can't predict  

### ISSUE THREAD

**Issue by haiy** [tensorflow/serving#458]
I successfully save the [example](https://www.tensorflow.org/get_started/tflearn) with  this method
```python
def save_tf_learn_model(estimator, feature_columns, export_dir):
    feature_spec = create_feature_spec_for_parsing(feature_columns)
    serving_input_fn = input_fn_utils.build_parsing_serving_input_fn(feature_spec)
    estimator.export_savedmodel(export_dir, serving_input_fn)
    print("Done exporting tf.learn model to " + export_dir + "!")
```
But I can't use the client to do predict.
Here is my client code 
```python
import numpy as np
import tensorflow as tf
from grpc.beta import implementations
from tensorflow_serving.apis import predict_pb2
from tensorflow_serving.apis import prediction_service_pb2

tf.app.flags.DEFINE_string('server', 'localhost:9000',
                           'Server host:port.')
tf.app.flags.DEFINE_string('model', 'iris_model',
                           'Model name.')
FLAGS = tf.app.flags.FLAGS
host, port = FLAGS.server.split(':')
  channel = implementations.insecure_channel(host, int(port))
  stub = prediction_service_pb2.beta_create_PredictionService_stub(channel)

  request = predict_pb2.PredictRequest()
  request.model_spec.name = FLAGS.model
  request.model_spec.signature_name = 'serving_default'

  # feature_dict = {"f": _float_feature(value = [6.4, 3.2, 4.5, 1.5])}
  feature_dict = _float_feature(value = [6.4, 3.2, 4.5, 1.5])
  label = 0

  example = tf.train.Example(features=tf.train.Features(feature=feature_dict))
  serialized = example.SerializeToString()

  request.inputs['inputs'].CopyFrom(
        tf.contrib.util.make_tensor_proto(serialized, shape=[1]))


  result_future = stub.Predict.future(request, 5.0)
  prediction = result_future.result().outputs['scores']

  print('True label: ' + str(label))
  print('Prediction: ' + str(np.argmax(prediction)))

```

the error:
```
ERROR:root:Invalid encoding on b"Could not parse example input, value: '\n\x18\n\x16\x12\x14\x12\x12\n\x10\xcd\xcc\xcc@\xcd\xccL@"
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/grpc/beta/_client_adaptations.py", line 110, in result
    return self._future.result(timeout=timeout)
  File "/usr/local/lib/python3.5/site-packages/grpc/_channel.py", line 294, in result
    raise self
grpc._channel._Rendezvous: <unprintable _Rendezvous object>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/grpc/_common.py", line 93, in decode
    return b.decode('utf8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcd in position 49: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/grpc/_common.py", line 93, in decode
    return b.decode('utf8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcd in position 49: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/grpc/_common.py", line 93, in decode
    return b.decode('utf8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcd in position 49: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/grpc/_common.py", line 93, in decode
    return b.decode('utf8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcd in position 49: invalid continuation byte

During handling of the above exception, another exception occurred:
```

Please  give some suggestions to make it run.

**Comment by haiy** [comment]
any one can give some suggestions?Thanks so much.

**Comment by davidsoergel** [comment]
I think what is happening here is as follows:
* The example uses an empty feature name because there is only one feature.  In this case, TF 1.1 automatically renames the feature to "inputs".  Thus I think your client would work with
`feature_dict = {"inputs": _float_feature(value = [6.4, 3.2, 4.5, 1.5])}`
* Because this was confusing, you tried setting feature_dict to something that is not a dict.  That makes `tf.train.Features(feature=feature_dict)` invalid and in my opinion should have thrown a more informative error.  Anyway this is the reason for the "invalid encoding" errors coming from the gRPC library.

The automatic renaming of the predict inputs is considered a bug, and was removed in TF 1.2. 
I'm not sure whether an empty feature name should be considered valid; I'll look into that.  Even if it is, you'll still need to specify that name in your feature_dict when constructing the request, e.g. 
`feature_dict = {"": _float_feature(value = [6.4, 3.2, 4.5, 1.5])}`

**Comment by haiy** [comment]
@davidsoergel thanks so much for your reply.I'm so sorry that the line I've pasted  a wrong version about feature dict.Actually the error was caused by 

```python
feature_dict = {"": _float_feature(value = [6.4, 3.2, 4.5, 1.5])}
```

the corresponding server output is 

```
2017-06-16 18:47:23.762493: W external/org_tensorflow/tensorflow/core/framework/op_kernel.cc:1169] Invalid argument: Could not parse example input, value: '


���@��L@

```

Could you please give some further information about how to fix it in version 1.1.0?

**Comment by ariwaranosai** [comment]
This may cause by protobuf in python implement which will remove "" during SerializeToString. 
see [this](https://github.com/google/protobuf/issues/3381).

@haiy  @davidsoergel
