### ISSUE TITLE
SyntaxError: invalid syntax when building with python3.

### ISSUE THREAD

**Issue by abcfy2** [tensorflow/serving#527]
I'm using python3 installed by `anaconda`. But I cannot compile tensorflow-serving:

```
RROR: /home/fengyu/projects/serving/tensorflow_serving/model_servers/BUILD:181:1: error executing shell command: 'bazel-out/host/bin/external/bazel_tools/tools/build_defs/pkg/build_tar --flagfile=bazel-out/local-py3-fastbuild/bin/tensorflow_serving/model_servers/tensorflow_model_server_tar.args' failed: bash failed: error executing command /bin/bash -c 'bazel-out/host/bin/external/bazel_tools/tools/build_defs/pkg/build_tar --flagfile=bazel-out/local-py3-fastbuild/bin/tensorflow_serving/model_servers/tensorflow_model_server_tar.args': com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Traceback (most recent call last):
  File "/home/fengyu/.cache/bazel/_bazel_fengyu/49d694a6bdfd6ccee39cb10c46d42915/execroot/tf_serving/bazel-out/host/bin/external/bazel_tools/tools/build_defs/pkg/build_tar.runfiles/tf_serving/../bazel_tools/tools/build_defs/pkg/build_tar.py", line 23, in <module>
    from third_party.py import gflags
  File "/home/fengyu/.cache/bazel/_bazel_fengyu/49d694a6bdfd6ccee39cb10c46d42915/execroot/tf_serving/bazel-out/host/bin/external/bazel_tools/tools/build_defs/pkg/build_tar.runfiles/bazel_tools/third_party/py/gflags/__init__.py", line 1091
    except gflags_validators.Error, e:
                                  ^
SyntaxError: invalid syntax
INFO: Elapsed time: 2691.501s, Critical Path: 140.28s
```

**Comment by abcfy2** [comment]
Maybe this issue relate to https://github.com/bazelbuild/bazel/issues/1580

**Comment by gautamvasudevan** [comment]
Closing due to staleness.
