### ISSUE TITLE
[Question] Storage path source from S3

### ISSUE THREAD

**Issue by quantumlicht** [tensorflow/serving#615]
Hello a "recent" pull request has introduce `s3_file_system` in the tensorflow codebase.

I'd like to know if that means that I can load models directly from S3 rather that from local filesystem?

I tried compiling tf-serving with the master branch of tensorflow to make sure that the s3 filesystem would be included. It does not seem to work for me right now. 

Here's an excerpt of my `model_config.txt` file 
``` 
config: {
    name: "other-model",
    base_path: "/models/othermodel",
    model_platform: "tensorflow",
    model_version_policy: {
       all: {}
    }
  },
  config: {
    name: "s3-model",
    base_path: "s3://mybucket/key/",
    model_platform: "tensorflow",
    model_version_policy: {
       all: {}
    }
  },
```

Unfortunately, when I running tensorflow_model_server the error that is reported is ` FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3://mybucket/key for servable s3-model

It's not clear if this error comes from a configuration error, or possibly that the filesystem is not correctly registered because the error
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/env.cc#L137

would be swallowed here:
https://github.com/tensorflow/serving/blob/master/tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc#L222

**Comment by kirilg** [comment]
The model server itself could probably make use of the newly added S3 functionality, but I'm not familiar with those recent changes and we didn't test it.

One thing you can try is to add the new build target as a dep like we do with gcs and hadoop [here](https://github.com/tensorflow/serving/blob/d8c33a33a276f4d3704f12ad8952cc272df53822/tensorflow_serving/model_servers/BUILD#L137). Maybe add "@org_tensorflow//tensorflow/contrib/s3:s3_file_system",
there and try again.

**Comment by quantumlicht** [comment]
I tried adding `@org_tensorflow//tensorflow/contrib/s3:s3_file_system` like you suggested. However now it complains when I rebuild with:
` bazel build -s -c opt --verbose_failures tensorflow_serving/...`
```
/root/.cache/bazel/_bazel_root/f8d1071c69ea316497c31e40fe01608c/external/org_tensorflow/tensorflow/contrib/s3/BUILD:69:1: error loading package '@aws//': Extension file not found. Unable to load package for '//third_party:common.bzl': BUILD file not found on package path and referenced by '@org_tensorflow//tensorflow/contrib/s3:s3_file_system'.
```

**Comment by kirilg** [comment]
I found the problem.
It seems the way the aws target is declared in TF's workspace.bzl doesn't work properly for submodules. I just sent a fix but in the meantime you can patch it in locally by adding the line
`"repository = tf_repo_name,"`
to https://github.com/tensorflow/tensorflow/blob/master/tensorflow/workspace.bzl#L662 (under the tensorflow submodule in your workspace)

**Comment by coldsheephot** [comment]
@kirilg I tested your solution and it works well!
@yongtang Hope it be merged to the tensorflow master.
Thanks!

**Comment by quantumlicht** [comment]
Thanks a lot! Is this fix shown on github? I'd like to monitor when it's going to get merged

**Comment by quantumlicht** [comment]
@coldsheephot Were you able to serve models fetch from s3 using a model_config file like I described in my original question?

**Comment by quantumlicht** [comment]
I guess this error:
FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3://my-bucket/key for servable s3-model

**Comment by quantumlicht** [comment]
Here are the environment variable that I used:
S3_REGION=us-east-1
S3_USE_HTTPS=0
S3_VERIFY_SSL=0

**Comment by yongtang** [comment]
Thanks @kirilg for the fix!

**Comment by calhamdower** [comment]
Im not sure this should be closed, as the above error also occurs for me:

`FileSystemStoragePathSource encountered a file-system access error: Could not find base path s3://my-bucket/key for servable s3-model`

has anyone had success with this?

**Comment by quantumlicht** [comment]
Yeah I am not sure if the error is because the file system is not registered, or because my S3 configuration is not correct. I have no idea how to go about debugging this.

**Comment by kirilg** [comment]
This issue was automatically closed when tensorflow/tensorflow@c4fd236 was submitted because it had a commit description "Fixes tensorflow/serving#615". We still have to sync the TF submodule before the fix is applied to TF Serving, so I'll reopen the issue. We'll sync the submodule in our next push this week, and in the meantime you can try syncing TF locally to see if it works for you:
```
cd tensorflow
git pull
git checkout master
./configure
cd ..
```

**Comment by quantumlicht** [comment]
I got the following error when running `bazel build -c opt tensorflow_serving/...`
I used the default settings for `./configure`
```
ERROR: /Users/dev/serving/tensorflow_serving/model_servers/BUILD:184:1: error executing shell command: 'bazel-out/host/bin/external/bazel_tools/tools/build_defs/pkg/build_tar --flagfile=bazel-out/local-opt/bin/tensorflow_serving/model_servers/tensorflow_model_server_tar.args' failed (Exit 1).
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_philippeguay/861d2ea172d6dc393ffe24a89a8f88df/execroot/tf_serving/bazel-out/host/bin/external/bazel_tools/tools/build_defs/pkg/build_tar.runfiles/tf_serving/../bazel_tools/tools/build_defs/pkg/build_tar.py", line 23, in <module>
    from third_party.py import gflags
  File "/private/var/tmp/_bazel_philippeguay/861d2ea172d6dc393ffe24a89a8f88df/execroot/tf_serving/bazel-out/host/bin/external/bazel_tools/tools/build_defs/pkg/build_tar.runfiles/bazel_tools/third_party/py/gflags/__init__.py", line 1, in <module>
    from gflags import *
ModuleNotFoundError: No module named 'gflags'
```

**Comment by calhamdower** [comment]
I got this going, woo.
I had already checked out r1.4.0-rc1 so I applied the "repository = tf_repo_name," fix to it compiled and it worked

I would say this is essentially the same as @kirilg mentioned above.

@quantumlicht  I would suggest building your tensorflow as a pip package as in:
https://www.tensorflow.org/install/install_sources
and then running 
`import tensorflow as tf
with tf.gfile.Open("s3://someKnownbucket/test.txt") as w:
    abc = w.size()`
-if thats not ok than its probably your environment variables... check your envVars of the key/id AND region of the docs you are trying to get. At least from this you'll know that your TF pull is AOK and S3 working.

**Comment by quantumlicht** [comment]
@calhamdower Thanks for that. I rebuilt tensorflow as a package like you mentionned.

What command did you use to build tensorflow serving?

**Comment by calhamdower** [comment]
`bazel build -s -c opt --define with_s3_support=true //tensorflow_serving/model_servers:tensorflow_model_server`

you shouldnt need the --define with_s3_support=true if the configure was done properly, but I had it in there anyway, just to be sure.

I think this can probably be closed once someone updates the tensorflow submodule and does a quick check that it works on a clean pull @kirilg, let me know when the sub-module is updated and I can check.

**Comment by kirilg** [comment]
The submodule was synced and the new s3 build dep was added to tensorflow_model_server. S3 should be supported now as long as you configure TF with s3.

**Comment by sirotenko** [comment]
Did anyone get it to work?
When I'm running it with the master version of TFS my output gets flooded by the same repeating messages:
```
2018-01-12 00:15:13.709741: I external/org_tensorflow/tensorflow/core/platform/s3/aws_logging.cc:53] Initializing Curl library
2018-01-12 00:15:13.723562: I tensorflow_serving/model_servers/server_core.cc:439] Adding/updating models.
2018-01-12 00:15:13.723620: I tensorflow_serving/model_servers/server_core.cc:494]  (Re-)adding model: s3-model
2018-01-12 00:15:13.723891: I external/org_tensorflow/tensorflow/core/platform/s3/aws_logging.cc:53] Initializing config loader against fileName /root//.aws/config and using profilePrefix = 1
2018-01-12 00:15:13.723964: I external/org_tensorflow/tensorflow/core/platform/s3/aws_logging.cc:53] Initializing config loader against fileName /root//.aws/credentials and using profilePrefix = 0
2018-01-12 00:15:13.724001: I external/org_tensorflow/tensorflow/core/platform/s3/aws_logging.cc:53] Setting provider to read credentials from /root//.aws/credentials for credentials file and /root//.aws/config for the config file , for use with profile default
2018-01-12 00:15:13.724039: I external/org_tensorflow/tensorflow/core/platform/s3/aws_logging.cc:53] Creating HttpClient with max connections2 and scheme http
2018-01-12 00:15:13.724074: I external/org_tensorflow/tensorflow/core/platform/s3/aws_logging.cc:53] Initializing CurlHandleContainer with size 2
2018-01-12 00:15:13.724102: I external/org_tensorflow/tensorflow/core/platform/s3/aws_logging.cc:53] Creating Instance with default EC2MetadataClient and refresh rate 900000
2018-01-12 00:15:13.724149: I external/org_tensorflow/tensorflow/core/platform/s3/aws_logging.cc:53] Found secret key
2018-01-12 00:15:13.724247: I external/org_tensorflow/tensorflow/core/platform/s3/aws_logging.cc:53] Initializing CurlHandleContainer with size 25
2018-01-12 00:15:13.724338: I external/org_tensorflow/tensorflow/core/platform/s3/aws_logging.cc:53] Found secret key
2018-01-12 00:15:13.724543: I external/org_tensorflow/tensorflow/core/platform/s3/aws_logging.cc:53] Pool grown by 2
2018-01-12 00:15:13.724580: I external/org_tensorflow/tensorflow/core/platform/s3/aws_logging.cc:53] Connection has been released. Continuing.
2018-01-12 00:15:13.855672: E external/org_tensorflow/tensorflow/core/platform/s3/aws_logging.cc:59] No response body. Response code: 404
2018-01-12 00:15:13.855763: W external/org_tensorflow/tensorflow/core/platform/s3/aws_logging.cc:56] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
```
And I've tested tf S3 operation with tf.stat. Works fine. Also if I change s3 path to some inexisting path I get a clear error message that such path not found.

**Comment by quantumlicht** [comment]
@sirotenko I was able to make it work. The `No response body. Response code: 404` error is suspicious. I would try to use the S3 cli to try `aws s3 ls s3://your-bucket`  I am suspecting that maybe your key does not have access to read your bucket.

**Comment by sirotenko** [comment]
@quantumlicht thanks for response
I also thought it is suspicious. But seems like its normal for directories. If I run test command from [this thread](https://github.com/tensorflow/tensorflow/issues/15159#issuecomment-349749663)
```
python -c "from tensorflow.python.lib.io import file_io; file_io.stat('s3://datasets.elasticmapreduce/ngrams/books/20090715/eng-1M/1gram/data')"
```
I'm **not** getting 404
But if I remove data from the tail and run it like this
```
python -c "from tensorflow.python.lib.io import file_io; file_io.stat('s3://datasets.elasticmapreduce/ngrams/books/20090715/eng-1M/1gram/')"
```
then here's what I'm getting:
```
2018-01-12 01:33:38.118706: I tensorflow/core/platform/s3/aws_logging.cc:53] Initializing Curl library
2018-01-12 01:33:38.449207: I tensorflow/core/platform/s3/aws_logging.cc:53] Initializing config loader against fileName /root//.aws/config and using profilePrefix = 1
2018-01-12 01:33:38.449258: I tensorflow/core/platform/s3/aws_logging.cc:53] Initializing config loader against fileName /root//.aws/credentials and using profilePrefix = 0
2018-01-12 01:33:38.449273: I tensorflow/core/platform/s3/aws_logging.cc:53] Setting provider to read credentials from /root//.aws/credentials for credentials file and /root//.aws/config for the config file , for use with profile default
2018-01-12 01:33:38.449288: I tensorflow/core/platform/s3/aws_logging.cc:53] Creating HttpClient with max connections2 and scheme http
2018-01-12 01:33:38.449304: I tensorflow/core/platform/s3/aws_logging.cc:53] Initializing CurlHandleContainer with size 2
2018-01-12 01:33:38.449320: I tensorflow/core/platform/s3/aws_logging.cc:53] Creating Instance with default EC2MetadataClient and refresh rate 900000
2018-01-12 01:33:38.449339: I tensorflow/core/platform/s3/aws_logging.cc:53] Found secret key
2018-01-12 01:33:38.449379: I tensorflow/core/platform/s3/aws_logging.cc:53] Initializing CurlHandleContainer with size 25
2018-01-12 01:33:38.449420: I tensorflow/core/platform/s3/aws_logging.cc:53] Found secret key
2018-01-12 01:33:38.449577: I tensorflow/core/platform/s3/aws_logging.cc:53] Pool grown by 2
2018-01-12 01:33:38.449597: I tensorflow/core/platform/s3/aws_logging.cc:53] Connection has been released. Continuing.
2018-01-12 01:33:38.579174: E tensorflow/core/platform/s3/aws_logging.cc:59] No response body. Response code: 404
2018-01-12 01:33:38.579276: W tensorflow/core/platform/s3/aws_logging.cc:56] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
2018-01-12 01:33:38.579397: I tensorflow/core/platform/s3/aws_logging.cc:53] Found secret key
2018-01-12 01:33:38.579593: I tensorflow/core/platform/s3/aws_logging.cc:53] Connection has been released. Continuing.
2018-01-12 01:33:38.626006: I tensorflow/core/platform/s3/aws_logging.cc:53] Cleaning up CurlHandleContainer.
2018-01-12 01:33:38.626080: I tensorflow/core/platform/s3/aws_logging.cc:53] Cleaning up CurlHandleContainer.
```
Notice the 404 in the output.
Another confirmation that TF can actually read my bucket is that if I change it to non-existing one, I'm getting 
```
tensorflow.python.framework.errors_impl.NotFoundError: Object s3://<my bucket and key> does not exist
```
In which format do you store models? Something like s3://buket/key/1/saved_model.pb and variables/ ?

**Comment by quantumlicht** [comment]
In that case you need to load from s3://bucket/key

Le 11 janv. 2018 20 h 36, "Mikhail Sirotenko" <notifications@github.com> a
écrit :

**Comment by sirotenko** [comment]
Yes, that is how I'm trying to load it

**Comment by sirotenko** [comment]
So I finally get it to work by checking out version 1.4.0 and applying patch suggested by @kirilg 
This makes me think that master (c1ec43508ee57a5d6269116aba82d2a16d383c8a) is broken in terms of S3 support

**Comment by joergkiesewetter** [comment]
hmm, not working completely.  When I specify a model on S3, it get's downloaded and loaded into the server. But the logs are a bit strange.

When I start to load the model, I get a lot of these log-messages:
```
2018-02-27 17:18:59.263552: E external/org_tensorflow/tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 404
2018-02-27 17:18:59.263631: W external/org_tensorflow/tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
2018-02-27 17:18:59.263811: I external/org_tensorflow/tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2018-02-27 17:18:59.295518: I external/org_tensorflow/tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2018-02-27 17:18:59.440845: I external/org_tensorflow/tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2018-02-27 17:18:59.860468: I external/org_tensorflow/tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2018-02-27 17:19:00.240998: I external/org_tensorflow/tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
```

These message are comming as long as the download is running. When the download finishes, there are some other messages:

```
2018-02-27 17:19:01.619719: W external/org_tensorflow/tensorflow/core/platform/s3/aws_logging.cc:57] Encountered Unknown AWSError
InvalidRange
The requested range is not satisfiable:
2018-02-27 17:19:01.944491: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:159] Restoring SavedModel bundle.
2018-02-27 17:19:01.997779: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:169] The specified SavedModel has no variables; no checkpoints were restored.
2018-02-27 17:19:01.997893: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:194] Running LegacyInitOp on SavedModel bundle.
2018-02-27 17:19:02.032605: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:289] SavedModel load for tags { serve }; Status: success. Took 150985551 microseconds.
2018-02-27 17:19:02.467961: I tensorflow_serving/core/loader_harness.cc:86] Successfully loaded servable version {name: model_5_1 version: 1}
```

after that,  the first log-messages are still comming in, but only with 3 lines of 'Connection has been released. Continuing`. The good thing is, the model is loaded and can be queried. The bad thing is, i'm still getting theses 5 lines of log messages every second:

```
2018-02-27 17:19:05.241682: I external/org_tensorflow/tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2018-02-27 17:19:05.267068: E external/org_tensorflow/tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 404
2018-02-27 17:19:05.267207: W external/org_tensorflow/tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer.
2018-02-27 17:19:05.267363: I external/org_tensorflow/tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
2018-02-27 17:19:05.295475: I external/org_tensorflow/tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing.
```

p.s. i'm using the latest commit (f0b3a41)

**Comment by mbelang** [comment]
Any news on this. I'm using latest version of Tensorflow and I have those annoying logs: 

```
[tensorflow-server-pr-14-585f869b5f-2wln8] 2018-08-27 13:51:41.183378: I external/org_tensorflow/tensorflow/core/platform/s3/aws_logging.cc:54] Found secret key 
[tensorflow-server-pr-14-585f869b5f-2wln8] 2018-08-27 13:51:41.183471: I external/org_tensorflow/tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing. 
[tensorflow-server-pr-14-585f869b5f-2wln8] 2018-08-27 13:51:41.194855: I external/org_tensorflow/tensorflow/core/platform/s3/aws_logging.cc:54] Found secret key 
[tensorflow-server-pr-14-585f869b5f-2wln8] 2018-08-27 13:51:41.194963: I external/org_tensorflow/tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing. 
[tensorflow-server-pr-14-585f869b5f-2wln8] 2018-08-27 13:51:41.206484: I external/org_tensorflow/tensorflow/core/platform/s3/aws_logging.cc:54] Found secret key 
[tensorflow-server-pr-14-585f869b5f-2wln8] 2018-08-27 13:51:41.206714: I external/org_tensorflow/tensorflow/core/platform/s3/aws_logging.cc:54] Connection has been released. Continuing. 
[tensorflow-server-pr-14-585f869b5f-2wln8] 2018-08-27 13:51:41.212817: E external/org_tensorflow/tensorflow/core/platform/s3/aws_logging.cc:60] No response body. Response code: 404 
[tensorflow-server-pr-14-585f869b5f-2wln8] 2018-08-27 13:51:41.212852: W external/org_tensorflow/tensorflow/core/platform/s3/aws_logging.cc:57] If the signature check failed. This could be because of a time skew. Attempting to adjust the signer. 
```

The server is working as expected though. I set the log level to ERROR only but still the `404` error is happening more than every second.

**Comment by orf** [comment]
I'm also getting this, it's impossible to diagnose where the 404's are coming from.

**Comment by davidvuong** [comment]
It's 2020 and I'm still seeing these messages but everything else works. For reference, I'm using the TFS docker image:

```
tensorflow/serving:2.1.0-gpu
```

and the arguments I'm passing are:

```
[
  "--port=8500",
  "--model_config_file=s3://your-s3-bucket/model.config",
  "--enable_batching",
  "--file_system_poll_wait_seconds=90",
]
```

This is running inside EKS where the underlying instance has roles to read/write to S3.

**Comment by waryak** [comment]
@davidvuong either me in 2021:D
Can't find specifications on how to store the model in s3 and explanations on what does BASE_PATH and MODEL_NAME vars mean... Just guessing...
