### ISSUE TITLE
package contains errors: crosstool.

### ISSUE THREAD

**Issue by auroua** [tensorflow/serving#636]
When I execute the command
```
bazel query 'kind(rule, @local_config_cuda//...)' --output label_kind
```
I got the following errors:
```
aurora@aurora:~/workspaces/PycharmProjects/tensorflow/serving/tensorflow$ bazel query 'kind(rule, @local_config_cuda//...)' --output label_kind
......
ERROR: /home/aurora/.cache/bazel/_bazel_aurora/c781d3b689f203e5220ff82dfc044d5e/external/local_config_cuda/crosstool/BUILD:4:1: Traceback (most recent call last):
	File "/home/aurora/.cache/bazel/_bazel_aurora/c781d3b689f203e5220ff82dfc044d5e/external/local_config_cuda/crosstool/BUILD", line 4
		error_gpu_disabled()
	File "/home/aurora/.cache/bazel/_bazel_aurora/c781d3b689f203e5220ff82dfc044d5e/external/local_config_cuda/crosstool/error_gpu_disabled.bzl", line 3, in error_gpu_disabled
		fail("ERROR: Building with --config=c...")
ERROR: Building with --config=cuda but TensorFlow is not configured to build with GPU support. Please re-run ./configure and enter 'Y' at the prompt to build with GPU support.
ERROR: package contains errors: crosstool.
ERROR: error loading package '@local_config_cuda//crosstool': Package 'crosstool' contains errors.
```
When I execute `.configure`, I indeed choose the cuda support.
I have build two or three different versions of tensorflow serving, but never success :cry: . 
How could I solve this problem? Thanks!

**Comment by gautamvasudevan** [comment]
Closing - please see the latest [Docker examples](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/docker.md) for bringing up a build environment.
