### ISSUE TITLE
GetModelMetadata grpc request returns connect failed

### ISSUE THREAD

**Issue by mvsusp** [tensorflow/serving#715]
I use GetModelMetadata to extract signature name of my deploy model in TF serving in that usually works fine.

I have a model that whenever I request the metadata returns ```AbortionError: AbortionError(code=StatusCode.UNAVAILABLE, details="Connect Failed")```.

The logs showing the TF serving loading the model but failing the request metadata call are below:
```bash
2018-01-04 20:32:02.640925: I tensorflow_serving/model_servers/main.cc:147] Building single TensorFlow model file config:  model_name: generic_model model_base_path: /opt/ml/model/export/Servo
2018-01-04 20:32:02.641860: I tensorflow_serving/model_servers/server_core.cc:441] Adding/updating models.
2018-01-04 20:32:02.642003: I tensorflow_serving/model_servers/server_core.cc:492]  (Re-)adding model: generic_model
2018-01-04 20:32:02.760564: I tensorflow_serving/core/basic_manager.cc:705] Successfully reserved resources to load servable {name: generic_model version: 1514865559}
2018-01-04 20:32:02.760743: I tensorflow_serving/core/loader_harness.cc:66] Approving load for servable version {name: generic_model version: 1514865559}
2018-01-04 20:32:02.760849: I tensorflow_serving/core/loader_harness.cc:74] Loading servable version {name: generic_model version: 1514865559}
2018-01-04 20:32:02.761161: I external/org_tensorflow/tensorflow/contrib/session_bundle/bundle_shim.cc:360] Attempting to load native SavedModelBundle in bundle-shim from: /opt/ml/model/export/Servo/1514865559
2018-01-04 20:32:02.762075: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:236] Loading SavedModel from: /opt/ml/model/export/Servo/1514865559
2018-01-04 20:32:02.842259: I external/org_tensorflow/tensorflow/cc/saved_model/loader.cc:155] Restoring SavedModel bundle.
[2018-01-04 20:33:36 +0000] [20] [ERROR] Exception in worker process
Traceback (most recent call last):
     result = stub.GetModelMetadata(request, self.request_timeout)
   File "/usr/local/lib/python2.7/dist-packages/grpc/beta/_client_adaptations.py", line 309, in __call__
     self._request_serializer, self._response_deserializer)
   File "/usr/local/lib/python2.7/dist-packages/grpc/beta/_client_adaptations.py", line 195, in _blocking_unary_unary
     raise _abortion_error(rpc_error_call)
 AbortionError: AbortionError(code=StatusCode.UNAVAILABLE, details="Connect Failed")
```

I understand that saved_model.pb may be missing something and that is why TF serving is failing. I compared it with another saved_model.pb that works and could not find anything different. 

I activate verbose logs as well, both using the flag ```tensorflow_model_server -v=1``` and env variable ```TF_CPP_MIN_VLOG_LEVEL=1```. I can see verbose logging when the server starts but nothing additional when it fails.

Is there a way that I can see why that get model metadata is failing in the server? Are there cases where this call should not work with a model?

Thanks

**Comment by chrisolston** [comment]
Based on the logs, it looks like the model load may still be in progress when the rpc request gets handled. I see "Loading servable ..." but not "Successfully loaded servable ..." (those log messages are from loader_harness.cc).

**Comment by mvsusp** [comment]
Thanks @chrisolston 

That is true. I noticed that the tf serving finishes loading the other models with the log:
```bash
2018-01-05 13:15:09.421180: I tensorflow_serving/core/loader_harness.cc:86] Successfully loaded servable version {name: generic_model version: 1513210401}
E0105 13:15:09.422131221      32 ev_epoll1_linux.c:1051]     grpc epoll fd: 3
2018-01-05 13:15:09.423263: I tensorflow_serving/model_servers/main.cc:288] Running ModelServer at 0.0.0.0:9000 ..
```

but this model never finishes loading. Looking at the logs after 10 minutes loading, the messages are:

```bash
algo-1_1  | 2018-01-05 13:18:49.844511: I external/org_tensorflow/tensorflow/core/framework/log_memory.cc:35] __LOG_MEMORY__ MemoryLogTensorOutput { step_id: 1 kernel_name: "save_1/Assign_19" tensor { dtype: DT_FLOAT shape { dim { size: 2048 } dim { size: 1024 } } allocation_description { requested_bytes: 8388608 allocator_name: "cpu" ptr: 140608614171008 } } }
algo-1_1  | 2018-01-05 13:18:49.844794: I external/org_tensorflow/tensorflow/core/framework/log_memory.cc:35] __LOG_MEMORY__ MemoryLogTensorDeallocation { allocator_name: "cpu" }
algo-1_1  | 2018-01-05 13:18:49.845886: I external/org_tensorflow/tensorflow/core/common_runtime/executor.cc:1557] Process node: 98 step 1 save_1/RestoreV2_18 = RestoreV2[_output_shapes=[<unknown>], dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save_1/Const_0_0, save_1/RestoreV2_18/tensor_names, save_1/RestoreV2_18/shape_and_slices) is dead: 0
algo-1_1  | 2018-01-05 13:18:49.854896: I external/org_tensorflow/tensorflow/core/framework/log_memory.cc:35] __LOG_MEMORY__ MemoryLogTensorAllocation { step_id: 1 kernel_name: "save_1/RestoreV2_18" tensor { dtype: DT_FLOAT shape { dim { size: 523698 } dim { size: 1024 } } allocation_description { requested_bytes: 2145067008 allocator_name: "cpu" ptr: 140606427156544 } } }
algo-1_1  | 2018-01-05 13:18:50.300250: I tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:390] File-system polling update: Servable:{name: generic_model version: 1514865559}; Servable path: /opt/ml/model/export/Servo/1514865559; Polling frequency: 1
algo-1_1  | 2018-01-05 13:18:50.300506: I tensorflow_serving/core/aspired_versions_manager.cc:235] Enqueueing aspired versions request: {name: generic_model version: 1514865559}
algo-1_1  | 2018-01-05 13:18:50.392926: I tensorflow_serving/core/aspired_versions_manager.cc:245] Processing aspired versions request: {name: generic_model version: 1514865559}
algo-1_1  | 2018-01-05 13:18:51.305212: I tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:390] File-system polling update: Servable:{name: generic_model version: 1514865559}; Servable path: /opt/ml/model/export/Servo/1514865559; Polling frequency: 1
algo-1_1  | 2018-01-05 13:18:51.307873: I tensorflow_serving/core/aspired_versions_manager.cc:235] Enqueueing aspired versions request: {name: generic_model version: 1514865559}
algo-1_1  | 2018-01-05 13:18:51.397209: I tensorflow_serving/core/aspired_versions_manager.cc:245] Processing aspired versions request: {name: generic_model version: 1514865559}
algo-1_1  | 2018-01-05 13:18:52.291040: I tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:390] File-system polling update: Servable:{name: generic_model version: 1514865559}; Servable path: /opt/ml/model/export/Servo/1514865559; Polling frequency: 1
algo-1_1  | 2018-01-05 13:18:52.291359: I tensorflow_serving/core/aspired_versions_manager.cc:235] Enqueueing aspired versions request: {name: generic_model version: 1514865559}
algo-1_1  | 2018-01-05 13:18:52.305222: I tensorflow_serving/core/aspired_versions_manager.cc:245] Processing aspired versions request: {name: generic_model version: 1514865559}
algo-1_1  | 2018-01-05 13:18:53.286431: I tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:390] File-system polling update: Servable:{name: generic_model version: 1514865559}; Servable path: /opt/ml/model/export/Servo/1514865559; Polling frequency: 1
algo-1_1  | 2018-01-05 13:18:53.286736: I tensorflow_serving/core/aspired_versions_manager.cc:235] Enqueueing aspired versions request: {name: generic_model version: 1514865559}
algo-1_1  | 2018-01-05 13:18:53.311147: I tensorflow_serving/core/aspired_versions_manager.cc:245] Processing aspired versions request: {name: generic_model version: 1514865559}
algo-1_1  | 2018-01-05 13:18:54.289559: I tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:390] File-system polling update: Servable:{name: generic_model version: 1514865559}; Servable path: /opt/ml/model/export/Servo/1514865559; Polling frequency: 1
algo-1_1  | 2018-01-05 13:18:54.290750: I tensorflow_serving/core/aspired_versions_manager.cc:235] Enqueueing aspired versions request: {name: generic_model version: 1514865559}
algo-1_1  | 2018-01-05 13:18:54.317354: I tensorflow_serving/core/aspired_versions_manager.cc:245] Processing aspired versions request: {name: generic_model version: 1514865559}
algo-1_1  | 2018-01-05 13:18:55.294702: I tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:390] File-system polling update: Servable:{name: generic_model version: 1514865559}; Servable path: /opt/ml/model/export/Servo/1514865559; Polling frequency: 1
algo-1_1  | 2018-01-05 13:18:55.294795: I tensorflow_serving/core/aspired_versions_manager.cc:235] Enqueueing aspired versions request: {name: generic_model version: 1514865559}
algo-1_1  | 2018-01-05 13:18:55.320977: I tensorflow_serving/core/aspired_versions_manager.cc:245] Processing aspired versions request: {name: generic_model version: 1514865559}
algo-1_1  | 2018-01-05 13:18:56.305001: I tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:390] File-system polling update: Servable:{name: generic_model version: 1514865559}; Servable path: /opt/ml/model/export/Servo/1514865559; Polling frequency: 1
algo-1_1  | 2018-01-05 13:18:56.311361: I tensorflow_serving/core/aspired_versions_manager.cc:235] Enqueueing aspired versions request: {name: generic_model version: 1514865559}
algo-1_1  | 2018-01-05 13:18:56.335515: I tensorflow_serving/core/aspired_versions_manager.cc:245] Processing aspired versions request: {name: generic_model version: 1514865559}
algo-1_1  | 2018-01-05 13:18:57.294109: I tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:390] File-system polling update: Servable:{name: generic_model version: 1514865559}; Servable path: /opt/ml/model/export/Servo/1514865559; Polling frequency: 1
algo-1_1  | 2018-01-05 13:18:57.294543: I tensorflow_serving/core/aspired_versions_manager.cc:235] Enqueueing aspired versions request: {name: generic_model version: 1514865559}
algo-1_1  | 2018-01-05 13:18:57.346831: I tensorflow_serving/core/aspired_versions_manager.cc:245] Processing aspired versions request: {name: generic_model version: 1514865559}
algo-1_1  | 2018-01-05 13:18:58.294286: I tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:390] File-system polling update: Servable:{name: generic_model version: 1514865559}; Servable path: /opt/ml/model/export/Servo/1514865559; Polling frequency: 1
algo-1_1  | 2018-01-05 13:18:58.294813: I tensorflow_serving/core/aspired_versions_manager.cc:235] Enqueueing aspired versions request: {name: generic_model version: 1514865559}
algo-1_1  | 2018-01-05 13:18:58.353694: I tensorflow_serving/core/aspired_versions_manager.cc:245] Processing aspired versions request: {name: generic_model version: 1514865559}
algo-1_1  | 2018-01-05 13:18:59.291980: I tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:390] File-system polling update: Servable:{name: generic_model version: 1514865559}; Servable path: /opt/ml/model/export/Servo/1514865559; Polling frequency: 1
algo-1_1  | 2018-01-05 13:18:59.292503: I tensorflow_serving/core/aspired_versions_manager.cc:235] Enqueueing aspired versions request: {name: generic_model version: 1514865559}
algo-1_1  | 2018-01-05 13:18:59.357724: I tensorflow_serving/core/aspired_versions_manager.cc:245] Processing aspired versions request: {name: generic_model version: 1514865559}
algo-1_1  | 2018-01-05 13:19:00.308769: I tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:390] File-system polling update: Servable:{name: generic_model version: 1514865559}; Servable path: /opt/ml/model/export/Servo/1514865559; Polling frequency: 1
algo-1_1  | 2018-01-05 13:19:00.426979: I tensorflow_serving/core/aspired_versions_manager.cc:235] Enqueueing aspired versions request: {name: generic_model version: 1514865559}
algo-1_1  | 2018-01-05 13:19:00.487783: I tensorflow_serving/core/aspired_versions_manager.cc:245] Processing aspired versions request: {name: generic_model version: 1514865559}
algo-1_1  | 2018-01-05 13:19:01.336396: I tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:390] File-system polling update: Servable:{name: generic_model version: 1514865559}; Servable path: /opt/ml/model/export/Servo/1514865559; Polling frequency: 1
algo-1_1  | 2018-01-05 13:19:01.516858: I tensorflow_serving/core/aspired_versions_manager.cc:235] Enqueueing aspired versions request: {name: generic_model version: 1514865559}
algo-1_1  | 2018-01-05 13:19:01.588901: I tensorflow_serving/core/aspired_versions_manager.cc:245] Processing aspired versions request: {name: generic_model version: 1514865559}
algo-1_1  | 2018-01-05 13:19:02.302260: I tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:390] File-system polling update: Servable:{name: generic_model version: 1514865559}; Servable path: /opt/ml/model/export/Servo/1514865559; Polling frequency: 1
algo-1_1  | 2018-01-05 13:19:02.333734: I tensorflow_serving/core/aspired_versions_manager.cc:235] Enqueueing aspired versions request: {name: generic_model version: 1514865559}
algo-1_1  | 2018-01-05 13:19:02.392203: I tensorflow_serving/core/aspired_versions_manager.cc:245] Processing aspired versions request: {name: generic_model version: 1514865559}
algo-1_1  | 2018-01-05 13:19:03.320245: I tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:390] File-system polling update: Servable:{name: generic_model version: 1514865559}; Servable path: /opt/ml/model/export/Servo/1514865559; Polling frequency: 1
algo-1_1  | 2018-01-05 13:19:03.364098: I tensorflow_serving/core/aspired_versions_manager.cc:235] Enqueueing aspired versions request: {name: generic_model version: 1514865559}
algo-1_1  | 2018-01-05 13:19:03.402735: I tensorflow_serving/core/aspired_versions_manager.cc:245] Processing aspired versions request: {name: generic_model version: 1514865559}
algo-1_1  | 2018-01-05 13:19:03.992294: I external/org_tensorflow/tensorflow/core/framework/log_memory.cc:35] __LOG_MEMORY__ MemoryLogTensorOutput { step_id: 1 kernel_name: "save_1/RestoreV2_18" tensor { dtype: DT_FLOAT shape { dim { size: 523698 } dim { size: 1024 } } allocation_description { requested_bytes: 2145067008 allocator_name: "cpu" ptr: 140606427156544 } } }
algo-1_1  | 2018-01-05 13:19:03.996010: I external/org_tensorflow/tensorflow/core/common_runtime/executor.cc:1557] Process node: 99 step 1 save_1/Assign_18 = Assign[T=DT_FLOAT, _class=["loc:@model/decoder/embedding_decoder"], _output_shapes=[[523698,1024]], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](model/decoder/embedding_decoder, save_1/RestoreV2_18) is dead: 0
algo-1_1  | 2018-01-05 13:19:03.998814: I external/org_tensorflow/tensorflow/core/framework/log_memory.cc:35] __LOG_MEMORY__ MemoryLogTensorAllocation { step_id: 1 kernel_name: "save_1/Assign_18" tensor { dtype: DT_FLOAT shape { dim { size: 523698 } dim { size: 1024 } } allocation_description { requested_bytes: 2145067008 allocator_name: "cpu" ptr: 140602137014336 } } }
algo-1_1  | 2018-01-05 13:19:04.295512: I tensorflow_serving/sources/storage_path/file_system_storage_path_source.cc:390] File-system polling update: Servable:{name: generic_model version: 1514865559}; Servable path: /opt/ml/model/export/Servo/1514865559; Polling frequency: 1
algo-1_1  | 2018-01-05 13:19:04.296354: I tensorflow_serving/core/aspired_versions_manager.cc:235] Enqueueing aspired versions request: {name: generic_model version: 1514865559}
algo-1_1  | 2018-01-05 13:19:04.312598: I tensorflow_serving/core/aspired_versions_manager.cc:245] Processing aspired versions request: {name: generic_model version: 1514865559}
```

TF serving is not logging anything anymore and the container resources seems to be fine:
```bash
$ docker stats
CONTAINER           CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O           PIDS
d38f14834ff3        0.00%               5.711MiB / 3.855GiB   0.14%               1.49kB / 0B         88.5MB / 110MB      7
```

Is there a way to debug why the model is failing to load?

**Comment by chrisolston** [comment]
Some models simply take a long time to load. Unfortunately it can be hard to debug the reason; you may need to add some logging inside the tensorflow layer to find out what it's doing.

(The "aspiring" log messages are normal and harmless, and don't mean it's retrying the load.)

**Comment by mvsusp** [comment]
@chrisolston 

It turns out that if memory available is less than the size of the model, TF Serving will load forever.

I solved this issue on my side by changing the instance but please consider throwing an exception if that scenario happens.

Thank you

**Comment by AswathKiruba** [comment]
@mvsusp  Hi, Could you please let me know how did and where did you set the flag tensorflow_model_server -v=1. Thanks in advance.
