### ISSUE TITLE
bazel-bin/tensorflow_serving/example/inception_saved_model --checkpoint_dir=inception-v3 --output_dir=/tmp/inception-export

### ISSUE THREAD

**Issue by hufangjian** [tensorflow/serving#737]
I am following the "Serving Inception Model with TensorFlow Serving and Kubernetes" tutorial from the tensorflow.org website. When I get to loading and exporting the model using
"root@5419fcb49ada:/# bazel-bin/tensorflow_serving/example/inception_saved_model --checkpoint_dir=inception-v3 --out
put_dir=/tmp/inception-export"

I get following error.
root@5419fcb49ada:/home/serving# bazel-bin/tensorflow_serving/example/inception_saved_model --checkpoint_dir=inception-v3 --output_dir=/tmp/inception-export
Traceback (most recent call last):
  File "/home/serving/bazel-bin/tensorflow_serving/example/inception_saved_model.runfiles/tf_serving/tensorflow_serving/example/inception_saved_model.py", line 202, in <module>
    tf.app.run()
  File "/home/serving/bazel-bin/tensorflow_serving/example/inception_saved_model.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "/home/serving/bazel-bin/tensorflow_serving/example/inception_saved_model.runfiles/tf_serving/tensorflow_serving/example/inception_saved_model.py", line 198, in main
    export()
  File "/home/serving/bazel-bin/tensorflow_serving/example/inception_saved_model.runfiles/tf_serving/tensorflow_serving/example/inception_saved_model.py", line 91, in export
    table = tf.contrib.lookup.index_to_string_table_from_tensor(class_tensor)
  File "/home/serving/bazel-bin/tensorflow_serving/example/inception_saved_model.runfiles/org_tensorflow/tensorflow/python/util/lazy_loader.py", line 53, in __getattr__
    module = self._load()
  File "/home/serving/bazel-bin/tensorflow_serving/example/inception_saved_model.runfiles/org_tensorflow/tensorflow/python/util/lazy_loader.py", line 42, in _load
    module = importlib.import_module(self.__name__)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/serving/bazel-bin/tensorflow_serving/example/inception_saved_model.runfiles/org_tensorflow/tensorflow/contrib/__init__.py", line 83, in <module>
    from tensorflow.contrib.eager.python import tfe as eager
  File "/home/serving/bazel-bin/tensorflow_serving/example/inception_saved_model.runfiles/org_tensorflow/tensorflow/contrib/eager/python/tfe.py", line 78, in <module>
    from tensorflow.contrib.eager.python.datasets import Iterator
  File "/home/serving/bazel-bin/tensorflow_serving/example/inception_saved_model.runfiles/org_tensorflow/tensorflow/contrib/eager/python/datasets.py", line 23, in <module>
    from tensorflow.contrib.data.python.ops import prefetching_ops
  File "/home/serving/bazel-bin/tensorflow_serving/example/inception_saved_model.runfiles/org_tensorflow/tensorflow/contrib/data/python/ops/prefetching_ops.py", line 25, in <module>
    resource_loader.get_path_to_datafile("../../_prefetching_ops.so"))
  File "/home/serving/bazel-bin/tensorflow_serving/example/inception_saved_model.runfiles/org_tensorflow/tensorflow/contrib/util/loader.py", line 55, in load_op_library
    ret = load_library.load_op_library(path)
  File "/home/serving/bazel-bin/tensorflow_serving/example/inception_saved_model.runfiles/org_tensorflow/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/home/serving/bazel-bin/tensorflow_serving/example/inception_saved_model.runfiles/org_tensorflow/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /home/serving/bazel-bin/tensorflow_serving/example/inception_saved_model.runfiles/org_tensorflow/tensorflow/contrib/data/python/ops/../../_prefetching
_ops.so: undefined symbol: _ZN6google8protobuf8internal9ArenaImpl10AddCleanupEPvPFvS3_E

**Comment by shygiants** [comment]
I have same issue.

**Comment by shygiants** [comment]
I've added a line to `tensorflow/contrib/data/BUILD` like the problem at #421 is solved.
```py
tf_custom_op_library(
    name = "_prefetching_ops.so",
    srcs = ["ops/prefetching_ops.cc"],
    deps = ["//tensorflow/contrib/data/kernels:prefetching_kernels",
            # This line
            "@protobuf_archive//:protobuf",
    ],
)
```

But, when I execute `bazel-bin/tensorflow_serving/example/inception_saved_model`, I get following error message.
```
$ bazel-bin/tensorflow_serving/example/inception_saved_model --checkpoint_dir=inception-v3 --output_dir=/tmp/inception-export
2018-01-28 15:48:38.040581: F external/org_tensorflow/tensorflow/core/framework/op.cc:54] Non-OK-status: RegisterAlreadyLocked(op_data_factory) status: Already exists: Op with name _Arg
Aborted (core dumped)
```

**Comment by sbyma** [comment]
I have the same issue with self-compiled v1.5.0. Does seem to be a link error as suggested by @shygiants , but yeah trying to link "@protobuf_archive//:protobuf" doesn't work. Who is the dev for contrib/data ?

**Comment by steveBetl** [comment]
I have the same problem. The full description of what I've tried is here on stackoverflow:
[Saving the default inception model using tensorflow serving in docker image
](https://stackoverflow.com/questions/48805197/saving-the-default-inception-model-using-tensorflow-serving-in-docker-image)

**Comment by sbyma** [comment]
Problem disappeared after I cleaned / expunged with Bazel, and reran `./configure`. But if you aren't building from source, then I don't know.

**Comment by steveBetl** [comment]
Thanks @sbyma 
Since I have been using the latest release of serving, there isn't even a `./configure` file to run. It was amazingly confusing trying to follow online tutorials.

In fact, my plan is to revert to the 1.4 release so that there *is* a ./configure file. This is trickier than it sounds, because just reverting doesn't cause the submodules - tensorflow in particular - to appear. You have to use git to init and update your submodules and make sure that they are at the right release too.

It's going to be so much fun.

**Comment by sbyma** [comment]
@steveBetl I wasn't using TF serving, just building and using TF proper. So I'm not sure that just reverting to serving v1.4 will work. But I suppose it doesn't hurt to try.

**Comment by Pokharaa** [comment]
Please view this tutorial.It might help you..
https://www.youtube.com/watch?v=SsaJJsRvwIs

**Comment by steveBetl** [comment]
@Pokharaa 
I've already tried to follow that tutorial. In fact, following that tutorial is how I ended up here. 
Your video assumes that you already have a saved model, so I figured I could just save one using inception_saved_model.py. Turns out, not so simple.

If you feel like putting together a similarly useful tutorial for how to save a model, I'd be very appreciative.

And thanks for the tutorial - I wouldn't have gotten this far without it.
Kind regards,

Steve

**Comment by Pokharaa** [comment]
Hello Steve,

If you are looking for how to save your own model using tensorflow then I think this tutorial would help you.Please refer it once and let me know.
https://www.youtube.com/watch?v=9l2lkQtinx4&t=17s

Regards,
Prarthana

**Comment by steveBetl** [comment]
@Pokharaa 
That looks like exactly what I need. I swear it didn't exist when I looked last time :)

**Comment by Pokharaa** [comment]
@steveBetl  
All the best :)

**Comment by RickVM** [comment]
Stumbled upon the same problem when following the inception tutorial from the docs.
https://www.tensorflow.org/serving/serving_inception

**Comment by Pokharaa** [comment]
Hi RickVM,
Did you see this tutorial?
I know its quite difficult to look but it may help to solve your problem.
