### ISSUE TITLE
Error running basic example - 'NoneType' object is not callable in client, exception in Thread-3

### ISSUE THREAD

**Issue by selimyoussry** [tensorflow/serving#769]
Hi all,

Specs:
* Ubuntu 17.04
* Running Python 3.6.4 (but getting same error with Python 2.7.14)
* Downloaded the .whl file for tensorflow-serving-api, and pasted it in my virtual environment's site packages, as suggested.

After following the tutorial, the last step (running the `mnist_client.py`) gives me this:

I run 
```
python mnist_client.py --num_tests=100 --server=localhost:9000
```

and get
```
Extracting /tmp/train-images-idx3-ubyte.gz
Extracting /tmp/train-labels-idx1-ubyte.gz
Extracting /tmp/t10k-images-idx3-ubyte.gz
Extracting /tmp/t10k-labels-idx1-ubyte.gz
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/selim/.pyenv/versions/3.6.4/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/selim/.pyenv/versions/3.6.4/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/selim/.pyenv/versions/tf-3.6.4/lib/python3.6/site-packages/grpc/_channel.py", line 701, in channel_spin
    completed_call = event.tag(event)
  File "/home/selim/.pyenv/versions/tf-3.6.4/lib/python3.6/site-packages/grpc/_channel.py", line 174, in handle_event
    callback()
  File "/home/selim/.pyenv/versions/tf-3.6.4/lib/python3.6/site-packages/grpc/_channel.py", line 313, in <lambda>
    self._state.callbacks.append(lambda: fn(self))
  File "/home/selim/.pyenv/versions/tf-3.6.4/lib/python3.6/site-packages/grpc/beta/_client_adaptations.py", line 124, in <lambda>
    self._future.add_done_callback(lambda ignored_callback: fn(self))
TypeError: 'NoneType' object is not callable
```

Please note that:
* I get the same error even if `tensorflow_model_server` is not running, so the error probably happens before calling the server
* In the file `mnist_client.py`, in the loop `for _ in range(num_tests)` in the `do_inference` function has time to do two iterations before the error is thrown.

Any idea?

Thank you very much!

**Comment by feitianxiang** [comment]
same issue,can somebody help?

**Comment by gautamvasudevan** [comment]
Try again with the latest (1.10.0) - we've moved away from gRPC beta.

**Comment by harshini-gadige** [comment]
@selimyoussry  - Hi, does this issue persists with the latest version ? If not, feel free to close this. Thanks !

**Comment by harshini-gadige** [comment]
Closing due to lack of activity.
