### ISSUE TITLE
inception_export.py with wrong path for checkpoint

### ISSUE THREAD

**Issue by photon3710** [tensorflow/serving#78]
The inception_export.py has set wrong path for loading the checkpoint.

edward@edward-All-Series:~/git/serving$ bazel-bin/tensorflow_serving/example/inception_export --checkpoint_dir=inception-v3 --export_dir=inception-export
Traceback (most recent call last):
  File "/home/edward/git/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/tf_serving/tensorflow_serving/example/inception_export.py", line 143, in <module>
    tf.app.run()
  File "/home/edward/git/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/tf_serving/external/tf/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "/home/edward/git/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/tf_serving/tensorflow_serving/example/inception_export.py", line 139, in main
    export()
  File "/home/edward/git/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/tf_serving/tensorflow_serving/example/inception_export.py", line 117, in export
    saver.restore(sess, full_path)
  File "/home/edward/git/serving/bazel-bin/tensorflow_serving/example/inception_export.runfiles/tf_serving/external/tf/tensorflow/python/training/saver.py", line 1088, in restore
    raise ValueError("Restore called with invalid save path %s" % save_path)
ValueError: Restore called with invalid save path inception-v3/inception-v3/model.ckpt-157585

**Comment by chrisolston** [comment]
Sorry for the bug. I've reproduced it and am working on a patch.

**Comment by chrisolston** [comment]
I've committed a change that I believe will fix this. Closing this issue. Please re-open if it did not get fixed.

**Comment by tomx** [comment]
It seems that directing the checkpoint_dir to any other area other than where it was originally saved causes an error. i.e. if my original output files where saved at /output and I later changed it to /output-run2 and pointed the checkpoint_dir to it while exporting, it would error like above.
