### ISSUE TITLE
IndexError: index 0 is out of bounds for axis 0 with size 0  [error on the example]

### ISSUE THREAD

**Issue by NetWilliam** [tensorflow/serving#839]
I built the docker image and ran the example, but met a problem when trying to train the example of mnist service model. 

Is there anybody know how to continue?
perhaps I should download some mnist labeled case to run the training?

docker file:
```
FROM ubuntu:16.04

MAINTAINER Jeremiah Harmsen <jeremiah@google.com>

ADD sources.list /etc/apt/

RUN apt-get update && apt-get install -y \
        build-essential \
        curl \
        git \
        libfreetype6-dev \
        libpng12-dev \
        libzmq3-dev \
        mlocate \
        pkg-config \
        python-dev \
        python-numpy \
        python-pip \
        software-properties-common \
        swig \
        zip \
        zlib1g-dev \
        libcurl3-dev \
        openjdk-8-jdk\
        openjdk-8-jre-headless \
        wget \
        && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set up grpc

RUN pip install mock grpcio

# Set up Bazel.

ENV BAZELRC /root/.bazelrc
# Install the most recent bazel release.
ENV BAZEL_VERSION 0.5.4
WORKDIR /
RUN mkdir /bazel && \
    cd /bazel && \
    curl -fSsL -O https://github.com/bazelbuild/bazel/releases/download/$BAZEL_VERSION/bazel-$BAZEL_VERSION-installer-linux-x86_64.sh && \
    curl -fSsL -o /bazel/LICENSE.txt https://raw.githubusercontent.com/bazelbuild/bazel/master/LICENSE && \
    chmod +x bazel-*.sh && \
    ./bazel-$BAZEL_VERSION-installer-linux-x86_64.sh && \
    cd / && \
    rm -f /bazel/bazel-$BAZEL_VERSION-installer-linux-x86_64.sh

CMD ["/bin/bash"]
```

error log:
```
root@25922c1d7caa:/serving# bazel-bin/tensorflow_serving/example/mnist_saved_model /tmp/mnist_model
Training model...
Extracting /tmp/train-images-idx3-ubyte.gz
Traceback (most recent call last):
  File "/serving/bazel-bin/tensorflow_serving/example/mnist_saved_model.runfiles/tf_serving/tensorflow_serving/example/mnist_saved_model.py", line 147, in <module>
    tf.app.run()
  File "/serving/bazel-bin/tensorflow_serving/example/mnist_saved_model.runfiles/org_tensorflow/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/serving/bazel-bin/tensorflow_serving/example/mnist_saved_model.runfiles/tf_serving/tensorflow_serving/example/mnist_saved_model.py", line 60, in main
    mnist = mnist_input_data.read_data_sets(FLAGS.work_dir, one_hot=True)
  File "/serving/tensorflow_serving/example/mnist_input_data.py", line 186, in read_data_sets
    train_images = extract_images(local_file)
  File "/serving/tensorflow_serving/example/mnist_input_data.py", line 58, in extract_images
    magic = _read32(bytestream)
  File "/serving/tensorflow_serving/example/mnist_input_data.py", line 51, in _read32
    return numpy.frombuffer(bytestream.read(4), dtype=dt)[0]
IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by NetWilliam** [comment]
for anyone comes here later, please refer to: https://github.com/bazelbuild/bazel/issues/587

**Comment by HITxuefeng** [comment]
Have you solved this problem? I have encountered the same mistake as you.if you solved this problem,i hope you can help me.Thank you.

**Comment by runzhliu** [comment]
@HITxuefeng I just found out that, the MNIST dataset is failed to be downloaded by some reasons, could be proxy or something else.
You could check it by `ls -l /tmp` to see the size of the dataset to confirm about that.
