### ISSUE TITLE
Tensorflow Serving under ubuntu cannot be built due to compiling error.

### ISSUE THREAD

**Issue by jiangcore** [tensorflow/serving#893]
I build TF Serving in Mac and Ubuntu. There are errors of compiling in both platform with bazel. Here is the error messages:

ERROR: /home/parallels/.cache/bazel/_bazel_parallels/4733c330f52817a3d8c4908cfc7adcf1/external/org_tensorflow/tensorflow/tools/api/generator/BUILD:27:1: Executing genrule @org_tensorflow//tensorflow/tools/api/generator:python_api_gen failed (Exit 1)
Traceback (most recent call last):
  File "/home/parallels/.cache/bazel/_bazel_parallels/4733c330f52817a3d8c4908cfc7adcf1/execroot/tf_serving/bazel-out/host/bin/external/org_tensorflow/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/tools/api/generator/create_python_api.py", line 26, in <module>
    from tensorflow import python  # pylint: disable=unused-import
  File "/home/parallels/.cache/bazel/_bazel_parallels/4733c330f52817a3d8c4908cfc7adcf1/execroot/tf_serving/bazel-out/host/bin/external/org_tensorflow/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 63, in <module>
    from tensorflow.python.framework.framework_lib import *  # pylint: disable=redefined-builtin
  File "/home/parallels/.cache/bazel/_bazel_parallels/4733c330f52817a3d8c4908cfc7adcf1/execroot/tf_serving/bazel-out/host/bin/external/org_tensorflow/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/python/framework/framework_lib.py", line 52, in <module>
    from tensorflow.python.framework.importer import import_graph_def
  File "/home/parallels/.cache/bazel/_bazel_parallels/4733c330f52817a3d8c4908cfc7adcf1/execroot/tf_serving/bazel-out/host/bin/external/org_tensorflow/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/python/framework/importer.py", line 32, in <module>
    from tensorflow.python.framework import function
  File "/home/parallels/.cache/bazel/_bazel_parallels/4733c330f52817a3d8c4908cfc7adcf1/execroot/tf_serving/bazel-out/host/bin/external/org_tensorflow/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/python/framework/function.py", line 37, in <module>
    from tensorflow.python.ops import variable_scope as vs
  File "/home/parallels/.cache/bazel/_bazel_parallels/4733c330f52817a3d8c4908cfc7adcf1/execroot/tf_serving/bazel-out/host/bin/external/org_tensorflow/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/python/ops/variable_scope.py", line 197, in <module>
    """
**AttributeError: 'int' object attribute '__doc__' is read-only**
INFO: Elapsed time: 36.955s, Critical Path: 3.42s
INFO: 3 processes, local.
FAILED: Build did NOT complete successfully

**Comment by jiangcore** [comment]
Change enum to enum34 by the following command:
pip install enum34
pip uninstall enum

**Comment by gautamvasudevan** [comment]
Closing - please see the latest [Docker examples](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/docker.md) for bringing up a build environment - these work in Ubuntu so you shouldn't have to translate much.
