### ISSUE TITLE
Unable to build tensorflow serving with bazel.

### ISSUE THREAD

**Issue by santoshchanveer** [tensorflow/serving#904]
Hi,
 i am serving my trained model to tensor-flow serving but getting following error while building the serving...
Here is the stack trace

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/megdap/.cache/bazel/_bazel_megdap/3d62d882a5019f9dc3eef89176996700/execroot/tf_serving/bazel-out/host/bin/external/org_tensorflow/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/tools/api/generator/create_python_api.py", line 26, in <module>
    from tensorflow import python  # pylint: disable=unused-import
  File "/home/megdap/.cache/bazel/_bazel_megdap/3d62d882a5019f9dc3eef89176996700/execroot/tf_serving/bazel-out/host/bin/external/org_tensorflow/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/megdap/.cache/bazel/_bazel_megdap/3d62d882a5019f9dc3eef89176996700/execroot/tf_serving/bazel-out/host/bin/external/org_tensorflow/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/megdap/.cache/bazel/_bazel_megdap/3d62d882a5019f9dc3eef89176996700/execroot/tf_serving/bazel-out/host/bin/external/org_tensorflow/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/megdap/.cache/bazel/_bazel_megdap/3d62d882a5019f9dc3eef89176996700/execroot/tf_serving/bazel-out/host/bin/external/org_tensorflow/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/megdap/.cache/bazel/_bazel_megdap/3d62d882a5019f9dc3eef89176996700/execroot/tf_serving/bazel-out/host/bin/external/org_tensorflow/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/anaconda/envs/py35/lib/python3.5/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/anaconda/envs/py35/lib/python3.5/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /home/megdap/.cache/bazel/_bazel_megdap/3d62d882a5019f9dc3eef89176996700/execroot/tf_serving/bazel-out/host/bin/external/org_tensorflow/tensorflow/tools/api/generator/create_python_api.runfiles/org_tensorflow/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: PyClass_Type

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
INFO: Elapsed time: 1458.854s, Critical Path: 66.41s
INFO: 3955 processes, local.
FAILED: Build did NOT complete successfully

**Comment by CLIsVeryOK** [comment]
I met the same problem, but I once succeed. maybe the reason is caused by the network in China.

**Comment by cchung100m** [comment]
Hi @santoshchanveer,

What's your bazel version? I suggest you can use bazel 0.11.0 again.

> https://github.com/bazelbuild/bazel/releases/tag/0.11.0

Hope helps,

**Comment by gautamvasudevan** [comment]
Building TF Serving is fairly non-trivial. Try using the docker image first - if you just need a working binary - (docker pull tensorflow/serving). Otherwise, you can build the image from [Dockerfile.devel](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/docker.md)

**Comment by cchung100m** [comment]
Hi @gautamvasudevan ,

Do you have experiences of querying model status? I am facing the tensorflow-serving-api GetModelStatus() failed problem. #938 Can you take a look on my issue if you are available?

Many thanks,

**Comment by gautamvasudevan** [comment]
It should be noted that building tf serving (much like tensorflow) is dependent on very specific library versions. Your best bet is to start with the [dockerfile](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/docker.md) and make sure you can build with that, and then migrate the steps to the environment of your choosing.

Optionally - you can choose to use the [debian package](https://www.tensorflow.org/serving/setup#installing_using_apt_get) or the [default docker container](https://hub.docker.com/r/tensorflow/serving/) with just the binary and save yourself the hassle of building it yourself if you don't have a specific need to do so.

**Comment by AswathKiruba** [comment]
Thanks @gautamvasudevan  for your comments. Could please help us with the #961  issue.

**Comment by haotianteng** [comment]
Hi @gautamvasudevan Our model have to use external packages which is not included in tensorflow/serving docker image, which causing a failure in building with bazel in docker, is there a easy way to solve it?

**Comment by gautamvasudevan** [comment]
You would probably make a customer docker image for your needs, and you could start with the development images.
