### ISSUE TITLE
Installation on CentOS 7.0

### ISSUE THREAD

**Issue by lkluo** [tensorflow/serving#930]
I got errors when trying to install tensorflow serving on CentOS7.0:
> ERROR: /root/.cache/bazel/_bazel_root/71fb59ccb20e34305f765068f873db73/external/com_google_absl/absl/time/BUILD.bazel:27:1: no such package '@com_googlesource_code_cctz//': The repository could not be resolved and referenced by '@com_google_absl//absl/time:time'
ERROR: /root/.cache/bazel/_bazel_root/71fb59ccb20e34305f765068f873db73/external/com_google_absl/absl/time/BUILD.bazel:27:1: no such package '@com_googlesource_code_cctz//': The repository could not be resolved and referenced by '@com_google_absl//absl/time:time'
ERROR: Analysis of target '//tensorflow_serving/util/net_http/server/public:http_server_api' failed; build aborted: no such package '@com_googlesource_code_cctz//': The repository could not be resolved

I followed the steps described in [https://www.tensorflow.org/serving/setup](url). It turned out the tensorflow folder was not cloned using
`git clone --recurse-submodules https://github.com/tensorflow/serving`
so I cloned that folder manually. I am using bazel 0.10.0.

I also followed [https://gist.github.com/jarutis/6c2934705298720ff92a1c10f6a009d4](url) with no luck (could be out of date). Any suggestions on the above errors or recommendations on the correct installation steps?

**Comment by lkluo** [comment]
Now the errors encountered:

> ERROR: /root/.cache/bazel/_bazel_root/71fb59ccb20e34305f765068f873db73/external/org_tensorflow/util/python/BUILD:5:1: no such package '@local_config_python//': Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/71fb59ccb20e34305f765068f873db73/external/org_tensorflow/third_party/py/python_configure.bzl", line 291
                _create_local_python_repository(repository_ctx)
        File "/root/.cache/bazel/_bazel_root/71fb59ccb20e34305f765068f873db73/external/org_tensorflow/third_party/py/python_configure.bzl", line 255, in _create_local_python_repository
                _get_numpy_include(repository_ctx, python_bin)
        File "/root/.cache/bazel/_bazel_root/71fb59ccb20e34305f765068f873db73/external/org_tensorflow/third_party/py/python_configure.bzl", line 239, in _get_numpy_include
                _execute(repository_ctx, [python_bin, "-c",..."], <2 more arguments>)
        File "/root/.cache/bazel/_bazel_root/71fb59ccb20e34305f765068f873db73/external/org_tensorflow/third_party/py/python_configure.bzl", line 54, in _execute
                _fail("\n".join([error_msg.strip() if ... ""]))
        File "/root/.cache/bazel/_bazel_root/71fb59ccb20e34305f765068f873db73/external/org_tensorflow/third_party/py/python_configure.bzl", line 27, in _fail
                fail(("%sPython Configuration Error:%...)))
Python Configuration Error: Problem getting numpy include path.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named numpy
Is numpy installed?
 and referenced by '@org_tensorflow//util/python:python_headers'
ERROR: Analysis of target '//tensorflow_serving/servables/tensorflow/testdata:export_bad_half_plus_two' failed; build aborted: Loading failed

**Comment by lkluo** [comment]
Now the errors are related to: https://github.com/tensorflow/serving/issues/906

**Comment by gautamvasudevan** [comment]
That should be resolved now. If you have further trouble, try looking at the dockerfiles published.
