### ISSUE TITLE
grpc.framework.interfaces.face.face.RemoteError

### ISSUE THREAD

**Issue by BennyTheSen** [tensorflow/serving#951]
I'm trying to do a classification task with a model I trained in Keras and converted to TF savedModel format.  I created an python app to do start the classification task of the tf model.
The API is currently deployed on local, and the POST request is done by postman.

The error message I'm getting:

> Traceback (most recent call last):
  File "/home/vagrant/Desktop/Masterarbeit/apiDir/venv/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/Desktop/Masterarbeit/apiDir/venv/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/vagrant/Desktop/Masterarbeit/apiDir/venv/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/Desktop/Masterarbeit/apiDir/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/vagrant/Desktop/Masterarbeit/apiDir/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vagrant/Desktop/Masterarbeit/apiDir/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vagrant/Desktop/Masterarbeit/apiDir/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vagrant/Desktop/Masterarbeit/apiDir/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/vagrant/Desktop/Masterarbeit/apiDir/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vagrant/Desktop/Masterarbeit/apiDir/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vagrant/Desktop/Masterarbeit/apiDir/app/app.py", line 103, in main
    return str(stub.Classify(request, 50))
  File "/home/vagrant/Desktop/Masterarbeit/apiDir/venv/lib/python3.6/site-packages/grpc/beta/_client_adaptations.py", line 309, in __call__
    self._request_serializer, self._response_deserializer)
  File "/home/vagrant/Desktop/Masterarbeit/apiDir/venv/lib/python3.6/site-packages/grpc/beta/_client_adaptations.py", line 195, in _blocking_unary_unary
    raise _abortion_error(rpc_error_call)
grpc.framework.interfaces.face.face.RemoteError: RemoteError(code=StatusCode.UNKNOWN, details="lame client channel")

My code:

```
import os
from grpc.beta import implementations
import tensorflow as tf
from tensorflow_serving.apis import predict_pb2
from tensorflow_serving.apis import prediction_service_pb2
import json 
import flask
import requests
from flask import Flask, globals, request, g
import numpy as np

app = Flask(__name__)

MODEL_NAME = str(os.getenv('MODEL_NAME', ''))
MODEL_SERVER_HOST = str(os.getenv('MODEL_SERVER_HOST', ''))
MODEL_SERVER_PORT = int(os.getenv('MODEL_SERVER_PORT', ''))
ROOT_CERT = str(os.getenv('ROOT_CERT', '')).replace('\\n', '\n')


def get_access_token():
    url = "https://s0018712070trial.authentication.eu10.hana.ondemand.com/oauth/token"
    querystring = {"grant_type": "client_credentials"}
    headers = {'authorization': "Basic  ..."}
    response = requests.request("POST", url, headers=headers, params=querystring)
    #print('Bearer ' + json.loads(response.text)['access_token'])
    return 'Bearer ' + json.loads(response.text)['access_token']


def metadata_transformer(metadata):
    additions = []
    token = get_access_token()
    additions.append(('authorization', token))
    return tuple(metadata) + tuple(additions)


@app.route('/', methods=['POST'])
def main():
    credentials = implementations.ssl_channel_credentials(root_certificates=ROOT_CERT)
    channel = implementations.secure_channel(MODEL_SERVER_HOST, MODEL_SERVER_PORT, credentials)
    stub = prediction_service_pb2.beta_create_PredictionService_stub(channel, metadata_transformer=metadata_transformer)

    # process the first file only
    data = np.matrix([0.06222425773739815, 0.08211926370859146, -0.060986146330833435, 0.13920938968658447, ....
                    ])

    # See prediction_service.proto for gRPC request/response details.
    # change input type and data shapes according to your model
    request = predict_pb2.PredictRequest()
    request.model_spec.name = MODEL_NAME
    request.model_spec.signature_name = 'ticketCatFeature2'
    request.inputs['input'].CopyFrom(tf.contrib.util.make_tensor_proto(data, shape=[200]))


    # print stub.Predict(request, 100)
    return str(stub.Classify(request, 50))


port = os.getenv('PORT', '5000')
if __name__ == "__main__":
    app.debug = not os.getenv('PORT')
    app.run(host='0.0.0.0', port=int(port))

```
I'm totally new to tensorflow serving and have no clue what to do with this error message and can't really find issues with this problem

**Comment by jeffersonramoslucas** [comment]
I'm also having this problem, any solution?
