### ISSUE TITLE
TensorFlow_serving is broken on ci.bazel.io

### ISSUE THREAD

**Issue by meteorcloudy** [tensorflow/serving#99]
http://ci.bazel.io/job/TensorFlow_Serving/112/BAZEL_VERSION=HEAD,PLATFORM_NAME=linux-x86_64/console
```
FAIL: //tensorflow_serving/session_bundle:session_bundle_py_test (see /home/ci/.cache/bazel/_bazel_ci/e409f7152fa45ddf3337f1660b5273b9/execroot/linux-x86_64/bazel-out/local-fastbuild/testlogs/tensorflow_serving/session_bundle/session_bundle_py_test/test.log)
____From Testing //tensorflow_serving/session_bundle:session_bundle_py_test:
==================== Test output for //tensorflow_serving/session_bundle:session_bundle_py_test:
.E.
======================================================================
ERROR: testBasic (__main__.SessionBundleLoadTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ci/.cache/bazel/_bazel_ci/e409f7152fa45ddf3337f1660b5273b9/execroot/linux-x86_64/bazel-out/local-fastbuild/bin/tensorflow_serving/session_bundle/session_bundle_py_test.runfiles/tf_serving/tensorflow_serving/session_bundle/session_bundle_test.py", line 39, in testBasic
    base_path, target="", config=tf.ConfigProto(device_count={"CPU": 2}))
  File "/home/ci/.cache/bazel/_bazel_ci/e409f7152fa45ddf3337f1660b5273b9/execroot/linux-x86_64/bazel-out/local-fastbuild/bin/tensorflow_serving/session_bundle/session_bundle_py_test.runfiles/tf_serving/tensorflow_serving/session_bundle/session_bundle.py", line 57, in LoadSessionBundleFromPath
    meta_graph_filename)
RuntimeError: Expected meta graph file missing /home/ci/.cache/bazel/_bazel_ci/e409f7152fa45ddf3337f1660b5273b9/execroot/linux-x86_64/bazel-out/local-fastbuild/bin/tensorflow_serving/session_bundle/session_bundle_py_test.runfiles/tensorflow_serving/session_bundle/example/half_plus_two/00000123/export.meta
```

**Comment by kirilg** [comment]
This test is passing at head with Bazel 0.2.1 and locally for me with 0.2.2. There were no recent changes to this test. Could this be a Bazel regression @HEAD?

base_path, as computed [here](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/session_bundle/session_bundle_test.py#L31) should include the workspace name in the runfiles dir - see [here](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/test_util/test_util.py#L38). The path in the error message is ".../session_bundle_py_test.runfiles/tensorflow_serving/session_bundle/...", but should be ".../session_bundle_py_test.runfiles/tf_serving/..." in Bazel >= 0.2.2.

@kchodorow is this an issue with the latest Bazel or something with TF Serving that I missed?

**Comment by meteorcloudy** [comment]
The change causing this bug has been reverted, but there is still a time out test. I'll open a new issue for that.
